### ISSUE TITLE
Optimize Redux Storage

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1146]
- [ ] Do not store too many messages. Use https://github.com/rt2zz/redux-persist-transform-compress
- [ ] Potentially compress the store if that is faster (compression is faster than storing more data?) Use https://github.com/edy/redux-persist-transform-filter

**Comment by dhruvdutt** [comment]
@zulipbot claim

**Comment by dhruvdutt** [comment]
@borisyankov Any update to keep in mind while working on this?

**Comment by borisyankov** [comment]
Treat these as two separate tasks.

The compression idea might work or it might not work.
Make sure to compare the timings in the Diagnostics screen before and after.

**Comment by gnprice** [comment]
In 19dfdf2ef and d1cc06ba6 (#2822), in 2018-07, we started compressing the persisted Redux state, on Android which is where there was an acute need to do so. The commit message on 19dfdf2ef explains why that was important on Android, and also why "redux-persist-transform-compress" wasn't a helpful tool.

There certainly are other things we could do to improve how we persist our Redux state: we might make our message cache more complex to evict or expire some data, we might add compression on iOS, we might reorganize so we don't store e.g. the whole `state.users` in (on Android) one row of a SQLite table, we might do other things.

I don't think any of these are a priority, because since the compression we added in 2018 I don't think this has come up as an important factor in users' experience of the app. When we do find that there's a problem to be solved which is meaningful for users, we'll file individual issues that start from information about the problem, and explore solutions from there.
