### ISSUE TITLE
Unexpected rendering of markdown

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1184]
Web: 
<img width="814" alt="screen shot 2017-09-18 at 3 39 10 pm" src="https://user-images.githubusercontent.com/12700799/30537519-9852d71c-9c87-11e7-9625-24fab3dc85a4.png">

Mobile: 
<img width="374" alt="screen shot 2017-09-18 at 3 38 56 pm" src="https://user-images.githubusercontent.com/12700799/30537527-9b8c094e-9c87-11e7-9102-e40aa5b8111b.png">

Markdown: 
<pre>
We emphasize that we will not able to be visualized :thumbs_down:  to investigate the construction of the lookaside buffer.</pre>

That break after visualized should not be there!

**Comment by brainwane** [comment]
@borisyankov could you elaborate on that a little? Is it a problem with the Markdown spec itself, or the emoji library we use, or something else?

**Comment by borisyankov** [comment]
@brainwane and mentioning @timabbott as he is likely interested why this happens.

The problem is how the native components work, and the fact that we often have to render complex HTML. If we would render simple text with some links, some images etc. we would be able to render correctly 100% of it.

There are two components in React Native (and generally in the native platforms too) - one is 'View' that behaves like 'div' blocks, and the other is 'Text' that behaves like 'span' blocks. The problem is we can't embed 'View' inside 'Text' while in HTML you can do anything.

In the beginning, we had a better render for these cases, but they broke completely in more complex messages, and break sometimes meant 'crash the app.

In this very specific case, there are three blocks, one text, then the image/emoticon and then one more text. They are aligned in two rows, just as a floating 'div' would do, or even more correctly as a 'flexbox' with 'wrap'.

**Comment by borisyankov** [comment]
@timabbott I totally forgot about this... but the WebView is still a viable option, not only with helping us show 100% html render, but also these tricky positioning issues and sticky headers.

@vishwesh3 I am curious, how good are you with HTML/CSS (if we go for WebView, I can do it alone, but would be nice if you can help ;) )

**Comment by vishwesh3** [comment]
yea! I have a good knowledge of HTML/CSS (have done some web projects :)) . Would love to work with you :) 😄 


Major problem here is how blocks are separated (line break and all) natively. I have spent lots of hours on this in GSoC time. 
Today finally I got a way to handle such cases (why not to create a separate block for each one 🤔 ) , how its looks now
![image](https://user-images.githubusercontent.com/18511177/31575038-f1b38734-b0fa-11e7-8989-d1d9c6a04908.png)


I am creating a PR for this one and we can have discussion on this approach there.

**Comment by vishwesh3** [comment]
PR https://github.com/zulip/zulip-mobile/pull/1308 :)

**Comment by kunall17** [comment]
Awesome work going on @vishwesh3 

I just wanted to ask what's the problem with directly using the web view, AFAIR it was working nicely when I tried it long back?

**Comment by vishwesh3** [comment]
I really like native components over webview, so working hard to behave it
as per our requirement. :)

most people only use apps over site in browser because of the native
feeling (and I am one among them :))

so if we really got stuck and can't find a way then webview will be nice. :)

**Comment by kunall17** [comment]
Yeah, me too prefer the native components, but I do wonder the noticeable changes using WebView vs the current implementation.

(I'll check the old after my exams get over, tuesday)

**Comment by jasonaowen** [comment]
I see that this issue is closed, but I'm still experiencing the behavior described.

I appreciate the quick turnaround on this issue -- and on all the work you are doing on Zulip! I think this issue needs more work before it's done.

Specifically, #1308 added a debug option, which is a useful step, and mentioned that it needed performance testing. How does performance testing work on the zulip-mobile app? When will that happen? What other steps need to happen to get this enabled by default in production?

I searched and did not see any other related issues for markdown rendering or for performance testing. Would you mind reopening this issue? Or, shall I open a new issue to track this remaining work?

**Comment by timabbott** [comment]
@jasonaowen you should certainly still be experiencing the behavior, since we haven't done a release with the fix yet.

**Comment by jasonaowen** [comment]
@timabbott Right! I understand that. If there were a release today, though, I don't think the markdown rendering issue would be addressed - what we have right now, as I understand it, is an option in a debug screen. @borisyankov wants performance testing on the new behavior before enabling it by default, which makes sense to me. I suggest that this issue is the natural place to track that performance testing, as well as whatever additional steps need to be completed, but if you would prefer a new issue I would be happy to open one.
