### ISSUE TITLE
Android @mention notifications render as @**person** 

### ISSUE THREAD

**Issue by rspier** [zulip/zulip-mobile#1221]
Android notifications look like

@Robert some text

instead of

@Robert some text

![image](https://user-images.githubusercontent.com/43223/30881840-f890ba60-a2bb-11e7-8e93-8dd25dadf9c1.png)

**Comment by borisyankov** [comment]
@rspier did you mean that `@**Robert**` should be `@Robert`?

This change should be done on the backend. Pinging @kunall17 @timabbott

**Comment by timabbott** [comment]
@borisyankov it's not a backend bug.  Here's the message in question: https://chat.zulip.org/#narrow/stream/mobile/subject/catch-up/near/287614

**Comment by timabbott** [comment]
@rspier just to confirm, which Android app is this?

**Comment by timabbott** [comment]
(It might be the older app that we're deprecating)

**Comment by rspier** [comment]
AFAIK, it's the new app. Zulip (Beta)  Version 2.0.32

@borisyankov Yes.  If you see the image in the first comment, it's obvious that it's wrong.

(Possibly related, when you autocomplete on the web, you end up with @**Robert** in the composition box.)

**Comment by borisyankov** [comment]
I suspect it is the same on both apps, as the app does not reformat anything itself and just displays the text pushed by the server.

**Comment by kunall17** [comment]
This doesn't seem to be an easy fix, as we receive the markdown and to render the messages in Java (old app) we used a parser which parsed from html to View. 

So either we parse the content to html from the server, then send perhaps? @timabbott

**Comment by timabbott** [comment]
I feel like we're not discussing this systematically, so I'll try to be clear.  

The message was sent from the webapp, and thus rendered by the backend before being delivered to the mobile app.  Thus, the mobile app should be receiving HTML, not raw markdown, and should be using its local rendering logic to replace that HTML with the appropriate native components for the view to look good.  

So either (1) we lost the `apply_markdown` option on the event queue registration in the mobile app, and the mobile app is displaying new messages as the raw markdown rather than using the HTML (which actually given this symptom seems pretty likely) or (2) the mobile app always renders mentions in markdown, which is inconsistent with my experience.

**Comment by kunall17** [comment]
So for testing, I sent a PM with this markdown 
<pre>
@**Kunal Gupta** :100: #**checkins** [Zulip website](https://zulip.org) 
> Quoted
</pre>

And I received this markdown as content field in the GCM message resulting in this notification
![screenshot_20170927-111143](https://user-images.githubusercontent.com/12700799/30897600-cd35577c-a374-11e7-843e-41729c8c53ad.png)

**Comment by timabbott** [comment]
Ahh, that would make sense; we use `apply_markdown` in the `get_messages` and `get_events` code paths, but don't do something equivalent in the GCM code path?

**Comment by timabbott** [comment]
Having now read the code in question, the problem here is that `get_gcm_payload` and `get_apns_payload` (which generate the content in the backend) send down the first 200 bytes of `message.content` (to provide a short, truncated version).  We should be interacting with `message.rendered_content`, AKA the HTML version, and then potentially dropping HTML tags where unavailable in the markup language for push notifications (e.g. replacing the HTML tag for a mention with just the name).  

@kunall17 can you find documentation for each of GCM and APNS on whether any markup is allowed in the content of a push notification that we can consult while fixing the backend to do what we want here?  I'm imagining what we want is a pipeline of the form:
(1) Access the renderd markdown
(2) Apply a "drop HTML tags" conversion to make it only use syntax valid in the GCM/APNS system
(3) Then truncated to 200 characters (or whatever length we thing is correct).

**Comment by borisyankov** [comment]
Not sure if html content is allowed, but the other important point is that we do not handle the notifications in a common JS code. Meaning, we better preprocess it on the server, or we'll have to reimplement that in Java and Objective-C/Swift. @kunall17 can you confirm this is correct?

**Comment by kunall17** [comment]
Can be closed now as fixed

Sent - 
<pre>**bold** @**Kunal Gupta** :laughing:</pre>

Received - 
![screenshot_20171007-134255](https://user-images.githubusercontent.com/12700799/31307046-df97b4e8-ab79-11e7-8d53-78f462c54951.png)
