### ISSUE TITLE
Notifications icon isn't cleared properly when messages get read

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1227]
I just got this report from a new user to the RN app: 

"a day later, the app icon still thinks I have 1 notification to view (this is clearly not true)"

We should do a careful audit on the code for handling this and make sure the algorithm is correct.  Presumably we want the notification cleared whether the message is read in the app or on the web... we may want to use the `unread_msgs` data structure for this stuff.

**Comment by borisyankov** [comment]
I would have asked if this is Android or iOS, but I think we are completely missing the dismissal code, so it should be the same solution for both. @kunall17 what do you think about this?

**Comment by kunall17** [comment]
Works fine on android, but on iOS it will constantly show 1 message even if several messages are received!

**Comment by jasonaowen** [comment]
I'm experiencing the same issue on Android: on a thread that is more than one screen long, even if I scroll all the way to the top and all the way to the bottom, the thread still shows one unread message in the topic list.

(Android Zulip app, version 2.0.32)

**Comment by kunall17** [comment]
@jasonaowen Thanks for report, you're talking about the UnreadNotice which shows "1 Unread message" and a button to `mark all as read` which is already reported here https://github.com/zulip/zulip-mobile/issues/1291 

This issue was related to badge count always set to 1 in the app drawer of iOS. 
And is temporarily fixed and can be closed!

**Comment by borisyankov** [comment]
I'll fix the #1291 next. Closing this.
