### ISSUE TITLE
Upload the application to F-Droid

### ISSUE THREAD

**Issue by marmistrz** [zulip/zulip-mobile#1270]

**Comment by borisyankov** [comment]
Thanks for the suggestion, Marcin. I am not familiar with F-Droid.
Do we need to register or can anyone submit it?

We are providing APK files with each release here:
https://github.com/zulip/zulip-mobile/releases

**Comment by Be-ing** [comment]
I have opened a request for this on [F-Droid's tracker](https://gitlab.com/fdroid/rfp/issues/386).

**Comment by Be-ing** [comment]
The Android app is quite laggy for me on LineageOS without GApps. I don't know if this is an issue with the app in general or if the lack of GCM push notifications is slowing it down.

**Comment by marmistrz** [comment]
You need to make a merge request to the following repository: https://gitlab.com/fdroid/fdroiddata
The application must not used closed-source dependencies. You may want to ask the F-Droid people at the IRC channel #fdroid on Freenode or on the F-Droid forum for more details on the process.

**Comment by Be-ing** [comment]
F-Droid has an [FAQ for app developers](https://f-droid.org/en/docs/FAQ_-_App_Developers/) and [a guide for contributing](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md).

**Comment by borisyankov** [comment]
@vishwesh3 do you want to have a look at the perf issues on LineageOS? I am curious what is going on.

**Comment by Be-ing** [comment]
Until this happens, it would be nice if https://zulipchat.com/apps/android mentioned that the APK files can be downloaded from https://github.com/zulip/zulip-mobile/releases

**Comment by anirudhjain75** [comment]
I use lineageOS on Nexus 6 works for me perfectly 🤔

**Comment by anirudhjain75** [comment]
@zulipbot claim

**Comment by pulkonet** [comment]
@anirudhjain75 any success in uploading the app to fdroid?

**Comment by Serkan-devel** [comment]
Any updates on this?

**Comment by downeym** [comment]
> Until this happens, it would be nice if https://zulipchat.com/apps/android mentioned that the APK files can be downloaded from https://github.com/zulip/zulip-mobile/releases

+1 ... it's not obvious that folks don't have to use Google services in order to download and use Zulip. 😄

**Comment by Serkan-devel** [comment]
but it's easier to update that way

**Comment by gnprice** [comment]
@downeym Thanks for the suggestion/bump! I agree.

I took a quick look at the relevant server code, and it isn't a trivial matter of adding a `<p><a>...` to an HTML template. So I'll file an issue there to see about getting someone to make that change.

**Comment by gnprice** [comment]
Just a quick note that we [heard from](https://chat.zulip.org/#narrow/stream/2-general/topic/Testing.20mobile.20client/near/811328) a user who mentioned they were using the app "from F-Droid", and they explained that they were getting it from the IzzyOnDroid app repository:
https://apt.izzysoft.de/fdroid/index/apk/com.zulipmobile
https://apt.izzysoft.de/fdroid/index/info
But AFAICT the work of getting Zulip into the F-Droid repo itself is still open for someone to pick up and do.

(FTR there seem to be some inferences on that page that aren't true: we do not use Firebase Analytics, in fact we [go out of our way not to](https://github.com/zulip/zulip-mobile/commit/f507b025c); and we don't require any non-free dependencies.)

**Comment by mdimjasevic** [comment]
As someone interested in seeing this happening, I'm just sending a gentle reminder. I am not sure if this has been resolved in the meantime, but there was a build dependency problem where some React libraries required Play Services: https://gitlab.com/fdroid/rfp/issues/386#note_134825356

Zulip is free software so it would be great to have it available in a free software repository for Android-based devices!

**Comment by timabbott** [comment]
One thing worth mentioning is that we do distribute the app via a direct download link to the Android APK on zulipchat.com/apps.  Obviously, this isn't the same as froid, but does mean it can be installed without going through the Play store.

**Comment by mdimjasevic** [comment]
> One thing worth mentioning is that we do distribute the app via a direct download link to the Android APK on zulipchat.com/apps. Obviously, this isn't the same as froid, but does mean it can be installed without going through the Play store.

Thank you for your reply, @timabbott! I am aware of the direct link option. Still, it would be great to see Zulip in the official F-Droid repository.

**Comment by gnprice** [comment]
> I am not sure if this has been resolved in the meantime, but there was a build dependency problem where some React libraries required Play Services: https://gitlab.com/fdroid/rfp/issues/386#note_134825356

Interesting, thanks for highlighting that.

One of those, `react-native-notifications`, is no longer part of our Android build since 01b33ad31. (Rather, I think its JS still gets included because we use it on iOS; but its Gradle project is gone from our build.)

The other, `react-native-device-info`, does a few small things for us and I don't think any of them actually involve Play Services, so this is really just an issue with its build metadata.

---

The next step for this remains for someone who uses F-Droid and is excited about seeing Zulip in that repo to try preparing an F-Droid package for it. You'll want to consult F-Droid's documentation about how to do that; I think it ultimately turns into a merge request on their repo.

If you run into problems where Zulip won't build there, due to those Play Services mentions or another issue, either this thread or the `#mobile` stream on chat.zulip.org is a good place to ask; we'll be happy to answer questions.

**Comment by varac** [comment]
Any progress on this ?

**Comment by dioraman** [comment]
> Any progress on this ?

Hi all! I second the question. :)

**Comment by abhas** [comment]
It is available via the [IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/index.php). Downloading it from there will also help you get updates. It works fine without Google Play or MicroG installed. I have used it that way in the past.

https://apt.izzysoft.de/fdroid/index/apk/com.zulipmobile

**Comment by monnier** [comment]
I'm glad it's available on that IzzyOnDroid repository, but it's not the same as being in *the* F-Droid repository.  Since we are talking about Free Software and installation of *binaries*, an important issue is whether that binary indeed corresponds to the Free Software we expect to install.  The F-Droid repository tries to provide that trust.  IzzyOnDroid on the other hand does not (and for good reasons: I do not intend to disparage that service).

**Comment by WesleyAC** [comment]
I [looked into](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/fdroid/near/1203052) what it would take to package Zulip for F-Droid today, and it's more work than the core team can take on right now. However, if someone else was to package Zulip for F-Droid, we'd be very happy to add bumping the version in F-Droid to our release checklist. In the meantime, people can get the APK from our [GitHub releases page](https://github.com/zulip/zulip-mobile/releases), use the IzzyOnDroid repo linked above (which is unofficial, but currently appears to get the APK directly from our GitHub release), or build from source.

**Comment by gnprice** [comment]
Thanks, those details are helpful. Nothing to apologize for. I've filed #5087 as an issue specifically for getting that code out of the build.

I'll reiterate, though, that we do not use Firebase Analytics -- it's not configured, and it's not reporting anything. (Details in that issue #5087, which is also the best place to discuss further.) But it would be nice to remove the code too, so that a scanner like yours can more easily be confident of that.

> PS, for the subject of this issue: you might consider switching to [UnifiedPush](https://unifiedpush.org/) for cloud messaging.

Yeah, this is #3838. I'll copy the other details in your comment there.

**Comment by IzzySoft** [comment]
> we do not use Firebase Analytics

I cannot tell that without running some tests, so I'm far from accusing you of this :wink: My library scanner can only tell what is present, not whether it's used (or if it's only a stub). So ideally indeed, removing the code brings confidence: what's not present cannot be used. Above config should take care that the build doesn't include the analytics parts (so my scanner wouldn't report it as it's no longer found) while keeping FCM intact.

Great to read UP was already brought up and you are open to it (side-note: OpenPush seems not too active anymore, long time not heard of). The more apps making use of it, the more useful it becomes – for the obvious reasons (a single network session being kept alive for all apps to use). Wishing you easy progress with all 3 topics (size, getting rid of the analytics code, and bringing in UP) :smiley:

**Comment by dm17** [comment]
I would considering Zulip if it was up-to-date on F-DROID.

**Comment by gnprice** [comment]
@IzzySoft Thanks for the ping -- sorry I let this hang.

We did some further debugging on this back in October, which I've just written up at https://github.com/zulip/zulip-mobile/issues/5086#issuecomment-1067355270 . Let's continue discussion of the APK size on that thread.

I'm going to go see about splitting the APKs up as you suggested: #5295 .

**Comment by IzzySoft** [comment]
Thanks @gnprice – I've already joined the discussion there :smiley:

**Comment by dm17** [comment]
> We are providing APK files with each release here:
> https://github.com/zulip/zulip-mobile/releases

The cool thing about F-DROID we can freely download stuff and have a certain level of privacy because they screen for such things. Then there is an easy question of "what's the difference between the GitHub and F-DROID release" - and if there is no difference, then we can just use GitHub to have a quicker release cycle. So, existing on F-DROID is kind of a third party review process.

**Comment by IzzySoft** [comment]
Hehe… that's the reason why some apps are on F-Droid and in my repo as well (e.g. FairEmail) – quicker release cycle :wink:

**Comment by gnprice** [comment]
@dm17 Thanks for that feedback about your use case!

**Comment by IzzySoft** [comment]
Just stumbled about [this RFP at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/386) during the triage runs, which was opened by @Be-ing. There were some packaging tries, but they got stuck with build errors (see e.g. [here](https://gitlab.com/fdroid/rfp/-/issues/386#note_695233302)). Any chance one of you could have a look at that to get things rolling there as well?

**Comment by IzzySoft** [comment]
@gnprice @chrisbobbe any chance? The due-date popped up again, so the RFP at F-Droid now enters the candidate-to-close state: if we see no chance to process the request, we have to close it in 4 weeks.

**Comment by IzzySoft** [comment]
Well… We can reopen the RFP again once you're ready, or start a new one. But as there was no reply at all, it will now be closed due to inactivity, sorry. Looking forward to a revival then…

**Comment by gnprice** [comment]
Ah, just looking at this now. From those build errors:
```
/home/vagrant/build/com.zulipmobile/android/app/src/main/java/com/zulipmobile/notifications/FcmListenerService.java:6: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;
                                    ^
```

It looks like they're all saying that the Firebase messaging libraries (aka FCM), which we use for push notifications, weren't found.

That in turn is presumably because of this line in the quoted build script:
```
    prebuild:
      - sed -i … -e '/firebase/d' build.gradle
```
which deletes the line in our build config that pulls in that dependency.

I think the way forward on that would be for someone to send a PR here that makes the use of FCM a build-time option. I don't think we'll find time on the core team to write such an option, but I'd be happy to review and merge a PR to add one. Then that will make for a more sustainable way to support that variation than trying to sed out lines from the build config.

For how to implement such an option, probably the easiest way is with a [Gradle "project property"](https://docs.gradle.org/7.4.2/userguide/build_environment.html#sec:project_properties). For an example, see our use of a `sentry` property: it's consumed at the `if (hasProperty('sentry'))` in `android/app/build.gradle`, and it's set by passing `-Psentry` on the Gradle command line in `tools/android`. Here, we might call it `nofcm`, so `-Pnofcm` on the Gradle command line.

I believe it would also be possible to set up the no-FCM build as a different flavor or version in our Android build config. That might even be cleaner, but I haven't really used that mechanism so can't offer suggestions on how to do it that way.

**Comment by IzzySoft** [comment]
A different build flavor is what most projects use for that case. Another option might be using @UnifiedPush and then have their simple FCM distributor included with the non-free version (so e.g. PlayStore users won't notice a difference, while others have the option to use the distributor of their choice). That way, push messages would be possible in both variants. If that sounds interesting to you, you can find [some pointers here](https://gitlab.com/-/snippets/1896503#push) in my snippet.

Note however that I am no dev, so I cannot provide you a corresponding PR – I can only share my findings :wink:

**Comment by licaon-kter** [comment]
The recipe is ready to be merged: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11516

F-Droid awaits for this to be in: https://github.com/zulip/zulip-mobile/pull/5462

**Comment by chrisbobbe** [comment]
Thanks, @licaon-kter! Does this mean the build errors Greg discussed in https://github.com/zulip/zulip-mobile/issues/1270#issuecomment-1145476504 were resolved? I'm curious about that because I don't remember a PR going by that matches this description:

> I think the way forward on that would be for someone to send a PR here that makes the use of FCM a build-time option.

**Comment by licaon-kter** [comment]
This issue has been open for the last 5 years? The way forward might sound nice, hope someone can make such a nice PR. In the mean time, if @linsui can add screenshots this is ready to be merged. Is this ok?

**Comment by gnprice** [comment]
Sure, if you have a build that works and that meets F-Droid's requirements for merging, then it's not a problem for us how you make it work.

The suggestion I made above was because the previous attempt was hitting build errors, and I offered a suggestion for how to handle them. Those build errors are all that @chrisbobbe was asking about. Based on the CI results on that thread https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11516 , I gather that the build errors have been dealt with one way or another.

Just to make sure we have a shared set of expectations: there's a lot of stuff in that prebuild recipe that we can't guarantee will keep working. It's entirely likely that some of that recipe will break in the future. That's what I was saying here, above:

> that will make for a more sustainable way to support that variation than trying to sed out lines from the build config.

But if you're OK with that, and F-Droid in general is OK with that, then we don't have any intention of standing in the way.

**Comment by gnprice** [comment]
And I see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11516 has been merged! Thansk to @linsui and everyone else who contributed.

Are there any other steps remaining which this issue can help track, or should it be closed?

**Comment by gnprice** [comment]
> Are there any other steps remaining which this issue can help track, or should it be closed?

Hearing none, I've let the issue be closed by @Poussinou's #5481 just now, which added a link in our README to the F-Droid page for the app. Thanks again, everyone :slightly_smiling_face: 

If further issues come up which would be good to address or track in this repo, please don't hesitate to file a new issue or PR as usual.

**Comment by Be-ing** [comment]
https://zulip.com/apps/android could be updated to link to F-Droid as well

**Comment by IzzySoft** [comment]
Congrats to your listing at F-Droid! As the link in the Readme already points there, I'll now remove the armeabi build from my repo to avoid confusion ([see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background). Should you want it back for some reason, just drop me a note to restore it.
