### ISSUE TITLE
Unread notice stuck at 1 unread message 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1291]
After scrolling at the bottom of the home narrow as well

**Comment by borisyankov** [comment]
Maybe we have issue with the message ids that ScrollView reports? Is this Android? If yes, maybe @vishwesh3 can have a look at?

**Comment by vishwesh3** [comment]
I was experiencing this few versions back. But can't reproduce on current master. 
To have an better experience with unread count (and messages) I am thinking to have model something like outbox. Once message is read (I mean visible's ids is sent from scrollView then count it as read irrespective of it is present in `unread`). 

When I am connected to slow internet it's takes some time (even 5-6 seconds) to to hide unread count notice after reaching to bottom. For such situation we need to consider [unsentMessageIds](https://github.com/zulip/zulip-mobile/blob/master/src/api/queueMarkAsRead.js) to get updated unread message.

I am thinking to work on it. Thoughts?

**Comment by vishwesh3** [comment]
One such case on Android is:- if last message of the list contains reaction (in my case there was only one reaction) then that message is not mark as read. Most probably this is because of visible id's in out `AnchorScrollView`

**Comment by kunall17** [comment]
I still can reproduce this bug on the latest update, and no reaction was there on the last message 

![screenshot_20171014-184026](https://user-images.githubusercontent.com/12700799/31575972-60c6ef3a-b10f-11e7-94f6-7026645574ec.png)

> I am thinking to have model something like outbox. Once message is read (I mean visible's ids is sent from scrollView then count it as read irrespective of it is present in unread).

I highly agree on this point, and I have faced the similar problem.
The priority should be not to display the user that it's unread, maybe have a queue buffer like structure in which read messages are stored which are not sent to the server (something like the old native app AFAIR)

**Comment by vishwesh3** [comment]
Okay! Cool Working on it :+1:

On 14-Oct-2017 6:46 PM, "Kunal Gupta" <notifications@github.com> wrote:

I still can reproduce this bug on the latest update, and no reaction was
there on the last message

[image: screenshot_20171014-184026]
<https://user-images.githubusercontent.com/12700799/31575972-60c6ef3a-b10f-11e7-94f6-7026645574ec.png>

I am thinking to have model something like outbox. Once message is read (I
mean visible's ids is sent from scrollView then count it as read
irrespective of it is present in unread).

I highly agree on this point, and I have faced the similar problem.
The priority should be not to display the user that it's unread, maybe have
a queue buffer like structure in which read messages are stored which are
not sent to the server (something like the old native app AFAIR)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/zulip/zulip-mobile/issues/1291#issuecomment-336634357>,
or mute the thread
