### ISSUE TITLE
Mark messages as unread

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1325]
Allow to mark something as unread so you read it on the web (for when you have a long reply you need to write).

**Comment by borisyankov** [comment]
Closing as implemented.
The unread cards UI will provide an additional way to do this.

**Comment by boxybox** [comment]
> Closing as implemented.
> The unread cards UI will provide an additional way to do this.

Hi, 

I can't find the option to mark a message as unread. 

Nor can I find it in the documentation here https://zulipchat.com/help/

If this feature was implemented then how can I use it?

**Comment by gnprice** [comment]
Hi @boxybox!

This feature isn't part of how Zulip works. For the use case in the issue description:
> Allow to mark something as unread so you read it on the web (for when you have a long reply you need to write).

what we find works very well is to "star" a message:
https://zulipchat.com/help/star-a-message
On mobile, you can do this by long-pressing the message and choosing "Star message" from the popup menu.

Not sure why the issue was closed that way in 2017. The best guess I have is that the author was thinking of the "mark as *read*" feature -- to mark a whole conversation or stream as read all at once -- which we added around that time.

In any case, the correct resolution is that this issue is closed because it's a feature we don't intend to add :smile:, because we think starring messages is a solution that makes a better user experience.

**Comment by iexcept** [comment]
@gnprice could you please star your dick!!! okay?

**Comment by ajdelgado** [comment]
Star message doesn't mean the same for a user. A starring is interpreted as something important, but unread is something you didn't read throw and might be or not important. So you might take a quick look to see what it is but didn't understand and need follow up later.

**Comment by gnprice** [comment]
@ajdelgado Nevertheless we find that starring works well for this use case. If I need to follow up later, then that's important, so starring works well for highlighting it for me to do so. Once I have read it more completely, I unstar it, unless there's some reason it remains important.

In any case this feature isn't mobile-specific, so if you'd like to discuss this feature request further, the best venue will be a general Zulip venue. There's a GitHub issue thread zulip/zulip#2676, and you're also welcome to come say hello on chat.zulip.org and start a discussion there; I recommend the stream `#feedback`.
