### ISSUE TITLE
Scroll position doesn't take you to the latest unread messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1337]
We've talked about this a lot, but I think it's worth having an issue to track this, since I think it's by a large margin our most important bug at this point.  At least on Android, every time I go to a view via the UI, it feels like it takes me to a place about 20-30 messages above where one would expect.  The correct algorithm is detailed in http://zulip.readthedocs.io/en/latest/pointer.html , but roughly, we should take you to the first unread message (if any exist in the new view), otherwise to the bottom.

**Comment by borisyankov** [comment]
The next release should fix this. 
In order to make debugging this issue easier in production, I have added a feature in 'Settings -> Diagnostics -> Debug' called 'Distinguish unread messages'. It is a temporary configuration that does reset on restart (so no one leaves it on by mistake). It will color the unread messages in a vivid pink.

**Comment by borisyankov** [comment]
A definitive fix is merged. Closing the issue.
