### ISSUE TITLE
Try to find when back button does not work.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1456]
Sometimes on pressing back button on Android nothing happens. One need to press it multiple times. So this issues is to find is there any specific case/steps of reproduce it.

* Download app from [Play Store](https://play.google.com/store/apps/details?id=com.zulipmobile&hl=en) or [App Store](https://itunes.apple.com/us/app/zulip/id1203036395?mt=8).
* Play with app, switch between different screens. Open Lightbox (click on images in messages), scroll over message list, switch narrow, send messages etc.
* Note down paths, where you find it is broken.

**Comment by cdikibo** [comment]
@zulipbot label "GCI task"

**Comment by borisyankov** [comment]
Hint: this is likely related to React Navigation and the fact that we have several navigations inside each other (Stack, Tabs, Drawer)

**Comment by thejwzhang** [comment]
@zulipbot claim

**Comment by thejwzhang** [comment]
I've noticed a few areas where the back button does not work as expected on the Android app: 

1. This isn't exactly related to the original issue, but hitting the navigation bar back button in any stream/topic exits the app and goes into the home screen. Instead, I think it should go back to the last screen you visited. For example, if you start the app in a stream and then you click the "Starred" messages tab, hitting the back button should go to the stream you came from instead of exiting the app.

2. In the Language menu, pressing the back button the top left hand corner works as expected, but hitting the back button on the navigation bar does not work, sometimes requiring multiple taps and other times not responding. Additionally, I've noticed that occasionally the back button at the top left navigates completely out of the pop in side window and leaves you at a stream.

3. The same issue occurs when you click "Create new stream," where the back button that shows up works, but the back button in the navigation bar does not work as expected.

4. If you hold down a message, tap the share button, and then click the back button (or click any empty space above the pop up), it exits entirely and puts you into the stream again, instead of the menu that pops up after you hold a message.

**Comment by jainkuniya** [comment]
nice finds @thejwzhang.
First one is a feature request :) Second & third are good finds 👍 
I am not able to get what you mean in fourth one. Can you please explain it a bit more (or even share a video/GIF of it)?

**Comment by thejwzhang** [comment]
Thanks! 
For the fourth one, I've created a video to hopefully demonstrate what is going on. 
In this video, I try the task twice with my taps shown. I hold down a message, then a menu comes up with a "Share" option. After tapping the "Share" option, the Android share menu comes up. When I tap the back button to exit that menu, it goes back to the message screen (it goes back 2 layers). It should simply exit the Android share menu and display the initial menu.

Since I can't attach videos here on Github, view the video [here](https://drive.google.com/file/d/1FJYnWwMaKvlBmLxsk1NZilvIyldvzYvH/view?usp=sharing).

**Comment by jainkuniya** [comment]
Not sure. if this is a bug or not. BTW I am in favour of current behaviour.

**Comment by borisyankov** [comment]
I consider these more or less as bugs.
For point 1 we already have a thing ready that will be finished up and merged in few weeks (#1312)
For points 2 and 3 - I think it is either a bug in React Navigation or something similar (I did update it in the last release, but it is still there)
Point 4 - yeah, I would expect it to work exactly as you describe it, not sure what we can do about it.

@jainkuniya if you have time, I think 2 and 3 are most important to figure out.

**Comment by jainkuniya** [comment]
@zulipbot claim

**Comment by jainkuniya** [comment]
Gone through `react-navigation` library & finally found the cause of #M1456 & submitted PR #M1657 :)
