### ISSUE TITLE
Whitespace issue with few messages in a narrow

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#165]
Example:
<img width="377" alt="screenshot 2017-01-02 15 30 56" src="https://cloud.githubusercontent.com/assets/4666213/21598027/4e14ce34-d109-11e6-94c4-9f8e86cba4d7.png">

**Comment by borisyankov** [comment]
Elaborate.

**Comment by timabbott** [comment]
The issue here is that we should display the message at the top of the screen and have whitespace below, similar to how the Zulip webapp works.  That way, when new messages come in, it doesn't require unnecessary scrolling down.

**Comment by borisyankov** [comment]
That is intentional. It works like that in all major competitors:
* Slack
* Facebook Messenger
* Google Hangouts

**Comment by timabbott** [comment]
Plenty of other chat tools work this way (with short feeds placed at the top rather than the bottom), e.g. the default Android text messaging app.  But the important thing for Zulip is that we place much more emphasis than other products on actually tracking what you've read (as opposed to just marking entire views as read as soon as you look at them), and that model impacts what the best UI is for certain things.

It also just looks weird with the heading showing what you're looking at (which is at the top of the screen and not repeated) so far from the actual message.  

The bottom whitespace is I think also something we'll want even if there is significant message history, so that after you scroll to the bottom, the next message that comes in is on-screen without scrolling your view.

**Comment by borisyankov** [comment]
This is how the default messaging app on Android looks like:
https://goo.gl/photos/sya7gFkBoBMWwQy59

**Comment by borisyankov** [comment]
The sticking to bottom is a completely separate issue that has to be fixed either way.

**Comment by timabbott** [comment]
Interesting, I seem to have a totally different one.

**Comment by borisyankov** [comment]
What brand of phone do you have?
I am with Nexus 6P - so this is the actual default messaging app coming from Google.
If you have Samsung/Sony etc. they tend to have their own apps.

**Comment by timabbott** [comment]
Samsung, this is probably their app.  

Regardless, I think for Zulip in particular, because of the potential for multiple layers of headings (if you're narrowed to a stream, for example), it's probably best to have results appear at the top.
