### ISSUE TITLE
Show both stream and topic in title when narrowed to a topic

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#172]
Clicking on the stream name should return to the stream narrow

**Comment by borisyankov** [comment]
Very unlikely this will fit on a mobile screen.

**Comment by timabbott** [comment]
I would show the full stream name, and then a cutoff version of the topic name (since stream names tend to be short).  We should also have a way to see the full topic name; some ideas include:
(1) Something in the top you can press to see the full name wrapped to multiple lines
(2) Making the area horizontally scrollable.
(3) Making the heading area go to 2 lines of height if it's really long.
(4) Showing the topic on a second line if it is too long

But regardless, for most users having the stream name be visible is probably more important than the topic (though it's important it be visible that we're narrowed to a topic).
