### ISSUE TITLE
Add an initial automated test suite

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#20]

**Comment by borisyankov** [comment]
I will take care of this.
I already wanted to write few tests for easier debugging, instead of going through emulator, inspectors etc.

First quick steps I'll do:
1. Fix all eslint warnings and enable eslint run
2. Fix all Flow warnings and enable flow
3. Run eslint + flow + mocha  on npm run test
4. Configure and enable Travis to run these

**Comment by timabbott** [comment]
Sounds great to me!

**Comment by borisyankov** [comment]
@timabbott this is done (based on it being only 'initial')

**Comment by timabbott** [comment]
Yep, sounds good, we can close this.  I figure future issues about tests will be about specific things we want to do with testing.
