### ISSUE TITLE
Crash on welcome screen with "unexpected url"

### ISSUE THREAD

**Issue by anurag1018** [zulip/zulip-mobile#2016]
<img width="304" alt="screen shot 2018-03-05 at 10 51 25 pm" src="https://user-images.githubusercontent.com/17769227/36990043-6f6125a4-20c9-11e8-9321-fc5b5ef1fd3b.png">

I tried including special characters in the url (! and @ in the above case)
This causes an error message on the url.
If we could match submitted the url with the permitted valid urls using regular expressions and display a message such as "Invalid URL" before sending it to the server for connection request, it will probably fix the issue.

**Comment by anurag1018** [comment]
@zulipbot claim

**Comment by jainkuniya** [comment]
This is Android specific.
Good find @anurag1018 👍

**Comment by anurag1018** [comment]
Yeah Ios automatically rejects the promise in these special cases.
After researching a bit, I found it is not possible to solve the bug through regex validation since it is possible to create an organization with special characters in its name.
The only way is through the promise rejection embedded in the code. I tried implementing a catch block with the fetch API but it doesn't seem to have any effect. Any Ideas?

**Comment by borisyankov** [comment]
An exception is not thrown as the underlying native Android code crashes and it doesn't bubble up.

**Comment by anurag1018** [comment]
<img width="387" alt="screen shot 2018-03-14 at 12 39 48 pm" src="https://user-images.githubusercontent.com/17769227/37473827-feffcae4-2894-11e8-838a-a91bc7b79cc6.png">
Turns out that subdomain accepts only letters, numbers and hyphens. The next part for validation of this was easy.

**Comment by gnprice** [comment]
Marking as critical, because
* a crash is always pretty bad, and
* a bug that blocks the user when they're first trying to use the app is super bad, and
* we [regularly see this issue in Sentry](https://sentry.io/zulip/zulip-mobile/issues/342464306/events/latest/), so people are in fact hitting it.

@anurag1018 , unassigning you because it's been a couple of weeks; this is open for anyone to pick up.

A solid fix here would be two-layered:
* The form should validate the organization URL as a well-formed URL, and when it's not it should give feedback instead of trying to make an HTTP request that will crash.
* If we somehow end up making an HTTP request with an invalid URL, it should produce an exception we can catch, not crash in Java code -- that seems like a bug in React Native. We should try to locate an issue upstream, and file one if there isn't.

That first layer is the essential one and also easier, so that's the part that is critical to fix soon.

**Comment by gnprice** [comment]
More details at the original report of this issue, #1377 .

**Comment by borisyankov** [comment]
We already check for valid URL in the API layer. Closing as no longer crashing.

**Comment by gnprice** [comment]
For reference: it looks like the fix for this was commit 2c456c635.
