### ISSUE TITLE
settings: Use the same height for selected and unselected languages.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#2610]
The height of the row containing the selected language, 'Catalan', is greater than the heights of the rows containing all other unselected languages.

![image](https://user-images.githubusercontent.com/12771126/40864592-71bb8f5e-65c2-11e8-887b-b907ea40f0b5.png)

This isn't really an issue of usability, I just think it would feel a bit more polished if the heights of the rows remained consistent.

@gnprice @borisyankov Thoughts?

@zulipbot add "area: layout"

**Comment by gnprice** [comment]
Yeah, agreed on all counts. Thanks for raising this!

This isn't a particularly great UI for this task, but it looks like its design is trying to imitate an iOS style found in some settings, like the example with checkmarks in the right-hand screenshot at the top of [this iOS HIG page](https://developer.apple.com/ios/human-interface-guidelines/views/tables/).

It'd be good to fix the layout here so that it works right, with all the items staying at the same height. I think the items could all use a bit more padding; and the icon can probably be smaller, too (like it is in that screenshot, and in the system settings on my iPhone.)

For the exact padding, I'd refer to the [Material guidelines for a list](https://material.io/design/components/lists.html#specs). It's possible the checkmark size that looks good here (in mimicing iOS conventions) will be smaller than Material Design prescribes, though -- after all the Material prescription for this UI is somewhat different anyway (namely radio buttons.)

At some point it may be worthwhile to come back and replace this with a better language-selection UI, but that'll be more work. (Alternatively, FWIW: if this were for a task where this basically is the right UI model, then the ideal thing would be to follow platform conventions and use on Android something that won't be so alien to Android users. But for language selection there are better UIs anyway.) A quick layout fix here should be easy and will be well worth it.

**Comment by jackrzhang** [comment]
@zulipbot claim
