### ISSUE TITLE
Two login with password options when creating a new account. 

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-mobile#2622]
## Issue Summary
When creating a new account I am being presented with two login with a password options.
## Screenshot of Issue
![screenshot_20180604-003526](https://user-images.githubusercontent.com/13500254/40892580-0279e912-6791-11e8-88c2-8229dc11d26f.png)
## Version Info
Zulip Mobile: v13.4.88
Phone: Samsung Galaxy S7 Edge

**Comment by borisyankov** [comment]
Thanks for reporting this.
This happens when you have both LDAP and 'login with password' enabled.

We have fixed this issue and this will be working in the next release.
(CC @gnprice this is fixed in https://github.com/zulip/zulip-mobile/commit/f2ee751a8e431fd58f38325cea97080d9f19d4f9#diff-4482bccc9bdb5288e5d20df47ff1c595)

**Comment by adambirds** [comment]
Had a feeling it was due to that, good to know it will be fixed in the next release!

**Comment by borisyankov** [comment]
I am closing this as fixed in `master`.
