### ISSUE TITLE
Voice input via ios app just receive first word instead of full phrase

### ISSUE THREAD

**Issue by tientranphuoc** [zulip/zulip-mobile#2659]
Hello Zulip team,

This is a critical bug I think so, it's very funny and I can not understand how this bug can exist.

This bug just exist in ios app only.

Thanks.

**Comment by borisyankov** [comment]
Thanks for reporting this issue. I am not sure how actively are we using the voice dictation feature ourselves, I guess not often.

I have tested on an iPhone and I confirm the bug is reproducible 100% of the time.

The issue causing this lies in React Native and is reported here:
https://github.com/facebook/react-native/issues/18890

We have done some work on improving the compose box that might fix this (the 'uncontrolled' input one)

**Comment by a-b** [comment]
Very often! This is a valid bug and let's check why text input is breaking voice dictation.

**Comment by borisyankov** [comment]
We have a fix for that. It needs several PRs merged before that, but it should be coming soon. Few weeks I think.

**Comment by chrisbobbe** [comment]
Yep, this was fixed in https://github.com/facebook/react-native/commit/a7a2ef1bb65c6908b8ac68f8addaac1c75de98e3, released in React Native v0.57.0, which we started using in 52950733671c097733aad507edf0b7c07d700b9c, released in Zulip Mobile https://github.com/zulip/zulip-mobile/releases/tag/20.0.103 in November, 2018.

(Also confirmed that I'm not seeing this issue on my iPhone with Zulip Mobile v26.22.145.)
