### ISSUE TITLE
A `starred` tag does not appear after starring a message in a stream.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#2676]
To reproduce:

1. Star any message in any stream via long-press.
2. A tag containing `starred` text should appear below the message, but doesn't.

The same message does become marked within the web app, however. Also, if you long-press the same message again, the correct option 'Unstar message' is toggled.

This is on both Android and iOS.

**Comment by jackrzhang** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
#2843 is a good fix which we should do (and it will put us ahead of the web app! see zulip/zulip#10111); but when the user did the starring/unstarring right here in this app in front of them, it will inevitably have too much latency for many (most?) users to feel responsive because it only gets to act when the server tells it about the event.

So we should also do a local echo of this state. The webapp gets away with doing this in a totally simple-minded way: it just updates its own state, then fires off a request to the server. See `toggle_starred` in `message_flags.js`, and its callers and callees.

That's not totally awesome behavior -- the request could fail, and then the user thought they'd safely stashed away that message in a way they'd remember to see it later, and we've let them down. And that case may come up a lot more often on mobile than on desktop. But doing better is certainly more complicated.

**Comment by gnprice** [comment]
> That's not totally awesome behavior -- the request could fail, and then the user thought they'd safely stashed away that message in a way they'd remember to see it later

I just played a bit with reactions in FB Messenger, as one point of comparison to help gauge what our standards should be here. :wink: (Wait no, that's not on the FB "reaction" list. Maybe :open_mouth: ?) They did seem to be doing something, but it isn't great:
* I opened a thread, then went into airplane mode.
* Tried reacting to a message. The reaction appeared immediately. ... After I scrolled up a bit (scrolling that message offscreen), then scrolled back down, it was gone.
* Tried again. Curious how long it takes to disappear, so this time, stared at it for like 10 seconds... and it stayed. Scrolled up and down again, and again now it disappeared.
* Now I can't do any reactions at all; they just silently don't appear. Maybe it's decided it lacks a connection, and stopped doing local feedback.
* Minutes later (still in airplane mode), reactions work again. It really is about scrolling offscreen; I left one onscreen for a while and it stayed, then just dipped the message offscreen for the briefest time I could, and it was gone. And after that, it's back to not accepting reactions.
* OK, *now* when I open it again, there's a red "Airplane Mode On" banner. That wasn't there before -- I'd been surprised not to see it.
* ... But the actual behavior is just like before: it does local feedback, but it disappears on scrolling offscreen, and after that it refuses to show local feedback for a while.
* Finally, turned off airplane mode. No sign of the reactions -- looks like it didn't retry sending them. That part at least seems for the best :)

(In case these variables matter if someone else tries the behavior: this was all in a "chat head" window, on Android 8.1 Oreo. Of course Facebook is constantly changing things, and moreover running A/B tests so it's likely some behavior is different for any two people even at a given time -- so there are lots of possible variables that could cause results to vary.)

So that's at least one comparison point on mobile, in addition to the Zulip webapp, to say we likely shouldn't hold ourselves to too high a standard in this particular area.

**Comment by gnprice** [comment]
Here's one proposal for a still-pretty-simpleminded approach that may be good enough:
* When the user tries to star a message, we update our own state before firing a request to the server, just like the webapp does in `message_flags.toggle_starred`.
* Except: first we check if `getSession(state).isOnline` -- the same flag relied on by our "No Internet connection" banner in `OfflineNotice`. If we're not online, then we skip the local echo. I think we try the request anyway, just in case something's funny and it works after all; that way it'll work, just degrade to the high-latency experience.

**Comment by jackrzhang** [comment]
Hm, that scrolling behavior sounds fascinating. I'm observing nothing of the sort on my iPhone in airplane mode.
