### ISSUE TITLE
Message requesting does not work well when few messages exist

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#268]
Testing on https://zuliporg.zulipchat.com reveals some issues, very few messages shown, likely no scroll event is fired up and no older messages are fetched up.

**Comment by borisyankov** [comment]
Hmm, that might be a server issue, or I am misunderstanding something.

@timabbott Why can I see just 4-5 messages in Home in this server, while some streams I am subscribed to have many?

**Comment by timabbott** [comment]
This is because that server has no traffic.

So the way the server works when you join is that we add to your Home history something like 100 messages of recent history on your initial subscriptions.  If an org were active, you'd get more messages and things would proceed from there.

We also allow you, when narrowed to a public stream, to see the complete all-time history of that stream even from before you joined.

Trying to do that same thing with the home view would be prohibitively expensively technically (we would need to either add potentially 100K messages to your home view history when you sign up for a busy organization, or give up the model that your home view history is exactly messages that you actually saw).

**Comment by borisyankov** [comment]
So the app works as expected.
