### ISSUE TITLE
Conversation list should use cache if no connection

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2725]
If there is data for the conversation list, but trying to load users a loading indicator is shown.
Instead, it should show the previously loaded data.

**Comment by chrisbobbe** [comment]
https://github.com/zulip/zulip-mobile/issues/3802 is part of this, but it doesn't include showing a loading indicator; PR https://github.com/zulip/zulip-mobile/pull/3901 is in progress for that.

**Comment by gnprice** [comment]
I think in this issue the loading indicator is (was) the status quo, and it's asking to show the cached data.

We now do show the cached data, so this was done some time ago. And that's a problem :wink:, namely #3387, because we don't give any indication that we're loading new data and what's visible is stale.

**Comment by chrisbobbe** [comment]
> We now do show the cached data, so this was done some time ago.

12 days ago, I think, in https://github.com/zulip/zulip-mobile/pull/3822.

**Comment by gnprice** [comment]
Hmm, yeah, thanks for the correction! I guess I was misled by too-hastily reading #3387, which is a year old and asks for the loading indicator (but doesn't actually say whether the status quo was that we showed cached data, or prematurely-cleared data, or what -- just, we didn't indicate we were loading fresh data.)
