### ISSUE TITLE
Add local echo for starring a message.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#2852]
If a user is on a slow network or just geographically distant (i.e. on a different continent) from a server, we should optimistically update for starring a message.

For relevant discussion, see [#2843](https://github.com/zulip/zulip-mobile/pull/2843#discussion_r206269559) and [#2676](https://github.com/zulip/zulip-mobile/issues/2676#issuecomment-408969257).

@gnprice

**Comment by jackrzhang** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
(It turns out that until recently, this was the *only* way the webapp had to display that you'd just starred a message -- there was a bug (zulip/zulip#10111) so that when it got an `update_message_flags` event for starring a message, it would drop it! But that was fine, because by then it had long since rendered the change with a local echo / optimistic update.)

**Comment by chrisbobbe** [comment]
Looks like work was begun in https://github.com/zulip/zulip-mobile/pull/2843 and finished in https://github.com/zulip/zulip-mobile/pull/2922, so, closing this.  🎉
