### ISSUE TITLE
Message headers are visually too large/thick.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#287]
The message headers as shown in the screenshot below on the iPhone 5 Simulator are quite large and take up too much space on the screen. Perhaps the height should be closer to around 70% of what it is currently?

<img width="320" alt="screen shot 2017-02-06 at 12 49 48 pm" src="https://cloud.githubusercontent.com/assets/10321399/22665804/f9c1a9c4-ec6a-11e6-8c0f-0a0623eed028.png">

**Comment by borisyankov** [comment]
We need that size so they are 'tappable'.
Generally the suggested minimal size on iOS is 44px x 44px, and these headers are actually narrower, so I don't think we can go more narrow.

**Comment by timabbott** [comment]
I think part of what's going on is the overall font size issue from #288 is present in this screenshot; everything is too big there...

**Comment by borisyankov** [comment]
There is no bug in the screenshot. You are looking at it on a laptop/pc likely. Or at least a big phone.
iPhone 5 is a tiny screen that can fit much less stuff than a 5" phone.
The header is 70px which considering this is 2x retina is equal to 35px.
This is less than the recommended 44px, but I think it is still tappable because it is wide.
