### ISSUE TITLE
Uncaught SyntaxError: Unexpected Identifier in 15.0.92

### ISSUE THREAD

**Issue by jpellman** [zulip/zulip-mobile#2894]
One of our users seemingly randomly gets the following error while logged into a realm on our self-hosted Zulip server:

![zulip_uncaught_syntaxerror](https://user-images.githubusercontent.com/5000591/44233612-59d0cd00-a172-11e8-85df-4df9132ae63b.jpg)

Aforementioned user is using v.15.0.92 of the Zulip mobile app on a Galaxy S7 running Android 8.0- any ideas what might be causing this?

**Comment by gnprice** [comment]
Thanks for the detailed report!

This looks like a case of #2505. The issue was fixed in 787c4a53b (from #2854) a couple of weeks ago in master; the fix is in version 16.2.96, which went to beta this week and will go out to everyone next week if all is well.

(Meanwhile, if you're interested in giving early feedback on beta versions, we'd be [glad to have you join](https://github.com/zulip/zulip-mobile/#using-the-beta)!)
