### ISSUE TITLE
Emoji Reaction Picker: List commonly used emoji

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#2927]
I feel like the emoji reaction picker should include a compact row of the 10 most frequently used emoji by the user ( this could be local but ideally would be across all zulip clients ).

For the most part I don't see users using more than say 5-10 reactions on a regular basis and having to type out names or scrolling a list can be tedious/frustrating. 

For reference this feature can be seen on the iOS iMessage keyboard.

**Comment by agzuniverse** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
See also #4567, and #4565 for making common emoji available in the action sheet before you even get to the picker.

**Comment by gnprice** [comment]
We did this at some point a while ago -- the list of emoji in the reaction picker starts with :heart:, :tada:, and the other "popular emoji" that are the same ones at the top of web's emoji picker.

A nice compact row would be an improvement; #4567 tracks that.

It's a hardcoded list, rather than based on the user's actual usage patterns. This matches Zulip web, and https://github.com/zulip/zulip/issues/21841 is for doing something based on actual usage. When that issue makes progress, we'll follow along in mobile then.
