### ISSUE TITLE
@-ing in messages makes them get stuck

### ISSUE THREAD

**Issue by omnibs** [zulip/zulip-mobile#2999]
#### What

Typing `@` on a message brifly brings up a names autocomplete, which fades out in a few milliseconds, and after that I can't submit a message.

#### Hardware / software

Galaxy Note 9 on Zulip 17.1.98

#### Repro video

https://drive.google.com/file/d/1daRA7DQ-0ZrtulYRoc0BX4Ex_sFcaU--/view

Let me know if yall want any more info to help figuring this out

**Comment by jainkuniya** [comment]
This issue is same as #2791 which got fixed by 0baca8f, and will be released out next week.

Thanks @omnibs for the report!

Now this issue can be closed, 
cc @gnprice @borisyankov

**Comment by gnprice** [comment]
Thanks for the report! This sounds like another aspect of the same issue as #2987 , which was fixed in 18.0.99.

(Also #2791 as @jainkuniya points out, but I think the brief popup is not the most annoying symptom here :slightly_smiling_face: )

Closing; please reopen if you find it isn't fixed for you by 18.0.99.
