### ISSUE TITLE
Build version of anchor-based scroll view for Android

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#30]
The iOS app contains a modified version of RCTScrollView that allows adding elements to both the top and bottom while maintaining scroll position.

We need a version of this for Android.

**Comment by borisyankov** [comment]
We should consider ListView, which is strongly recommended over ScrollView for rendering larger amounts of data. Maybe it will also be easier to implement the anchoring so need for custom version for Android?

**Comment by neerajwahi** [comment]
@borisyankov I tried using ListView initially and it was a bit tricky to get it to support infinite scrolling in both directions (by adding `onStartReached` in addition to `onEndReached`) , so I decided to start with ScrollView. Ultimately we will want to optimize it (perhaps by paging in views like ListView).

I also tried maintaining scroll position without implementing it in a native component. When new content is added from the top of the feed, we need to change the contentOffset of the underlying scroll view. That's difficult to do in a performant way on the JS thread because we only receive scroll updates occasionally (by default every 50ms and at best every ~16ms), so it ends up causing the scroll position to jump.

**Comment by kmdupr33** [comment]
I think we can get the infinite scrolling in both directions on Android by just implementing a native module that bridges to Android's `RecyclerView.` 

That's the approach I'm going to try out. Hope that's ok. 

I think this approach will likely be simpler/neater than copy-pasting the android equivalent of `RCTScrollView`, and, as @borisyankov suggested, it will scale better than a scroll view for large amounts of data.

**Comment by neerajwahi** [comment]
@kmdupr33 It looks like a version of that may exist in the React Native codebase that you may want to check out: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/recyclerview/RecyclerViewBackedScrollView.java

For iOS, the issue is that I needed to modify the bridge (`RCTScrollView`) for our use case (such as changing `contentOffset` when new content is added to the beginning of the stream).

I could have created a new native module, but that would have meant duplicating a lot of work to make some minor changes.

Some of the options included:
- Copy and pasting `RCTScrollView` to `RCTAnchoredScrollView` and making the changes
- Rewriting `RCTAnchoredScrollView` from scratch
- Forking React Native, modifying `RCTScrollView`, and making this project use the forked version
- Merging required changes to `RCTScrollView` upstream (to the React Native repo)

**Comment by kmdupr33** [comment]
Thanks for pointing that out. I'll check it out. 

If we bridge to an Android `RecyclerView,` we actually won't need to worry about the content offset. The `RecyclerView` gives us the ability to preserve the user's current scroll position even when new items are added to the list for free.

**Comment by neerajwahi** [comment]
Even if they are added at the beginning of the list?

The difference I think is that you're planning on writing a brand new bridge, while for iOS I copy-pasted the existing bridge and made changes to it (because `RCTScrollView` actually has a lot of logic in it that it didn't make sense to rewrite).

**Comment by kmdupr33** [comment]
Yes sir. Even if they're added at the beginning of the list.

I suspect that there won't be a lot of logic that I need to reimplement for this. I think the native bridge will be less than 200 LOC. Is it okay if I try it out and then consider the copy-paste option if it turns out to be more complicated?

**Comment by neerajwahi** [comment]
Sure, but maybe check out `RecyclerViewBackedScrollView` first? No point in doing all that work if you don't need to :)

**Comment by kmdupr33** [comment]
Indeed. Doing extra work is almost always not fun :) Unfortunately, it doesn't look like RecyclerViewBackedScrollView is going to give us the notifications when the user reaches the beginning or end of a list. Regardless, it'll definitely be helpful as I try to work on this, so thanks again for pointing it out.

**Comment by neerajwahi** [comment]
Just curious, why won't it give us the notifications? The way this works in iOS is that we get an onScroll notification at some configurable interval. In that JS callback we determine the user's scroll position and trigger a callback (either `onStartReached` or `onEndReached`) if it passes some threshold in either scroll direction.

See: https://github.com/zulip/zulip-mobile/blob/master/src/stream/InfiniteScrollView.js#L48

At first glance looks like the Android version also sends scroll notifications: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/recyclerview/RecyclerViewBackedScrollView.java#L343

**Comment by kmdupr33** [comment]
I was actually just looking at the line. Maybe the right play here is to subclass `RecyclerViewBackedScrollView.` Let me look a little closer at this class here to see what's going on.

**Comment by kmdupr33** [comment]
I've tried using the `RecyclerViewBackedScrollView,` along with its `ViewManager` and I'm getting some odd behavior: first, the `RecyclerViewBackedScrollView` isn't sized correctly (it only takes up 3/4ths the width of the screen) and second, the `RecyclerViewBackedScrollView` doesn't appear to be getting touch events, which, in turn, causes the scroll view to fail to scroll.

I'm going to spend some time getting to the bottom of this. Just wanted to let you know where I was at.

**Comment by kmdupr33** [comment]
@neerajwahi I've figured out how to get the scrollview to render at the correct size and I've fixed the scrolling issue. However, there's a problem with how the child views are getting rendered within the scroll view. I suspect that I'm going to need to copy paste some code from the RN library in order to fix this, assuming we want to continue on this path.

Alternatively, I could just implement a proper RecyclerView by using the elements of the `stream` array as the data we want displayed in a `RecyclerView`. The later option seems cleaner and we'll have the added bonus of being able to recycle views in the list, a benefit that isn't likely to be trivial even given the different sizes of the messages in the stream.  

If its okay with you, I'd like to explore this alternative route.

**Comment by neerajwahi** [comment]
@kmdupr33 we may want to fork RN anyway and pull down the forked version (and eventually merge any changes we make upstream) since that's cleaner than copy-pasting `RCTScrollView` like we currently do. Mostly thinking aloud to myself here.

Is the scroll view you got to render at the correct size not backed by `RecyclerView`?

I'm not at all familiar with how RN is implemented for Android so I defer to you on the most fruitful route for this :)

**Comment by kmdupr33** [comment]
Awesome. Forking RN seems like a good idea. Seems like a lot of people wind up doing that for reasons similar to ours.

The scrollview that I got to render is backed by a `RecyclerView.` In fact, there's one (small) piece of it that is copy-pasted from the `RecyclerViewBackedScrollView` you pointed me to. However, there's a large piece of code that's responsible for laying out the items within a RecyclerView that I suspect would have to be copied in order to get things working properly.

On a bit of a separate note, it might actually be good to implement a proper `UITableView` on the iOS side of the app as well. I'm assuming we haven't actually tested the app on a physical device, and we might find that once we do that -- especially if we do that on a lower-end device we may want to support -- we don't like the performance of the scroll view. [This article](https://medium.com/@talkol/recycling-rows-for-high-performance-react-native-list-views-628fd0363861#.k2hsgg3s5) does a good job of explaining why we will probably get better performance out of a RN component that's backed by a native view that actually recycles its views and it also sketches out some of the implementation.

I'm not trying to step on your toes. I just want to make sure that we want to stick with the iOS implementation we've got. If it turns out we want something like `UITableView` on the iOS side, then maybe I don't have worry so much about an implementation on Android that will have 0 impact on the iOS side.

**Comment by neerajwahi** [comment]
The performance (of the native thread at least) on a physical iPhone is quite good. We're probably going to want to implement something similar to `ListView` where we page rows in and out to reduce memory usage.

I'm not convinced that view recycling is the right approach. In the article you mention, our use case falls under "high variation between rows and a smaller data-source" whereas view recycling works well when each row has the same height and very similar layout.

Why would the Android implementation have an impact on the iOS side?

**Comment by kmdupr33** [comment]
Hmm...That's good that we've tested on a physical device, but I am curious whether we've tested on the lowest-end devices we want to support. 

Maybe the stream messages will have a higher variation than what I've seen, but I don't think that differing amounts of text within messages is a big enough difference to neutralize the performance benefits of recycling views. [Facebook found that traditional recycling wasn't beneficial for their newsfeed on Android](https://code.facebook.com/posts/879498888759525/fast-rendering-news-feed-on-android/), but the various items within that newsfeed were *very* different. 

RE how our use case falls into the categories in the article: I don't think we fall squarely into one or the other. Instead, I actually think we're in the similar rows, small data-source category, and in that case, I think recycling makes sense.

Maybe we could run a small experiment to see what the right approach is. Maybe its not worth the effort. I'm open to whatever you think is the best call.

The Android implementation doesn't have to have an impact on the iOS side, but its going to take a little extra work to make sure that it doesn't have that impact. If we're going to move to more a `ListView` approach anyway, then I figured I'd try to avoid that extra work. The API for `ListView` is about specifying a datasource rather than adding child views, which is how we're handing things now.

**Comment by borisyankov** [comment]
I have a hunch that a `ListView` will be much better for a _long_ list of _text_.

BTW, have you had a look at https://github.com/FaridSafi/react-native-gifted-chat/

**Comment by neerajwahi** [comment]
It might be worth exploring view recycling on iOS in the future but for now I think there are a lot of other tasks that are higher priority.

I've been testing on an iPhone 6 (which is now 2 generations old) and the performance has been excellent. The bottleneck is the JS thread. The main benefit of recycling will be reducing memory pressure, but we might be able to get those benefits from using a `ListView` style implementation that pages views in and out as the user scrolls.

**Comment by borisyankov** [comment]
iPhone 6 is way too high class device to consider it a 'minimum' one.
Apple officially support iPhone 4S which still updates to iOS 10.

According to this:
https://fiksu.com/resources/ios_trackers/
You don't get to the 90% of usage if you don't include iPhone 5s and 5.

And keep in mind Android is much more variable in performance characteristics.

People might be forgiving of a super-modern 3d game that works a bit slow, but maybe not of a chat app.

**Comment by SudoPlz** [comment]
What did you guys end up doing after all?

**Comment by borisyankov** [comment]
@SudoPlz  We are still using ScrollView, but are strongly considering two alternatives as superior: FlatList/SectionList or a WebView.

We have prototypes for both here:
https://github.com/zulip/zulip-mobile/blob/master/src/message/MessageListFlatList.js
https://github.com/zulip/zulip-mobile/blob/master/src/message/MessageListWeb.js

**Comment by SudoPlz** [comment]
Hmm interesting, and why would you consider FlatList as a superior solution than a list that recycles its children, such as a https://github.com/wix/BindingListView
