### ISSUE TITLE
Sent messages sometimes don't scroll in view

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3011]
Sometimes messages send by the user don't scroll into view.

This is possibly related to the 'messages disappear when sent for a moment'.

**Comment by gnprice** [comment]
> This is possibly related to the 'messages disappear when sent for a moment'.

FTR and for the sake of cross-reference, that's #2413 (fixed) and later #3117.

The reported symptom also sounds related to #2483, which was fixed in 3c14c7d57; and to #3410.

In any case: WFM now, this report doesn't have any specifics that would help reproduce, and this issue has been idle for some time, so closing. If someone sees this symptom in the future, we can file a new issue and debug that report.
