### ISSUE TITLE
Wrap around swipe gesture

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3023]
I think the fact that the swipe gesture stops when you reach the first screen causes me to accidentally click on of the streams listed there. Instead the gesture should wrap around so swiping at either end takes you to the first / last screen.

**Comment by borisyankov** [comment]
I am not sure about that...
This swiping gesture might even go away completely when we upgrade to React Navigation 2.

I tested several apps - YouTube and Twitter do not swipe at all between the bottom navigation icons, but do swipe between tabs, and don't swipe around.

Facebook does swipe between screens but when you are at the end you are there and don't go to the first one.

**Comment by armaanahluwalia** [comment]
I find the swiping gestures really nice once they are discovered. Saves a lot of effort during navigation. I think the main problem that needs to be solved here is the accidental click of the stream icons. I'm not sure of a good solution but its happened to me more than 10 times during the course of my use which is why I bring it up.

**Comment by gnprice** [comment]
(It's not explicit above, but I'm pretty sure this is about swiping between the "main tabs" at the bottom of the screen in the app's home view.)

This is now moot because we no longer have a swipe gesture between those -- quite possibly because of the upgrade Boris mentioned above. In general, [the standard convention seems to be](https://chat.zulip.org/#narrow/stream/48-mobile/topic/swipe.20on.20streams.20screen/near/805191):
* with top tabs, swiping navigates between them (it doesn't for us right now, but that's #3997), but
* with bottom tabs, swiping doesn't interact with them at all,

so by not offering swipe between those tabs, we're following convention.
