### ISSUE TITLE
Autocorrect on iOS Compose Input

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3053]
Autocorrect does not behave as expected on the iOS compose message input. Basically this is very easy to reproduce. See the video for a comparison of behavior on iMessage and Zulip.

Ideally Zulip would be able to autocorrect in the middle of a sentence like iMessage does.

https://streamable.com/8w70j
https://streamable.com/glcz7

If you notice at the end of the second video the cursor jumps to the end. That happened when I tried to type a character it wasn't me moving the cursor manually. It seems to lose its place ( this is not as easily repro-able as the autocorrect problem and may be related to #3052 )

Seen on on iOS 18.0.99

**Comment by gnprice** [comment]
Thanks for the report and the clear screencaps!

I suspect this is the same underlying issue as #2434 , though I don't understand this subsystem well enough to be confident that's the case.

That issue should be fixed in RN v0.57. Would you try the tip of #2789 (which upgrades us to that version) and see if this issue still reproduces there? (And if it does, also try reproducing #2434 to confirm I haven't misunderstood something there?) If we're lucky, that does fix it.
