### ISSUE TITLE
debug: Update highlighted unread messages along with state.flags.read.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3062]
This was discussed with @gnprice.

<p align="center">
<img alt="debug-highlighted-unreads-not-updating" src="https://user-images.githubusercontent.com/12771126/47152236-f60d7200-d290-11e8-94e6-bb72f92e9b1c.gif" />
</p>

In the demonstration above, `state.session.debug` is:
```js
{
  doNotMarkMessagesAsRead: false,
  highlightUnreadMessages: true
}
```

I'd like to claim this.

**Comment by jackrzhang** [comment]
The current bit of code that's preventing messages in the webview from updating as they are marked as read is in `webViewHandleUpdates.js`:

https://github.com/zulip/zulip-mobile/blob/36ee9448ec47d9890346180b16cca164671643e6/src/webview/webViewHandleUpdates.js#L71

I have to further investigate; would you have any suggestions?

**Comment by borisyankov** [comment]
Yeah, I do. Because this solution will not be performant, and might not even work - we currently refresh the content and preserve the position but not sure if it will be possible to preserve the position while scrolling and keep it looking ok.

The reason why I didn't do it yet, is that it is a bit involved for a feature that is not key or even used by the wide audience.

If I was to implement it I would:
 * add a new event for 'updating unread messages'
 * would send this event and add a handler in the js.js file
 * when handled will either set a new class on the message nodes, or alternatively (should be tested for performance) create a new CSS rule targeting a concrete node

So either: (pseudo HTML)
`<div>` => `<div class="read">`
or
`<div id="msg123">` => `#msg123 { background: 'red' }`

**Comment by gnprice** [comment]
This is accomplished now by #3125 .
