### ISSUE TITLE
Improve CompatibilityScreen text.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3073]
Two things that @gnprice and I discussed in person:
- Refer to 'Play Store' on Android and 'App Store' on iOS.
- Include links to the latest versions.

(@zulipbot claim)

**Comment by borisyankov** [comment]
I'd say an important thing to test first is if this component even behaves OK still :)
I don't think we've tested it recently (or ever since its creation)

**Comment by borisyankov** [comment]
After that, we definitely want to update the URLs 👍

**Comment by gnprice** [comment]
Bumped the priority because completing #2634 will require us to activate this mechanism for old Android clients -- and before we do that we want to complete this change, and get a release with it out to the Play Store, so that when someday we activate this mechanism for a second time the experience is nicer. :)

**Comment by gnprice** [comment]
Now complete, with #3158 . Thanks @jackrzhang !
