### ISSUE TITLE
Rendering of `MainNavBar` is delayed on Android 9

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3089]
When navigating to a narrow, when rendering `ChatScreen` the `ComposeBox` component renders as expected but the `MainNavBar` does not render immediately but takes a bit.

This is not a critical issue, as the component renders correctly.
Still, it is good to figure out the issue which might also be present elsewhere.

**Comment by jainkuniya** [comment]
Here is more info on this issue:
I tested on few devices:
* On Android 9 emulator (Android Pixel XL), can't reproduce.
* But can reproduce on Android 9 running on One Plus 6.
* Can reproduce on on MI phones (not completely sure, but it was Android 8 or lower)

This issue is very critical and can also lead/extends to completely not rendering of MessageList, like:
![image](https://user-images.githubusercontent.com/18511177/50235980-3c8d6300-03df-11e9-8452-15ce9991a102.png)

(https://chat.zulip.org/#narrow/stream/48-mobile/topic/notifications)

I started debugging on this and here is what I found.
* If is remove `WebView`, then this got fixed. So this is related to `MessageList`.
* `MessageList` is encapsulated with `redux`, `actionSheet`, `withGetText`, I tried removing each at a time and tried to reproduce. I was still facing this issue, even after removing it. So not related to `redux` or `action sheet` or anything similar.
* Then I tried with `buildToolVersion` as `28.*`, nothing worked.
* Also tried with `compileSDKVersion` as `28.*`, same result,  nothing worked.
* I tried with same as what is present in RN repo (https://github.com/facebook/react-native/blob/9d00d4d5bb0f312b7d907e2fc4005a73301dee9f/ReactAndroid/build.gradle#L271),  same result,  nothing worked.
* Then I found few patterns to reproduce it:
  * If you doNarrow to those narrows, for which there are no messages (first time narrow/we haven't cached any messages yet/dummy messages are show for a small fraction of time) then this issue is never reproducible. Then for subsequent narrow to same narrow, I can reproduce this issue.
  * Many time nav bar is visible with a delay after narrowing. And sometimes, it only become visible after scrolling a message list. So if list height is less than screen, i.e message list is not scrollable it is not possible to make nav bar visible.
  * Even though nav bar is not visible, it's functionality works. That it, on tapping on back icon or on info buttons positions, corresponding nav actions takes place.
 
Then, one thing was troubling me: why compose box is rendered/displayed immediately. What is the problem with navBar???? It is also a normal component like composeBox. Then I changes the position of navBar from top of MessageList to bottom of MessageList.

like this (in `ChatScreen`):
```
<Chat narrow={narrow} />
<ChatNavBar narrow={narrow} />
```

and guess what, navBar is displayed immediately after narrowing, surprising yes!!

So the real issue is like:
When `webView` renders messages/calculate is size (I thinks many time recalculation takes place internally), it do something (wrongly) which affects the display property of component which is present vertically above to it.

Then I created new fresh RN (`0.57.8`) project with `compileSdkVersion = 27`. And guess what I found the same issue.

Playground: https://github.com/jainkuniya/rn-test-webview-on-andorid/blob/master/App.js

Swap the position of webView and text component and find that, when text is at top, there is delay in rendering/displaying text component. Same issue as ours.
Now replace 
```
source={{ html: 'https://github.com/facebook/react-native' }}
```
with
```
source={{ uri: 'https://github.com/facebook/react-native' }}
```

Again play around it with.

So when webView is not scrollable, many times text component is not even displayed.

Now finally I got a solution, which is using `styles`. 
Comment out this line
https://github.com/jainkuniya/rn-test-webview-on-andorid/blob/master/App.js#L31
and see the magic.
Just we are rendering components in reverse order 😝 and it got fixed.

Now next after applying same concept in `ChatScreen`
```
 <ActionSheetProvider>
        <View style={styles.screen}>
          <ZulipStatusBar narrow={narrow} />
          <View style={[styles.flexed, styles.flexDirectionColumnReversed]}>
            <Chat narrow={narrow} />
            <OfflineNotice />
            <ChatNavBar narrow={narrow} />
          </View>
        </View>
      </ActionSheetProvider>
```
Now UnreadNotice starts behaving in the same way like nav bar was behaving before.
Because in `Chat` `UnreadNotice` is above of `MessageList`
```
 <View style={styles.flexed}>
          <UnreadNotice narrow={narrow} />
          <NoMessages narrow={narrow} />
          <MessageList narrow={narrow} />
          <ComposeBox narrow={narrow} />
</View>
```
So to fix it, replace it with
```
 <View style={styles.flexed}>
          <View style={[styles.flexed, styles.flexDirectionColumnReversed]}>
                 <MessageList narrow={narrow} />
                 <NoMessages narrow={narrow} />
                 <UnreadNotice narrow={narrow} />
          </View>
          <ComposeBox narrow={narrow} />
</View>
```

And ya, this issues get's fixed.

(This is a hack.)

@zulipbot claim

**Comment by gnprice** [comment]
One next step that would be quite useful is to go looking in the RN tracker for a report of this issue, and if there is one then link to it here... and if there isn't, then to report it. That repro in a fresh RN app will be very helpful for a bug report.

If there is already a report of an issue that looks like this, then if there's any of this information that isn't already known in the issue thread, it'd also be helpful to post a comment with the additional information. The repro is again especially likely to be helpful.
