### ISSUE TITLE
Make sure the app doesn't break with the new delivery_email field

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#3196]
As part of adding (hacky) support for not sharing users' real email addresses with everyone in the organization, we've added a new field, `delivery_email` (which in most configurations just equals the `email`, but ).  The basic model is that the `email` field will continue to be a human-readable identifier for a user, and for most client purposes, they can just ignore the `delivery_email` field and things will transparently work; users generally will only have access to their own `delivery_email`.

I expect that this hacky approach (where the `email` field may not be the user's actual email address) is going to be how things work for a long time, because the `email` field name is used in so many places that migrating away from and then renaming it likely won't happen for a year or more from when we start doing so.

It's likely that the mobile apps don't need any work; for the webapp frontend, we needed to do just these two commits: https://github.com/zulip/zulip/commit/67f0b1bbca1f57773710f3f51534289148ec22ed and https://github.com/zulip/zulip/commit/bc74abae41e3388ba973fd94d83bd5b7c768c007 (for the "my account" settings page).  (Well, we'll possibly need to add a few more changes for the administration UI, but the mobile app doesn't have one).

But we should do some testing of the mobile app for this to make sure something reasonable happens in this configuration (which is available in the development environment now thanks to the commit above); I suppose if there's a place where we display "your email address", that should be changed to use `.delivery_email`.  No changes should be needed for the auth/login stage; for that, everything uses the value of `delivery_email` under the old name `email`.  

(We'd like to turn this feature on for chat.zulip.org within the next few weeks assuming no blockers from e.g. mobile)

**Comment by gnprice** [comment]
One other aspect of this worth making explicit: the transition from the existing configuration to the new one. When an organization makes this transition, the `email` of every user will change. Because we (mis)use the user's email as an identifier, this would be pretty confusing for the app.

Our planned solution is to have the server expire all event queues for the organization (for mobile clients... maybe all non-webapp clients? Tim told me last week he believes the webapp will have no trouble with the transition.) That should cause the app to reload everything, so there's no confusion.

This is an important area to test, though -- there's a lot of kinds of data involved, and there may be cases where we try to still use pre-transition data combined with post-transition data, which will make things confused.

**Comment by gnprice** [comment]
Update: This setting is available for org admins on zulipchat.com to choose, though marked "beta":
https://zulipchat.com/help/restrict-visibility-of-email-addresses
Not sure of when it was deployed, or its status in server releases.

We just got a [very helpful, detailed report](https://chat.zulip.org/#narrow/stream/48-mobile/topic/data.20not.20updating/near/764197) from a puzzled org admin of a set of symptoms that turned out to be triggered by this setting. They found that with the setting enabled (i.e. with email addresses visible only to admins), all users in the organization saw the following symptoms on mobile:
> * Private messages disappearing after sending, I think this is noted in issue #3117
> * Incoming messages will create notifications but not appear in app until the app is closed and reopened
> * Unread message counts don't clear until the app is closed
> * Sent or received messages in any private message feed create unread counts in all pm feeds
> * User image does not appear as icon for far right tab or in associated screen

On the last point, the avatar specifically is blank.

One further symptom found in discussion:
* on the PM conversations screen, each conversation shows the user's own name, in addition to whoever else is in it.

I believe the missing avatars, and the user's own name showing up on each PM conversation, are probably because we try to use the user's email address from something like `auth.email` to look up their avatar, or to filter them out of the list of users in a PM conversation, respectively.

Not sure about the unread counts in all PM feeds. That sounds like it might be the same bug, compounded with some additional bug in a reducer.

The first three symptoms all sound like we're failing to get events from the server. Not sure why this setting would lead to that failure mode, but apparently it does.

**Comment by timabbott** [comment]
This has been available for beta-testing by a few orgs (I think because this one asked for it) for a period of a couple weeks.  It is not in any server release.  We should definitely consider making this work properly in the mobile app a priority issue, because we have been getting regular requests for this feature and will definitely want to include it in the next release.

IIRC there is an event sent when `delivery_email` changes when an organization has this setting turned on, so if the issue is just in handling that, we should be able to have the app do a full refresh in that case if that addresses the issue; it should be a quite rare change.

**Comment by gnprice** [comment]
That's helpful context, thanks.

> IIRC there is an event sent when `delivery_email` changes when an organization has this setting turned on, so if the issue is just in handling that, we should be able to have the app do a full refresh in that case if that addresses the issue; it should be a quite rare change.

Cool. We'll want to do that, but unfortunately this will be more complex to implement than just the transition -- major steps include
* Really going through and finding all the places that we identify the current user by their email. These will be tricky to fully track down.
* Fixing those. This probably means building more data structures to use IDs where we've been using emails.

**Comment by gnprice** [comment]
Just pushed (as bd6c155b6..2407f3f9c) a series of fixes to various small places where we were using the current user's real email (the one used in authentication) where what we needed was their identifier-email. Each of these was a spot that would break when the hidden-emails setting is enabled. Now they all get the identifier-email through a common codepath, `getOwnEmail`.

Still in a draft branch is the change to make `getOwnEmail` actually consult the `email` from `/register`, rather than return the real email from authentication. Until that change, the above fixes are almost all no-ops. As of Friday, that change provoked some bugs at the moment of switching accounts, or logging into an account; still working through those. Hopefully the changes I just pushed will clear out some of the underbrush for debugging those other issues.

I also observed today a puzzling issue where, shortly after enabling hidden-emails on an org, I believe the server was still returning unobfuscated real emails in the `display_recipient` properties of a `/messages` response. Details [in chat](https://chat.zulip.org/#narrow/stream/3-backend/topic/hidden.20emails). In the discussion there, @timabbott suggested it might be a server-side caching issue; more debugging required.

**Comment by gnprice** [comment]
Just pushed 139b7d1ac..c5b93700e, and I believe this is now fixed! There may be yet-unknown bugs where we still use `auth.email` aka the `delivery_email` where we want the identifer-`email`, or vice versa; we'll file and fix those separately as we see them.

Behavior is still not good at transition time, in the period shortly after turning the setting on (or off) for an org. There are two pieces to this:

* The server-side caching issue mentioned above. I did some further debugging yesterday, described in the linked chat thread, and I think we have a diagnosis and a couple of ways to fix it.

  This is a bug in the data the server is returning -- a hole in the intended privacy properties of this setting, though fortunately a temporary one for I think up to 24 hours after the setting is enabled -- but its effect is especially visible on mobile because we use emails to identify users in lots of places, where the webapp has I think gotten farther in migrating away from that.

* Updating all the client-side data that identifies users by email address. This is actually a lot like (our current diagnosis of) that server-side caching issue, in that a root cause is that user emails (and avatar_urls, etc.) are denormalized into a variety of spots scattered across our data structures, so that it's not trivial to track them all down and update them.

  The solution we've talked about before, which I think is reasonable and is the only near-term-feasible one, is to have the server simply expire all event queues for the org when this setting is changed, so that we reload all data from the server.

  (That still leaves a bug where we don't properly handle users changing their email address -- either the self-user, or any other user. This is analogous to #3397 and is part of the umbrella issue #3408; the updates come in `realm_user` events with opcode `update`. But that's an uncommon occurrence, it isn't easy to fix given the denormalization, and so I don't think it's a priority compared to our other open issues.)

**Comment by timabbott** [comment]
@gnprice just a note -- the plan I'd imagined was for the client to destroy its event queue when receiving an event of the email_address_policy changing; the webapp I believe should be able to (possibly with small changes to address bugs) handle such transitions without a reload because of how it already handles email address changes correctly.  

(We have a handful of events that on the webapp trigger a reload for similar reasons)
