### ISSUE TITLE
Download >500KB Data Each Time the App Starts

### ISSUE THREAD

**Issue by fzyzcjy** [zulip/zulip-mobile#3245]
Hi! Thank you for this wonderful open source project! However, when I am testing it today, I find that it needs to download >500 KB of data each time I start the app. It seems that it is not a perfect experience for the users. Therefore, I think it may be better to fix it. :)

**Comment by borisyankov** [comment]
That is a good point :)
We do a full data refresh at start, including user data. If you have been testing the app on https://chat.zulip.org you might have experienced the high data usage because we have a lot of users.

**Comment by chrisbobbe** [comment]
Thanks for the report, @fzyzcjy!

Yes, on realms like chat.zulip.org there can be a very large amount of user data downloaded when you open the app, and when you return to the app after 10 minutes of inactivity. This is being tracked in https://github.com/zulip/zulip-mobile/issues/1804, and I’ve pinged Tim and Greg there to see if there’s been any activity I’m not aware of.

Recent private messages are also fetched, and (if returning after inactivity) messages from a narrow that you were viewing before. Currently, messages can contain very large images, and there are some challenges to caching and thumbnailing that are being tracked in https://github.com/zulip/zulip-mobile/issues/3853 and https://github.com/zulip/zulip/issues/13088. Large images may be consuming even more of your data than the initial user fetch, since they can arrive in messages at any time, and it would certainly be more unpredictable, making it hard to judge whether to choose to use a wifi connection over cellular data.

Just to help focus our progress on these important issues affecting data usage, I’m closing this issue in favor of those that I’ve mentioned. Please let me know if you think I have closed this in error. 🙂

**Comment by fzyzcjy** [comment]
@chrisbobbe Add oil!
