### ISSUE TITLE
Android: tapping a message notification doesn't open the relevance message

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-mobile#3251]
When I tap on a message notification, Zulip opens but doesn't necessarily take me to the right server or the right message.

**Comment by timabbott** [comment]
Does it take you to a blank white screen?  There's a bug in the latest release that results in that failure mode.

**Comment by jmandel** [comment]
Not a blanket screen! Could be just the last channel I was in (e.g., a Fchat.fhir.org  publicchannel, when the message notification is for a private message at chat.zulip.org)

**Comment by gnprice** [comment]
Hi @jmandel ! Thanks for this report.

In the case where you get a notification that's in a different realm/organization from the one you were last using, this is a known issue (and unfortunately will take some work to fix): #2295 .

If you're sometimes seeing this when that isn't the case, I'd love to see a report with further details on that. I'll close this one because it sounds like it's mainly the same as #2295.
