### ISSUE TITLE
Message does not load if Internet is back.

### ISSUE THREAD

**Issue by daschuer** [zulip/zulip-mobile#3281]
If you open a message during weak internet connection, grey bars are displayed instead of the real meassage.
This state lasts forever even if Internet connection is back or change to a WiFi.

It also happens to me that the message was removed from the new message list after turning back. I wanted to go back and forth to trigger reload. I cannot confirm this now though. It is Zulip 21.2.106 on Android.

**Comment by borisyankov** [comment]
Thanks for opening an issue for that.
This has always been the behavior, but recently we started adding retry functionality in select places.
I guess this is a great next place to do so.

**Comment by gnprice** [comment]
The fix in #3288 broke tests :face_with_head_bandage: , so I've just reverted it.

I think the actual code change in #3288 is fine -- it's the tests that are at fault. See abc781457 (shown in this thread, just above) for details.

So the next step would be to pick up that change that was #3288, and go on to fix the tests so we can merge a fixed version.

**Comment by gnprice** [comment]
On reconsideration, I think an automatic retry would not be a good solution here. A major reason for that is that when a message fetch fails, there may well be something wrong so that retrying would just fail again and again.

Instead, when the fetch fails, we should show an error in place of the messages. That's #4186, just filed. With a retry button, you can have it retry if you think the issue may be transient (like because the network wasn't working and now it's back). And then if it keeps failing, you know something is wrong and that there isn't a need to sit there waiting for 30 more seconds to see if it's just slow.

Related discussion at #4165 -- some of the circumstances are different but I think the core point is the same.

**Comment by gnprice** [comment]
Closing in favor of #4186 .
