### ISSUE TITLE
Message list scroll position is often slightly messed up

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3301]
When showing/hiding `UnreadNotice` the message list scroll position is moved by the height of that panel.

As a result, when you narrow to a conversation with one or a few unread messages and at least a screenful of total messages (which is a very common scenario when staying caught up in a busy org), what you typically see is the screen jumps a couple of times, and then settles scrolled slightly too far up, with the last message only partly visible. This is annoying and looks pretty broken.

[summary expanded by @gnprice]

**Comment by jainkuniya** [comment]
#3027 is also in somewhat similar catalog.

**Comment by borisyankov** [comment]
Relevant here is that the Keyboard-avoidance is set differently on Android and iOS.
On Android we do use:
`android:windowSoftInputMode="adjustResize"` in `AndroidManifest.xml`
While in iOS we use 
`behavior="padding"` on a `KeyboardAvoidingView`.

**Comment by gnprice** [comment]
I just bumped the priority of this and expanded the description; the effect feels pretty annoying, and we hear complaints about it.

**Comment by gnprice** [comment]
Further observations, from @timabbott (on his phone: Android, likely Android 9, likely either 25.2.116 or 25.3.117):

> we have a really annoying scrolling bug in mobile where closing the keyboard bounces me away from the end of the feed every time
> Hmm okay not every time, shoot
> But most of the time
> May be related to whether local echo is running when i hit back to close keyboard
> Hmm maybe not, but seems to happen 75% of the time when I close keyboard in this thread [i.e. a PM thread with me, where we were actively talking] with back button

**Comment by gnprice** [comment]
BTW see also #3457 "Narrow sometimes lands far in the past".

Probably a separate issue... but I've often found this issue thread when I was looking for that one, and vice versa.

**Comment by jainkuniya** [comment]
I did some debugging on [current master] (https://github.com/zulip/zulip-mobile/commit/bea1ee587b122c28e492b0e0ce31d93cc611aa01), and observed following issues:

- Our animation is smooth, first we are scaling down the size of unread notice and then making it hide by `display:none` see `AnimatedScaleComponent`. Ideally as soon as component scale down, animation component should start releasing space and shrink.

- As we suddenly hide `AnimatedScaleComponent` by setting `display:none` after animation completes, it triggers `resize` in `webview`. And we are handling this event only according to case keyboard pops in/out. That is when keyboard pops (webview size decreases) => scroll up, else scroll down (when keyboard hides, webview size increases). 
When unread notice disappears, webview size gets increased any by code it scrolls down.

So in #3892, I tried to differentiate resize events with the `difference`. It was kind of hack, i.e if difference is less than 100 then it is due to unread notice, else due to keyboard.

This `resize` event also gets triggered on initial paint, at this point difference is > 100.

**Comment by gnprice** [comment]
> * When unread notice disappears, webview size gets increased any by code it scrolls down.

Down, or up?

Even just focusing on the keyboard case for a moment, I think it should be scrolling up when it gets bigger: that's how it keeps the bottom of the viewport, i.e. the last message you're looking at, scrolled to the same place. If it's not doing that, then that's its own bug.

If it is doing that -- if it is making it so that the bottom of the viewport stays at the same spot showing the same message -- then that seems like a perfectly fine behavior for the unread banner coming and going just as much as for the keyboard coming and going.

But the observed behavior is that, somehow, it's not successfully preserving the position of the bottom of the viewport. Why is that? One thing I think we don't yet know the answer to is: what exactly is the step at which something's happening that's different from what we expect, and what's happening instead?

This is a question that can only be answered by observing, and logging details. Reading the code can be a useful source of guesses, but there's enough going on (especially with the choices the browser makes) that we'll need to see things empirically to know for sure. (Maybe you've already done some of this empirical study; I'm not sure from your comment, but in any case I'll be interested in seeing the details from it.) It may be productive to describe some of this debugging in a chat thread on a stream -- that can be a more natural place to post lots of details than a GitHub issue thread.

**Comment by jainkuniya** [comment]
> I think it should be scrolling up when it gets bigger:

ya, when keyboard gets in (webview becomes smaller), webview scrolls up.

and on the other hand: when keyboard hides (webiew becomes larger), webview scrolls down.

Similarly, when unread notice hides, (webiew becomes larger), webview scrolls down. Instead in this case, either we need to do nothing. 

I have tested this by logging/alert and found that when unread notice hides, `resize` is called and difference is -40 (on iPhone 5S), and if message list is scrollable then it scrolls by `-40` i.e scrolls down. 
```
window.scrollBy({ left: 0, top: difference });
```

This fits in the keyboard scenario, i.e when keyboard pops in, webview size decreases & it scrolls up and vice versa. But this doesn't fit unread notice case.

**Comment by jainkuniya** [comment]
I think, we should not rely on `resize` events for checking & acting when keyboards pops in/out. We can get this information from RN and then we can send events to weview. 
So that, we are nothing anything extra on `resize` events, which occurs in many cases: like when unread notice gets in/out, on initial render, when messages renders etc

**Comment by gnprice** [comment]
Hmm, it seems we still have some confusing details to sort out. Let's discuss in this [chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/scroll.20position/near/818739) -- I think that will be a better medium for this.

**Comment by gnprice** [comment]
Just sent #4043 with what appears to be the solution of this mystery.
