### ISSUE TITLE
Viewing uploaded files fails, or requires logging in again

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#3303]
Right now if I share a file (i.e. a document) and click on the link that's sent in the Android app it will open a webview asking me to log into the Zulip instance. This is pretty annoying to be honest as the expected behaviour here would be to offer me to download the file instead.

**Comment by drumilpatel2000** [comment]
@zulipbot  claim

**Comment by borisyankov** [comment]
I consider the original issue to be a **bug report** not a **feature request**

For documents (for example PDFs) that are not hosted on a zulip server, we do open the document in a Chrome Custom Tab / Safari View. This screen immediately displays the document. In addition, a menu would allow downloading the document.

This matches the behavior of several chat apps that I tested, including Slack (also several non-chat apps!)

So, we need to fix the auth issue, not add a direct download functionality, which already exists in the screen that shows the document.

**Comment by gnprice** [comment]
Thanks @borisyankov for the investigation! I agree with your conclusions.

Folding #3487 into this as a dupe -- you've determined it's the same underlying issue, with a difference in symptoms by platform:
> * on Android - after opening fails we go back to the message list
> * on iOS - we get a login screen

**Comment by gnprice** [comment]
> you've determined it's the same underlying issue, with a difference in symptoms by platform:
> 
> > * on Android - after opening fails we go back to the message list
> > * on iOS - we get a login screen

Hmm actually this doesn't quite fit the data -- the original report here on this thread was on Android, and described a login screen.

I still think these are the same issue so I'll dedupe them; we'll just keep in mind that we have a somewhat confusing set of reports.

**Comment by gnprice** [comment]
Current state:

* We believe all the reported symptoms are ultimately caused by trying to open an auth-requiring URL and not providing auth; similar to the cause of #3124 .
  * Background: normal auth in the mobile app is by including an `Authorization` header, i.e. by HTTP basic auth. We do this for all API requests made directly by our own code, but it's trickier when other libraries are making HTTP requests. Some we successfully teach to send that header; for others, we resort to sticking the user's API key in the query-part of the URL.

* Reported symptoms include:
  * on Android, a login screen (in the OP on this thread);
  * on Android, a "Cannot display PDF" toast (on #3487 -- my repro, and a similar report from a user)
  * on Android, it all working! (on #3487, report from a user; details unknown)
  * using chat.zulip.org (from Android), it all works fine (my repro, on #3487)
  * on iOS, a login screen (Boris comment on #3487)

* Possible related issues:
  * The setup is reminiscent of #2308, but the symptom is different. That one was reported on iOS. That symptom: a blank browser screen... but if the "Safari" icon there is followed, then it opens successfully.
  * #2115: download manager fails to download, causing exception.
  * again, #3124

**Comment by chrisbobbe** [comment]
We've got a way forward for this issue, but it requires backend work; see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/view.20uploaded.20files/near/819777).

**Comment by chrisbobbe** [comment]
(https://github.com/zulip/zulip-mobile/issues/2113 might be addressed during work on this, but it shouldn't block.)

**Comment by gnprice** [comment]
> We've got a way forward for this issue, but it requires backend work; see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/view.20uploaded.20files/near/819777).

And with zulip/zulip#14500, I think we now have the backend support we need! So the next step is for someone to prepare a PR to have the app start using this feature, with the fallback strategy Anders describes [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/view.20uploaded.20files/near/855412).

(Later when we have #4049, we can switch to using that instead of the fallback. But that'll be an easy change to make later, and shouldn't block doing this.)

**Comment by gnprice** [comment]
This bug is now fixed!

On Android, this means that (in master) visiting an uploaded file successfully downloads it, including when the server uses the S3 uploaded-file backend, as zulipchat.com does.

On iOS, that doesn't actually work yet -- it gets past this bug, but runs into another one. I've just filed #4136 for that bug.
