### ISSUE TITLE
Enhancing architecture docs

### ISSUE THREAD

**Issue by AB261** [zulip/zulip-mobile#3307]
Many of the folders in the /src directory are not mentioned in the architecture.md file such as lightbox. It would help beginners understand the structure more easily if this was done.

**Comment by AB261** [comment]
@zulipbot claim

**Comment by chrisbobbe** [comment]
Thanks @AB261 for reporting this, and I'm sorry it took so long to respond! As you said at https://github.com/zulip/zulip-mobile/pull/3371#issuecomment-576723345, you're too busy to keep working on this issue right now, which is very understandable because you went so long without receiving feedback.

So, I've closed that PR, and this issue is now open to someone who would like to get more familiar with the /src directory and help others to understand it too. 🙂 The doc in question is at https://github.com/zulip/zulip-mobile/blob/master/docs/architecture.md.

A good solution to this will be to write a brief but accurate description on each of the files in the /src directory, which has grown much larger since that part of the doc was last updated. _This will require digging into the directory and reading the code itself._ Also, please note that some of those directories (like redux-persist-migrate) are local copies of NPM packages that we've cloned to adapt to our own needs, so that should be clear in the descriptions, with links to the packages themselves, and the reason for the clone.

If something isn't clear after doing some investigation, please post about it here or on chat.zulip.org. And if something in that doc outside the /src section could be improved, feel free to do that in a separate commit.

**Comment by chrisbobbe** [comment]
I see that this hasn’t attracted much activity, which is fine — @gnprice mentioned today that the maintenance burden of documenting everything in the /src directory is quite large, considering each file should have its own code comments anyway, and I agree. So, I’m closing this. 🙂
