### ISSUE TITLE
Compose box obscured by keyboard on long message, in stream view

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3369]
When replying to a message in the stream view, if the message you’re typing is longer than a certain line length, the message gets cut off.

This makes drafting long messages extremely difficult. See [this video](https://streamable.com/m9kho) for a reproduction.

**Comment by gnprice** [comment]
Thanks @armaanahluwalia for this report! Very interesting.

To highlight one detail: this specifically happens when narrowed to a whole stream -- it doesn't happen when narrowed to a topic.

To describe here in words the exact symptom: when you type a long (draft) message, the compose box grows to make room... and in the video, it eventually grows to try to use some space that's hidden by the keyboard.

Some further observations in the video:
* The send button moves along with the bottom of the compose box... and right to the end of the video, you can still see a bit of the top of it. So the box is growing just a constant amount too far down.
* Even before you type anything, there's a different symptom present! ![image](https://user-images.githubusercontent.com/28173/53456805-9d8b7580-39e4-11e9-9f1f-373e9e1d8688.png)

  That blank white band between the compose box and keyboard is doing nobody any good.
* You appear to be on iOS. Helpful to mention for issues involving layout and/or the keyboard :slightly_smiling_face: , as they often vary by platform.

Further notes:
* With 23.1.110 (the current beta) on Android 9, I reproduce this issue -- but I don't reproduce the blank white band. So that's probably an unrelated issue.
* Gosh, though -- the height of that blank white band is just about equal to the amount we're going too low. So I still wonder if they're related somehow, even though one can happen without the other.

**Comment by gnprice** [comment]
Oh also -- this symptom is reminiscent of #3273 "Keyboard overlaps the compose box on iOS". That one was fixed in 23.0.109, but the history may be a clue for what to look into.

**Comment by gnprice** [comment]
(I went and filed #3370 for the blank white band.)

**Comment by gnprice** [comment]
Some discussion on a duplicate issue, #3414.

One direction to fix this would be to limit the compose box's height. But this shouldn't be a small fixed limit like 6 lines; see discussion on #3049. Instead it should fill the space available. See @borisyankov 's comment on #3414 about how that would ideally work.

Also @jainkuniya points out that the fact this happens only on a stream narrow means it only happens when the topic input is present. That's probably a clue. The compose box's layout already works just fine when there's no topic input; if we can make it work equally well when there is, that solves the problem.

**Comment by gnprice** [comment]
See #3579 for another report, with a nice screenshot demonstrating the issue.
