### ISSUE TITLE
Blank strip between compose box and keyboard

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3370]
In [this video](https://streamable.com/m9kho) taken by @armaanahluwalia to demonstrate #3369, there's another symptom present:
![](https://user-images.githubusercontent.com/28173/53456805-9d8b7580-39e4-11e9-9f1f-373e9e1d8688.png)

A blank white band between the compose box and the keyboard.

The video is from iOS. (@armaanahluwalia , would you confirm what version of the app it's from?) I don't reproduce this issue on Android 9 on 23.1.110.

Possibly-relevant recent history is in #3273 and its fix, c3b456016.

**Comment by jackrzhang** [comment]
I don't see this on an iPhone 7 with iOS 12.1, though it does reproduce on a simulated iPhone XR - I think that this bug is related to the fact that the shape of the touch screen on the newer iPhone models (as of the writing of this comment) is no longer a rectangle.

The application could be utilizing some value(s) for the height of the screen and by relation, the height of the keyboard, that are no longer represented the same way across the iPhone X's and earlier iPhone models.

**Comment by gnprice** [comment]
Thanks @jackrzhang for those repro details! That's helpful -- I agree it looks like evidence that this happens just on iPhones with non-rectangular screens.

I think this is likely an indirect symptom of #3066. We have some code that attempts to handle the notch / handle the display cutout / limit to the safe area, and I suspect this is caused by that code going awry.

**Comment by gnprice** [comment]
As of v26.9.132, this is still present though the symptom is a little subtler: the extra space is (in light mode) now the same gray color as the compose area, rather than white.

So basically it looks like a bad design choice rather than a bug. (Though in reality it's still a bug.)
