### ISSUE TITLE
Show diverse post times for multiple posts from the same user

### ISSUE THREAD

**Issue by athena-metis** [zulip/zulip-mobile#3375]
In zulip web interface the post times for consecutive posts from the same user are individually time stamped however in zulip-mobile only the time of the first post is listed even if the posts are many hours apart. This behaviour is the same in both portrait and landscape layouts.

**Expected behaviour:** Show time for either:-
- each post (may clutter the interface for faster moving conversation)
- show the time for each post where the previous post was X time after the previous post.

Example in the web version
![web-version](https://user-images.githubusercontent.com/32957443/53596107-edaa3980-3b96-11e9-93c9-93deacb4e861.png)

Example in zulip-mobile (v22.1.108 on android, this is also unchanged in v23.1.110)
![mobile-version](https://user-images.githubusercontent.com/32957443/53596635-0ff08700-3b98-11e9-9bad-7d23104cc206.png)

**Comment by athena-metis** [comment]
Just to confirm this behaviour is also the same in v23.1.110

**Comment by borisyankov** [comment]
That is intentional. There is no space to loose on a mobile phone's screen.
We might want to add some way to display this data, but it will definitely not be the same way as web.

**Comment by athena-metis** [comment]
I appreciate that space is limited and you wouldn't want to replicate the web approach, but not showing the time for more than the first post when they are hours apart is also not communicating valuable information.

**Comment by armaanahluwalia** [comment]
Agree with this feedback. Could probably just add a thin divider with a timestamp centered? Since vertical space isn't as much of an issue.

**Comment by timabbott** [comment]
I tend to agree with the reporter that we should include the timestamps.  It's often essential information for understanding what someone is communicating to see that they followed up 3 times an hour apart vs. 2 minutes apart.  And as is shown in that screenshot, our integrations are generally designed to not repeat the timestamp of an event because that information is expected to be displayed by the Zulip app itsefl.

**Comment by gnprice** [comment]
Thanks @athena-metis for writing this up! I agree -- some way of showing this information is a recurring thing I notice that I wish I had, and we should add it.

FWIW WhatsApp shows the time of every message. They stick it in the lower-right corner of the message's box; they manage to do it so that it takes no horizontal space, except on the last line of the message (which after all doesn't typically reach the very end of the line anyway.)

Some other apps (Android Messages; FB Messenger) take an approach where if you touch a message, a small area expands to show its timestamp.

I tend to prefer WhatsApp's approach. It may be a bit tricky to implement, but if we can I think it'd be pretty great.

One related observation: in mobile Zulip there is (typically) no visual indication at all of the distinction between two consecutive messages from the same user. That's sometimes confusing too. Most mobile messaging apps have some kind of bubble around each message; and in the Zulip webapp, the timestamp serves this function.

**Comment by ishammahajan** [comment]
WhatsApp's approach works for them, I think, because the `time`s they display are all in different columns with respect to each other. In Zulip, since we don't differentiate between a message the user sent, and others which are coming in, the time will always be in a straight line on the right. While this might not sound bad, I believe the interface will become too cluttered if we started doing something like this for *all* messages.

A possible solution for this is to check in realtime whether the message which comes after another one has been sent a certain amount of time after it (say 15 minutes), and only display the time if that is so. 

Another solution is that a swipe gesture could be added to the messages which reveals a date (lets say if the message is dragged to the left, the area revealed on the right would contain the date). I don't know about if we can implement this one with `WebViews` though.

<details>
<summary>Also spoiler</summary>

Bubbles seem to be a bad idea for zulip 😨 

</details>

**Comment by gnprice** [comment]
> WhatsApp's approach works for them, I think, because the times they display are all in different columns with respect to each other. In Zulip, since we don't differentiate between a message the user sent, and others which are coming in, the time will always be in a straight line on the right.

Hmm, I think this is fine. In fact, I mainly use WhatsApp in a group with several other people, where I can easily get a screenful at a time where all the messages are from other people, none from me. So this pattern simply isn't a factor there, and as I said above I think their design works well.

**Comment by ishammahajan** [comment]
There seems to be a misunderstanding.
To clarify my point, here's a [mockup](https://user-images.githubusercontent.com/33200024/54962025-3207da00-4f89-11e9-992b-ce0d669fb5d6.png).

Notice that the timestamps on the individual messages don't align with each other (they would in Zulip). I'm just wondering whether the alignment would make the UI cluttered, that's all.

That being said, I would like to work on this once a consensus is reached on how! 😄 
@zulipbot claim

**Comment by gnprice** [comment]
> Notice that the timestamps on the individual messages don't align with each other (they would in Zulip). I'm just wondering whether the alignment would make the UI cluttered, that's all.

Ah, I see. In the one active WhatsApp group I'm in, I guess people write longer messages :slightly_smiling_face: -- most messages are several lines long, so the bubbles are full width and those times are all vertically aligned. The exceptions are an occasional shorter message where it's further to the left, and an occasional message from me where it's a bit further to the right (because messages from others have an extra right-margin of maybe 30px.)

I think the longer messages are more typical for Zulip usage, so that's good for modeling after it.

I'll see about posting a suitable screenshot -- especially to illustrate the key thing they pulled off:

> They stick it in the lower-right corner of the message's box; they manage to do it so that **it takes no horizontal space**, except on the last line of the message (which after all doesn't typically reach the very end of the line anyway.)

which I'm not sure I've adequately explained.

**Comment by gnprice** [comment]
OK, well, here's at least a screenshot of a message demonstrating what I was describing:

![image](https://user-images.githubusercontent.com/28173/54965469-e07e3180-4f2d-11e9-918c-f31c26f4416a.png)

That's on web, but it works pretty similarly. The key bit is that if you draw a bounding-box for the message text, it actually *overlaps* the timestamp:

![image](https://user-images.githubusercontent.com/28173/54965507-115e6680-4f2e-11e9-8499-45d612ca6cf9.png)

One part of how to pull that off is that it's important the actual message *text* not overlap the timestamp, or even crowd it too closely. Through the magic of Chrome devtools looking at the web version, it looks like the technique is:
* The DOM tree is shaped like
```
div class=message
  div class=text-outer
    div class=text-inner
      span
        ... actual text ...
  div class=timestamp
```
* There's a rule like
```
.text-inner::after {
  content: "";
  display: inline;
  margin-end: 78px;
}
```
* So that `::after` pseudo-element acts as a buffer, or spacer -- if the text is too close to the end of the line where the timestamp will be, it wraps instead.
* There's more details -- when working on this, after trying something I recommend poking at the WhatsApp implementation to see how theirs works differently.
