### ISSUE TITLE
Copying Message to Clipboard

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3385]
There’s a bug in the way copying to clipboard works in messages. Currently it copies the entire message even if the area we long pressed was a link. In my opinion either this should be changed to copying just the link when pressing on a link and the entire message when pressing outside a link or we just always show two different options in the long press menu.

**Comment by ungps** [comment]
Hello.

What about something like this?

https://media.giphy.com/media/348sxe116DjLFFK4aq/giphy.gif

**Comment by ungps** [comment]
Hello.

Would something like [this](https://gfycat.com/HideousOffbeatInsect) work?

**Comment by ungps** [comment]
Hello.

Would something like [this](https://gfycat.com/HideousOffbeatInsect) work?

**Comment by ungps** [comment]
Hello,

Would something like [this](https://gfycat.com/HideousOffbeatInsect) work?

**Comment by borisyankov** [comment]
I think we would want the behavior to be on the same menu option.
The long-press menu is already filled with too many items.

**Comment by schezfaz** [comment]
Since the long press-menu is already filled with a lot of options, what we could do is directly copy the link to clip-board on long-pressing only the link portion of the message, without adding an intermediate step of selecting the correct option to do so. I believe this would be intuitive to the user as well, similar to how WhatsApp does it.

**Comment by ishammahajan** [comment]
I think this would work well, since it is pretty intuitive as well to press on a link and expect it to go on the clipboard. It is also how things work in Slack. There is another problem of pushing another option on the menu, what will happen if there are two links in the message? It seems like adding another menu to solve this problem isn't good for the UX. 

@zulipbot claim

**Comment by ungps** [comment]
Oh,

Last night I also worked on it, but It was pretty late and I was tired and forgot to mention that I will edit the first code I sent a preview for at beginning (and submit). Anyway, I went by a different approach. Long-pressing on a link will change the menu option from "Copy to clipboard" to "Copy link to clipboard". (preview)[https://gfycat.com/SilkyEvenBirdofparadise].

**Comment by ishammahajan** [comment]
I believe the option for `Copy Link to clipboard` should be left to copy the link of the current conversation to the clipboard so that it can be shared with someone not in the conversation but has access to it as mentioned in [#2623](https://github.com/zulip/zulip-mobile/issues/2623). Open to inputs about it though 😄

**Comment by gnprice** [comment]
Thanks to @pulkonet for pointing out that we have an existing issue for this! #2249 . (I remember being surprised that we didn't :stuck_out_tongue: , but didn't spot where we actually did.)

Closing this one as a dup, i.e. just to consolidate the discussion in one place. Everything said recently on this thread still holds just as true as it did before, though.

(And thanks again to @armaanahluwalia for re-raising the issue so that we're addressing it!)
