### ISSUE TITLE
There's no obvious way to unmute a topic

### ISSUE THREAD

**Issue by cyphase** [zulip/zulip-mobile#3473]
As far as I can tell, there's no way to unmute a topic in the mobile app. You can get to the muted topic from the stream's topic list, but not unmute it. If there is a way that I wasn't able to find, I think that makes this a valid issue anyway, since I looked all over the app and did some web searches trying to find a way to do it.

#267 and #415 are about adding mute/unmute, so this might be a regression.

Some possible, non-mutually-exclusive UIs for this:

* Long pressing on the topic in the stream topic list to bring up a menu
* A bar in the topic narrow like the unread messages bar
  * `This topic is muted (Unmute topic)`
* A "Muted topics" UI, which exists in the web/desktop apps under Settings

[CZO](https://chat.zulip.org/#narrow/stream/48-mobile/topic/unmute.20topic/near/739112)

**EDIT (2020-05-26):** Turns out there is *a* way to unmute a topic. You have to do a search that will return a message in the topic (you can search for the topic name), which gives you access to the topic recipient bar; then it's just a long-press and tap on "Unmute topic". That workaround doesn't invalidate this issue though.

**Comment by jainkuniya** [comment]
I have worked on this long time back, https://github.com/zulip/zulip-mobile/pull/982
@gnprice let's decide the priority and continue on this

**Comment by gnprice** [comment]
@cyphase Thanks for raising this! This would be a good feature to support, though I don't think it's a high priority (I don't think this is a super commonly-used feature.)

(I can't quite tell if we ever did support it -- looks like #982 wasn't merged, and I'm not sure if #415 covered this.)

I don't think we have a way to *mute* a topic either, so let's consider both of those together.

I think the main question we need to answer in order to implement it is, where should it appear in the UI? Thoughts in no particular order:
* For *un*muting, you don't naturally see the messages. (Though you can get to them from the stream's topic list if you want to.) So that pushes toward someplace like the stream's topic list.
* OTOH the topic list is kind of a pain to get to if you're reading the topic and want to mute it.
* I kind of like the banner. Do we currently show in any way that the topic you're looking at is muted, if it is? That'd be a good thing to do, and then it's natural to have the "unmute" action.
* OTOH that doesn't lend itself to a corresponding way to *mute* the topic in the first place.

**Comment by cyphase** [comment]
@gnprice
> I don't think we have a way to _mute_ a topic either, so let's consider both of those together.

You can mute a topic by long pressing on the topic header; which you can't see when narrowed to the topic, so you can only mute from a narrow that shows the header.

> I kind of like the banner. Do we currently show in any way that the topic you're looking at is muted, if it is? That'd be a good thing to do, and then it's natural to have the "unmute" action.

Not in the banner; muted topics are grayed out in the stream's topic list. Streams *do* show a muted speaker icon in the banner when muted, but you can't unmute from there.

> OTOH that doesn't lend itself to a corresponding way to _mute_ the topic in the first place.

Maybe the current stream settings button (the circled 'i') could be topic specific when narrowed onto a topic (right now it just shows the stream settings, even if you're narrowed into a topic)?

**Comment by chrisbobbe** [comment]
We've had another report of this, [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/unmuting.20a.20muted.20topic/near/859645).

**Comment by WesleyAC** [comment]
Closing this now that #4568 and #4608 are merged :)
