### ISSUE TITLE
Improve API retry functions

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3483]
Implement some of the suggestions in the review of #3254

We have a function `tryUntilSuccessful`. Its purpose is to 'never give up' retrying.
We are currently changing it to stop retrying on a 4xx error.
This is not sophisticated enough to handle all cases we have in mind and we should probably have two functions instead. 

An example where we need a more 'relaxed' version is #3288
While retrying is still desirable, failing is not critical.

**Comment by chrisbobbe** [comment]
If this is relevant here, https://github.com/zulip/zulip-mobile/pull/1323/commits/892127d3b31e6a06b3fa89fc98653f1231f377b4#diff-1b657602f015b258bd5cadf579cb6afa (closed without explanation) was an attempt to show a nice error screen on internal server errors, for the still-open https://github.com/zulip/zulip-mobile/issues/1254.

**Comment by gnprice** [comment]
Looking at #1323, one nuance I think will be important is: we don't want to just replace the app's whole UI with an error screen.

Webapps do that when they can't even load the page, which is a common symptom of server errors because they depend on the server to send the page in the first place. But our app has all its code, keeps a lot of data from the server, and already tolerates (though there are things we can do to make it better tolerate) being unable to reach the server at all for a while. So a 5xx response from the server should be no more disruptive than that.

**Comment by gnprice** [comment]
The specific content of this issue is what's described in this comment: https://github.com/zulip/zulip-mobile/pull/3254#issuecomment-469833756

I think all the outstanding items in that comment will be addressed by moving and renaming `tryUntilSuccessful` so that it's clear it's a helper specific to its call site in `doInitialFetch`, and not a generic abstraction. That's a step in #4165, so closing this.
