### ISSUE TITLE
Animated GIFs are static in lightbox

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3497]
@ishammahajan reported that animated GIFs don't work in the lightbox, posting this video:
https://chat.zulip.org/user_uploads/2/b/ZwHl_biOscMtw27V8GeNyJAu/Screen-Recording-2019-03-21-at-2.11.20-AM.mov

My description of that video:
* The animated image (presumably a gif?) works fine in the message list.
* But on touching it to go to the lightbox, there's just black -- the image doesn't show at all.

On further investigation, Isham added:

> It does come up, the initial image, after about 15-20 seconds

(Which I think means that after that loading time, a still frame showed up, but it still wasn't animated.)

@borisyankov [posted a test anigif](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Gifs.20don't.20get.20displayed.20in.20mobile.20apps/near/722158), and
* Boris then reported that it worked for him, on both iOS and Android
* But when I tried just now, on Android in v24.0.113, it didn't work:
  * The animation works just fine in the message list -- same as in Isham's video.
  * But when I go to the lightbox, I get just a still frame.

So, more debugging to be done! I think the first question to answer is: why did it work for Boris and not for me? Or put another way: in what conditions does it work and not work?

**Comment by ishammahajan** [comment]
For the folks who can't view/don't want to download .mov files -
![gif-slow-lightbox](https://user-images.githubusercontent.com/33200024/58354437-10df3f00-7e8f-11e9-962e-0845d2817bde.gif)

My full report:
- Initially opening the gif in the lightbox does not open the gif at all, just gives a black screen.
- After waiting for about 3-4 seconds (last time I tried it was 15 seconds) it gets loaded and displays a still.
- Opening it again after clicking away/force closing and reopening the app makes the still appear right away, which is why I am inclined to believe that it was a network issue.

**Comment by borisyankov** [comment]
Related: #3426

**Comment by agrawal-d** [comment]
Fixed in PR#https://github.com/zulip/zulip-mobile/pull/3825
