### ISSUE TITLE
JSON quote rendering is not colorblind friendly

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-mobile#3524]
I can't read the red text in
![Screenshot_20190617-081433](https://user-images.githubusercontent.com/313089/59607057-364f1980-90d8-11e9-9d2e-d18d6208fd64.png)

**Comment by gnprice** [comment]
Thanks @jmandel for the report!

Does this come out differently on the webapp? I.e. if you look at the same message, and also in dark mode.

(We generally use the same HTML for message bodies as the webapp, and try to keep the CSS similar.)

If it's the same, then we can fix it for both the same way; if it's different (and the webapp version works for you), then we should try to copy that :wink:

**Comment by jmandel** [comment]
It's much better on the web app in night mode:

![image](https://user-images.githubusercontent.com/313089/59641916-b7ce9800-9128-11e9-914f-c9eeef235237.png)

**Comment by gnprice** [comment]
Thanks -- that's a very helpful comparison!

I notice a few things from looking at the two screenshots:
* On web, the code block has a darker background than the surroundings. For us, it's a lighter background.
  * Looking at our CSS, it looks like we don't have anything specific for this in the night-mode case, so that's probably the root cause of this part.
  * We should probably just copy exactly the same CSS properties that the webapp sets.
* The red for strings is quite light on web, and rather darker for us.
  * Darker red text plus lighter background -> probably pretty similar lightness, so that's probably the core of the problem for you.
  * Again we should probably just copy what the webapp has.
* The webapp has something for the keys, too (they're in a light green, plus are bold), whereas we seem to leave them unstyled.
  * This part probably doesn't make as much difference for you one way or the other, but may be helpful for others.
  * And like other bits of this style, there isn't an obvious reason why the pros and cons of different choices would be different for us vs. the webapp -- so we should probably do the same thing as the webapp.
