### ISSUE TITLE
Add a jitsi / "add video call" button

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3546]
We've heard at least one user mention they'd like to see this:
> please add jitsi button, like in desktop client.

Filing just so we have a place to track any further requests for it, or discussion of use cases people want this for.

This isn't currently ripe for doing any design or engineering work on it.

**Comment by marcosms** [comment]
If what you need are more requests for this functionality to start its development, I am also interested in having a button to create videoconferences from mobile devices.

We are going to start using jitsi and it is something that is greatly missed. We started to use zulip in our offices, but we want to start using it in mobile devices. Now, only from the office we can start a videocall. It will be great that people in our works can start a videocall from their devices.

**Comment by chrisbobbe** [comment]
Thanks for the report, @marcosms!

A good first step for work on this will be to study the web app's implementation.

I just did a little bit of that. It looks like the web app does the following:

* Provide a button near the compose box with a video camera icon. (Space is really limited on mobile, and we'd want to make sure the button goes in a spot that makes sense.)
* When you click the video icon, a link to a video conference is inserted into the compose box, at the cursor position. I'm looking at the 'click' handler for '.video_link' in static/js/compose.js for this.
  * The choice of video call provider is made by the available and the selected video call providers: `.realm_available_video_chat_providers` and `.realm_video_chat_provider`, respectively, on `page_params`. On chat.zulip.org, Jitsi is available and selected. These params are made available in the `/register` response, so the mobile app has access to them.
  * [ ] In Jitsi's case, the URL itself is `.jitsi_server_url`, also on `page_params`. But! Even though `page_params` is [documented](https://zulip.readthedocs.io/en/latest/subsystems/events-system.html) as the place to access the data from the `/register` response, this one doesn't come from that — it's essentially hard-coded for use by the web app only. This means that this issue is blocked until that field is made available to mobile, preferably by including it in the `/register` response. I've just filed https://github.com/zulip/zulip/issues/14166 for that. Other useful-looking fields are also affected, so I'm optimistic about this issue being addressed.
  * The URL is conveniently inserted in Markdown link format (e.g., `[Click to join video call](https://meet.jit.si//550508269486988)`); this is done by `insert_video_call_url` in static/js/compose.js.

**Comment by chrisbobbe** [comment]
And the `jitsi_server_url` part of https://github.com/zulip/zulip/issues/14166 has landed! So, this can go ahead. Thanks @amanagr!

**Comment by chrisbobbe** [comment]
> We've had another report of this

And another, [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Jitsi.20Chat.20Button.20iOS/near/977028).

**Comment by gnprice** [comment]
Quick notes on how to implement this:
* (See https://github.com/zulip/zulip-mobile/issues/3546#issuecomment-597260426 above for details on what the webapp does, for comparison.)
* Now that the server sends `jitsi_server_url` in the `/register` response, we'll want to add that field to our `InitialData` type, which represents that response. Because only recent server versions send it, the field should be optional.
* Then we'll want to store it where we store other miscellaneous data from that response, in the `realm` part of our Redux state.
* We'll want another icon to appear in the `ComposeMenu` component, when that field is present and non-null. Should look like the "video camera" icon we use in the webapp.
  * It's possible we should rework this UI, as the number of icons that can appear here grows. But I think we can tolerate one more, so this feature doesn't need to block on that.
* If the user selects that icon, the handler for it should generate an appropriate link and insert it at the cursor in the message-content input.
  * None of the existing handlers in the compose menu happen to work that way, because they all deal with uploading images or files. So probably we'll want `ComposeMenu` to get passed as a prop a callback to let it do that. Its caller `ComposeBox` maintains the relevant state.

**Comment by wpj** [comment]
@zulipbot claim
