### ISSUE TITLE
notification: On clicking doesn't narrow down to conversation if app was in background.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3582]
I was using Zulip app few minutes ago, now I switched to another app. But still Zulip app is running in background. And as I gets a notification of PM message, I clicked on it. It doesn't took me to the PM conversation, rather ended up on the screen where I was when I switched to another app.

I reproduced it on the Android 9 One Plus Six Android Phone.

**Comment by gnprice** [comment]
Thanks for spotting this!

This is a key feature of notifications, so I think this is a good priority to fix.

**Comment by jainkuniya** [comment]
Got the problem.

Actually we are only checking for notification data on initial launch  in `AppEventHandlers`
```js
 componentDidMount() {
    const { dispatch } = this.props;
    handleInitialNotification(dispatch);
   ...
}
```

But what if app is resumed, `componentDidMount` will not be called.

So I tried putting it under `handleAppStateChange` like
```js
if (state === 'active') {
      handleInitialNotification(dispatch);
    }
```
Means whenever app state changes back to active, that means app is resumed, check for notification data.

Then it works.

But then on every substituent resume, native side is providing notification data and narrow is happening. 

Solution is to track on which notification we have acted either on native side or in redux state.

**Comment by gnprice** [comment]
Copying here my comments from a call with @jainkuniya the other day (and expanding on them a bit):

> Actually we are only checking for notification data on initial launch in `AppEventHandlers`

This is only one of two codepaths that are meant to handle the user tapping a notification. This is the one that operates when the notification action caused the app to be launched.

If you look at the implementation of `handleInitialNotification`, it's quite short and has two parts:
```
export const handleInitialNotification = async (dispatch: Dispatch) => {
  const data = await getInitialNotification();
  dispatch(narrowToNotification(data));
};
```
It gets the "initial" notification that caused app launch, and then it narrows to it.

Searching for `narrowToNotification` finds another call site:
```
  handleNotificationOpen = (notification: NotificationMuddle) => {
    const data: Notification =
      // $FlowFixMe clarify notification types
      Platform.OS === 'ios' ? extractNotificationData(notification) : notification;
    this.dispatch(narrowToNotification(data));
  };
```
So that's the other place where we narrow to a notification, after getting the data describing it. That in turn is invoked as the callback set here, in `NotificationListener#start`:
```
    this.listen('notificationOpened', this.handleNotificationOpen);
```

The purpose of that second codepath is precisely to handle notifications the user taps when the app is already running.

One debugging question to answer:
* Is that codepath working correctly when the app is already launched and in the *foreground*?

  If not, then it's simply broken. It certainly used to work, so that'd be a regression at some point.

If it works when the app is in the foreground and not when it's in the background, then it may be that the background case is falling through a crack between the two codepaths. I think the right solution will then be to make the "app already running" path cover the background as well as foreground case. Search like `git grep notificationOpened android/` to see where we emit that event (causing `handleNotificationOpened` to get invoked) on the Android-native side.

**Comment by gnprice** [comment]
(Also 

> Search like `git grep notificationOpened android/` to see where we emit that event (causing `handleNotificationOpened` to get invoked) on the Android-native side.

(Then on the iOS side: all the JS code described above is meant to work the same, but the logic that emits the event in the first place is separate; for that, look at the invoked `listen` method, and follow the trail through `NotificationsIOS` into the `react-native-notifications` library. But before that it'd be good to determine whether the same symptoms appear on iOS in the first place.)

**Comment by gnprice** [comment]
In discussion on #3612, @jainkuniya describes a diagnosis:

> Problem is:
> On master, we are only emitting event to react if `LifecycleState == RESUMED`, which only works in one scenario, i.e user is using App and notification comes (in this case LifecycleState is `RESUMED`).
> 
> But what if `LifecycleState` is `BEFORE_RESUME`, i.e user was using Zulip app few minutes back and currently on other app (Zulip app is present in the recent apps). In this case we weren't notifying react. We were just launching activity, which is more sort of bringing activity to foreground (as we have set activity to have single instance).
> 
> So [we need to] notify[] react every time except when app is in the state of `BEFORE_CREATE`, because in this case activity will be created and react will go in the flow of `initialNotification`.

Thanks @jainkuniya for reporting and then investigating this issue to reach that diagnosis! After discussion on #3612, I think the next step is I'll go and implement a fix based on that diagnosis.
