### ISSUE TITLE
Ios and web view (android too?) don’t go to first unread message in stream/topic

### ISSUE THREAD

**Issue by maltokyo** [zulip/zulip-mobile#3608]
When my users enter a topic with unread messages from the “unread messages” page, they expect to be taken to the first unread message, rather than to the top of the topic and have to scroll all the way down to the unread ones. Is it possible to go directly to the first unread message, when clicking on a topic? Maybe I missed something in setup or config/preferences?

**Comment by gnprice** [comment]
Thanks @maltokyo for the report!

Does the issue #3457 describe what you're seeing?

I'm also particularly curious about this bit:

> Ios and web view

Are you seeing this in the Zulip web app on iOS, or on a desktop? I don't think there's currently a known issue like this in the web app, so that would be quite helpful new information.

**Comment by maltokyo** [comment]
Yes #3457 describes what I experience in iOS app also. Same issue. So I
guess mines a duplicate. Will check also the web view again. Thank you for
taking up. My users get really frustrated with the mobile version not
scrolling to the unread section.

**Comment by gnprice** [comment]
Cool, thanks. Closing this in favor of #3457 .
