### ISSUE TITLE
Long topics names are truncated with no way to expand

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-mobile#3631]
in the overview screen, and in the stream-level topic list, and in the topic-level narrow view, topic names are truncated when they get too long ("..." appended to a fixed length truncation). This is fine, but there should be some way to actually view the full topic name, somewhere. Maybe as part of something you can see when you long-press on the message? 

(I wouldn't exactly call it a best practice but sometimes people create long topic names and you need to read the whole thing to make sense of it.)

Not being able to read full topic names is a mobile accessibility issue.

**Comment by gnprice** [comment]
Thanks! I agree, there should be a way to get the full topic name.

UI-wise, I feel like it belongs on the topic as a whole rather than an individual message. I think the popup when you long-press on a topic header would probably work nicely.

---

When there isn't a topic header, that means you've narrowed to that topic -- the whole screen is about that topic, and the (truncated) topic name is in the app bar. So it'd be good to make it tied to where the topic name appears up there.

Playing with a few other apps which have some kind of applicable "title" or "subject line", to see what they do (on my Pixel 2 XL running Android 10):
* Gmail: Long subject line just wraps, when viewing the single thread. The subject line isn't in the app bar, though -- which makes that work pretty smoothly in the layout, which it wouldn't for us.
* [Front](https://play.google.com/store/apps/details?id=com.frontapp.mobile) (a shared inbox for e.g. support queues): Same boat as us, AFAICT! Looked at a support@zulipchat.com ticket where the subject line was long, and I can't find a way to see the whole thing.
* Play Store: Similar to Gmail. Long app titles just wrap; and the title isn't in something like the app bar, so that works nicely.
* Wikipedia: Similar to Gmail.
* (system) Settings: Title of screen is in app bar, and just gets truncated with no way to expand. But at the parent screen where it appears in a list, it wraps. (Also the titles are all constants, so pretty short; you have to turn font sizes up a fair bit to start seeing this at all.)

Perhaps we might do the thing where when you're scrolled to the top, the app bar expands? ... Oh but that's tricky because the scrolling is happening inside a webview.

... Oho -- I just remembered the app where this exact problem annoyed me the other day. It was the system Files app (for e.g. PDFs downloaded from the web.)
* Files: Filename is in app bar, truncated. ... But I just discovered a way to expand it! Long-press on the title in the app bar, and a toast appears just below, with the full filename.

  That's not exactly a ringing endorsement of that design, because I spent a minute trying to find a way to do this the other day, and failed to discover it. But there it is. And we already make more use of long-press than many apps, so perhaps it'd be a more natural thing to try in Zulip.

---

One thing I'm seeing from looking at other apps: it seems like the fashion may have shifted away from putting unbounded text, like user-written titles, in the app bar. Gmail, Play Store, and Wikipedia all avoid this; Settings comes closer but not with user-written text; only Front and Files are really making the same design choice we are. And Front's design looks dated, like 2016-or-so Material Design, so only Files demonstrates a current design doing this.

OTOH a regrettable thing with the way Gmail, Play Store, and Wikipedia are handling titles is that there isn't really a good way to see the title when you're not scrolled to the top. That's sometimes annoying in those apps; for us it'd be a showstopper because, being a chat app, you routinely start (really, resume) at the bottom or middle and not the top.

**Comment by kshitijk83** [comment]
![Screenshot from 2019-11-16 20-07-48](https://user-images.githubusercontent.com/32035239/68990901-bee80680-087e-11ea-9e20-e88f49d496e6.png)
if I hold touch a topic this popup appears, we can do one thing that full topic can be shown here too above Mute topic option @gnprice

**Comment by gnprice** [comment]
Yeah, to make this concrete, here's a few places we can put this -- we might put it in all of them:
* The popup when you long-press on a topic header, in the message list.
* If you long-press on a truncated topic in the app bar, let's show a toast. (Like I described above from the stock Files app in Android 10.)
* If you long-press on a truncated topic in the topics-list screen for a stream, let's show a toast.
* If you long-press on a truncated topic in the unreads screen, let's perhaps also show a toast.

**Comment by hashirsarwar** [comment]
@zulipbot claim

**Comment by ramazanimwanza** [comment]
> Thanks! I agree, there should be a way to get the full topic name.
> 
> UI-wise, I feel like it belongs on the topic as a whole rather than an individual message. I think the popup when you long-press on a topic header would probably work nicely.
> 
> When there isn't a topic header, that means you've narrowed to that topic -- the whole screen is about that topic, and the (truncated) topic name is in the app bar. So it'd be good to make it tied to where the topic name appears up there.
> 
> Playing with a few other apps which have some kind of applicable "title" or "subject line", to see what they do (on my Pixel 2 XL running Android 10):
> 
> * Gmail: Long subject line just wraps, when viewing the single thread. The subject line isn't in the app bar, though -- which makes that work pretty smoothly in the layout, which it wouldn't for us.
> * [Front](https://play.google.com/store/apps/details?id=com.frontapp.mobile) (a shared inbox for e.g. support queues): Same boat as us, AFAICT! Looked at a [support@zulipchat.com](mailto:support@zulipchat.com) ticket where the subject line was long, and I can't find a way to see the whole thing.
> * Play Store: Similar to Gmail. Long app titles just wrap; and the title isn't in something like the app bar, so that works nicely.
> * Wikipedia: Similar to Gmail.
> * (system) Settings: Title of screen is in app bar, and just gets truncated with no way to expand. But at the parent screen where it appears in a list, it wraps. (Also the titles are all constants, so pretty short; you have to turn font sizes up a fair bit to start seeing this at all.)
> 
> Perhaps we might do the thing where when you're scrolled to the top, the app bar expands? ... Oh but that's tricky because the scrolling is happening inside a webview.
> 
> ... Oho -- I just remembered the app where this exact problem annoyed me the other day. It was the system Files app (for e.g. PDFs downloaded from the web.)
> 
> * Files: Filename is in app bar, truncated. ... But I just discovered a way to expand it! Long-press on the title in the app bar, and a toast appears just below, with the full filename.
>   That's not exactly a ringing endorsement of that design, because I spent a minute trying to find a way to do this the other day, and failed to discover it. But there it is. And we already make more use of long-press than many apps, so perhaps it'd be a more natural thing to try in Zulip.
> 
> One thing I'm seeing from looking at other apps: it seems like the fashion may have shifted away from putting unbounded text, like user-written titles, in the app bar. Gmail, Play Store, and Wikipedia all avoid this; Settings comes closer but not with user-written text; only Front and Files are really making the same design choice we are. And Front's design looks dated, like 2016-or-so Material Design, so only Files demonstrates a current design doing this.
> 
> OTOH a regrettable thing with the way Gmail, Play Store, and Wikipedia are handling titles is that there isn't really a good way to see the title when you're not scrolled to the top. That's sometimes annoying in those apps; for us it'd be a showstopper because, being a chat app, you routinely start (really, resume) at the bottom or middle and not the top.

**Comment by manzaa739** [comment]
Good

**Comment by gnprice** [comment]
Fixed by #3714. Thanks @jmandel and @hashirsarwar !
