### ISSUE TITLE
Presence-reporting logic is confused, in overlapping ways

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3699]
**EDIT**: Title reflects further discussion in thread below. Previous title:

### ~Failing to report presence inactive when put in background~

and original report from before that:

---

###  ~Can report presence active even after in background~

This is potentially one of the causes of #3659: which would mean it's causing people not to get notifications when they should.

It hasn't been confirmed empirically -- that'll be an important step in addressing the issue.

Found from studying the source. As I wrote there:

> > [@ray-kraesig] Or at least that the mobile app should be better about declaring its lack of presence. (We could possibly put something appropriate in `handleAppStateChange`... but there's a `reportPresence` call in there that looks like it's supposed to handle exactly this. )
> 
> Hmm. There is indeed that:
> 
> ```js
>   handleAppStateChange = (state: 'active' | 'background' | 'inactive') => {
>     const { dispatch, unreadCount } = this.props;
>     dispatch(reportPresence(state === 'active'));
> ```
> 
> But then there's also this:
> 
> ```js
> export const doInitialFetch = () => async (dispatch: Dispatch, getState: GetState) => {
>   dispatch(reportPresence());
>   setInterval(() => dispatch(reportPresence()), 60 * 1000);
> ```
> 
> That doesn't know anything about being in the background or not. And the `hasFocus` argument to `reportPresence` defaults to true. So one thing that may be happening is
> 
> * app is put in background
> * `handleAppStateChange` gets called; calls `reportPresence(false)`
> * sometime in the next 60 seconds, the timer set up by `doInitialFetch` fires
>   
>   * ... and the OS hasn't yet totally put us on ice. So it runs, and does effectively `reportPresence(true)`, which tells the server we're active after all.
> 
> So that, at least, seems like straightforwardly a bug.

**Comment by gnprice** [comment]
(If empirically it turns out this *doesn't* seem to happen, then that'll be interesting and it'd be good to understand why. Also that fact may be a fragile one, dependent on facts about the platforms that aren't evident in our code, and might not be stable over time -- in which case it'd be good to adjust the code so that it definitely behaves right even if those external facts change.)

**Comment by ray-kraesig** [comment]
At least on my Android test setup, it's both worse and better than that: the `setInterval()`-triggered `reportPresence` doesn't seem to be firing while the app is inactive... but `handleAppStateChange` isn't kicking off a presence report _at all_.

Looking at the code suggests this is due to the throttling in the middle of `usersActions#reportPresence`. Since it's almost always been less than a minute since the last heartbeat, the user will never be reported as idle.

**Comment by gnprice** [comment]
> Looking at the code suggests this is due to the throttling in the middle of `usersActions#reportPresence`. Since it's almost always been less than a minute since the last heartbeat, the user will never be reported as idle.

Oh gosh, indeed. That logic basically doesn't make sense at all in a world where this function has parameters.

A local fix might be to remember the last value we sent for `hasFocus` (and eliminate the other parameter, which is never passed), and bypass the throttling if the new value is different. But this code probably deserves bigger changes than that, too.

**Comment by gnprice** [comment]
From discussion [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/presence.20and.20notifications/near/800153) and on #3704 , having unpacked more clearly how the Zulip presence subsystem works and what the various states of it mean, we reached the conclusion that it doesn't actually make sense to send an `inactive` report!

So really the root bug here is that we have code that attempts to send such a thing. Then that bug is sort of masked by the other bugs we have in this logic, which cause us that code not to work as intended.

Anyway, #3704 should fix this whole cluster of bugs, notably by introducing a clearly-demarcated state machine.

**Comment by chrisbobbe** [comment]
Just a note (and gentle bump) with the update that #3704 was closed and replaced by #3727, which looks like it's paused on a question about whether some tests are unnecessarily thorough. So it seems like a fix is almost ready! 👍 

I noticed some of this confusion (a memory leak from setInterval being called multiple times without being cleared; looks fixed in https://github.com/zulip/zulip-mobile/pull/3727/files#diff-4a2845b8cea11d223c715f4d06a1fa15 on the active PR) while working on https://github.com/zulip/zulip-mobile/issues/3802. My progress on that issue isn't blocked or too conflicted (the change to fetchActions.js in #3727 is pretty small) but I was glad to see these proposed improvements to presence reporting, and that the bulk of the work is done. :)
