### ISSUE TITLE
Search people's names modulo diacritics, in autocomplete

### ISSUE THREAD

**Issue by maxandersen** [zulip/zulip-mobile#3710]
autocomplete seem to not work consistently for characters like `àåä`

If someone is named `ståhle` I can't get that to autocomplete it using `@sta`
but if you are named `stéph` autocomplete works with `@ste`

**Comment by gnprice** [comment]
Thanks @maxandersen ! I agree this would be a useful feature.

It looks like the webapp added this feature earlier this year, in zulip/zulip#11183 / zulip/zulip@b7a0a45f0. Before that, it had similar logic which it used for searching for a user in the right sidebar; we probably also want to use similar logic when searching for a user to e.g. start a PM thread.

A note on how to implement this: this looks like an example of some logic it'd be great to share the code for between web and mobile. For whoever takes this on, see
* c631bdb557c6cc04ce6ac0316bdd10c5add9e5bf and preceding commits in src/users/usersActions.js for an example of using code shared from the webapp
* zulip/zulip@a63786ac0d809721493995d08e2008fe6f4a3bb8 for an example of moving webapp code that wasn't previously shared into the shared package, and zulip/zulip@b70b7df22c36b6f3bf92fb99734cb22697b0a3ee for adding Flow types on it
* docs/howto/yarn-link.md for some mechanics for efficiently developing changes in shared code

In particular:
* `remove_diacritics` should definitely be shared, and I think it will be easy to share.
* `person_matches_query` would probably be good to share. It may take some more refactoring work to share, though. So that part should come after fixing this issue.

**Comment by ray-kraesig** [comment]
`remove_diacritics` is greatly simplifiable if we have access to [`String.prototype.normalize`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize):

```js
export const remove_diacritics = (str: string): string => 
  str.normalize("NFD")
    .replace(/[\u0300-\u036F\u1AB0-\u1AFF\u20D0-\u20FF\uFE20-\uFE2F]/g,'');
```

(This isn't quite complete; it will notably not remove strokes, such as those found in Ħ, Ł, Đ, or Ð _[sic!]_. Also, we may or may not want it to unify homographs and/or i + ı.)

**Comment by timabbott** [comment]
https://github.com/zulip/zulip/pull/13485 is an improved implementation we just merged for the webapp for this.

**Comment by gnprice** [comment]
Neat!

Here's the new version there, which is in a very similar spirit to Ray's comment above:
```
const unicode_marks = /\p{M}/gu;

exports.remove_diacritics = function (s) {
    return s.normalize("NFKD").replace(unicode_marks, "");
};
```

At that length it'd feel less bad to me to duplicate it. ... But also that change itself illustrates why it'd be better to share it. (The possibility we might add more normalization in the future -- so e.g. "Luk" finds "Łukasz", following on an example above -- is another reason.) Since it should be an easy one to share, I think that'll still be the preferred way to solve this issue.

**Comment by showell** [comment]
`remove_diacritics` is now in `static/shared/js/typeahead.js`.
