### ISSUE TITLE
Some emoji don't render in reactions list

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3716]
@Vamshi99 reported (at https://github.com/zulip/zulip-mobile/issues/2252#issuecomment-562986135 ):
> Some emojis don't show up correctly in the reacted people screen, they are just seen as a question mark for me.
> https://imgur.com/a/vGWMtXM

That was on a Redmi Note 5 pro, running Android 9. I reproduce on a Pixel 4 running Android 10.

**Comment by gnprice** [comment]
See https://chat.zulip.org/#narrow/stream/7-test-here/topic/emoji.20feature.20test/near/114151 for the repro in the images.

One quite odd bit: one of the emoji that doesn't show up right is `:angry:`.

But then I added the same reaction to another message... and when I "See who reacted" on that message, it *does* show up right!

And this persists: I can go back to the reactions-list screen for the one message and the emoji is still just a question mark, and then back to it for the other message and it still shows up just fine.

**Comment by jainkuniya** [comment]
**Observations:**
- This is reproducible on both Android and iOS
- Same set of emojis have issue on both Android and iOS

**Issue**
In our app code base, we have hard coded `unicodeCodeByName` in `src/emoji/codePointMap.js`

- It is outdated and not based on server (different Zulip server might have different file), latest can be found at https://chat.zulip.org/static/generated/emoji/name_to_codepoint.json 
PR #3100 will fix it.

So I manually copied all the code point, but issue wasn't fixed.

- There are some emojis whose name have changed over the time, like `arrow_left` (one of the emoji not rendered properly in the above image). Its new name is `left`, which is not present in our code. So in old messages if we get older name of emojis, or any other name which is not present in our list. Our code will throw error (`src/emoji/Emoji.js`)

```
const UnicodeEmoji = createIconSet(nameToEmojiMap, 'AppleColorEmoji');
```

as it is not able to create Icon with that name. It will only work for all those emojis whose name is present in `nameToEmojiMap`.

After doing RCA, I had two questions 
- how it is working in `MessageList`?
    - `MessageList` is webview, so it falls in other flow, doesn't require `createIconSet`
- how it works on web?
   - They are maintaining a whole/unified_reactions list of emojis https://github.com/zulip/zulip/blob/cfa62700809584003468a982605ef724204a5f21/zerver/management/data/unified_reactions.json this contain all the name (old, new if any) This list is also used for migration https://github.com/zulip/zulip/blob/cfa62700809584003468a982605ef724204a5f21/zerver/migrations/0097_reactions_emoji_code.py

Further I found that there is emoji_name mapping 
```
'1f3f9': {'canonical_name': 'bow_and_arrow', 'aliases': ['archery']},
```
https://github.com/zulip/zulip/blob/cfa62700809584003468a982605ef724204a5f21/tools/setup/emoji/emoji_names.py

**Conclusion**
Root cause of this issue is we don't have complete set of emoji names, which introduce other issue as well (will file a new issue for this, if not present): not able to add reaction to message if emoji name is not present on server (but on app) like `10`. It is changed to `ten` https://chat.zulip.org/static/generated/emoji/name_to_codepoint.json

**Proposed solutions**
- Create mapping on app side to handle such cases where emoji names are changed, but old message have old names.
- Fetch mapping and latest codePoint from server on app launch.
- Share this mapping and codePoint between mobile and web repo (from code perceptive)

**Comment by timabbott** [comment]
One possibility is that the mobile app should be fetching `name_to_codepoint.json` and similar details from the server, rather than having a copy embedded in the app.  That file does change from time to time, and the mobile app aims to handle older servers.

**Comment by gnprice** [comment]
I think we probably should be getting that data from the server. That's #2956.

Looking at this issue some more, though, I think that's not the main cause of this problem -- or anyway there's a simpler thing we should also fix that will fix this problem. The key observation is: these same reactions work just fine in the message list! So, what are we doing differently there?

The answer appears to be that for the message list we're using the reaction *codes* to identify the emoji for the reaction, while for the message-reaction list we're using the reaction *names*. In the latter case this is basically an accident; I think we didn't carefully think about which form of identifier was more appropriate. Certainly there's no good reason why we should use one in one place and the other in the other place.

And in fact the codes are more stable than the names -- in particular for Unicode emoji, which I think all these examples are, they're just a particular ASCII-ified representation of the sequence of Unicode codepoints for the emoji. So I think we should be using the codes in both places.

Fortunately that will be a pretty small change. We'll change a bit of `src/emoji/Emoji.js`, which implements the `Emoji` component; and we won't need `nameToEmojiMap` anymore, and might make a new data structure which is similar but with our emoji codes as keys.
