### ISSUE TITLE
Upgrade to Node v12

### ISSUE THREAD

**Issue by rk-for-zulip** [zulip/zulip-mobile#3780]
At present (2020-01), Node v12 is [the latest active LTS](https://nodejs.org/en/about/releases/). We should probably be ready to move up to v12 before v10 goes into "Maintenance" mode in 2020-04.

**Comment by ray-kraesig** [comment]
Current status:
* **Linux:** I've been using Node 12 for the last month or so. Seems OK so far.
* **Windows:** Known to be blocked by facebook/metro#453.
* **macOS**: Untested; unknown.

**Comment by gnprice** [comment]
> We should probably be ready to move up to v12 before v10 goes into "Maintenance" mode in 2020-04.

v10 will still be supported (as LTS) up to 2021-04-30. So I think it'd be OK to still be on it up to then, for as long as there's a reason to be.

Definitely it's good to be on current versions of tools when we can, though. So once that blocker on Windows is resolved, we should upgrade unless there's some other blocker in the way.

**Comment by gnprice** [comment]
Also, as you may well know but for concreteness here in the thread: what it means that we're currently on Node v10 is
* we use Node 10 in CI (see `.travis.yml`)
* we tell people to use Node 10 in the setup instructions (`docs/howto/build-run.md`)
* if people have build trouble and turn out to be using some other version of Node, we ask them to please use Node 10 instead.

So upgrading is a matter of confirming that everything works on the new version, and then updating those two places.

**Comment by gnprice** [comment]
> * but that probably means we'll need to update to React Native 0.62

I went and filed #3782 for that (and #3781 for the upgrade before it), so as to have a central name for it.

Because the comment was labeled "Current status", I took the liberty of updating it accordingly, wiki-style.

**Comment by gnprice** [comment]
We learned today ([chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/SOLVED.3A.20Prettier.20auto-formatting/near/896340)) about one major improvement that comes with Node 12: the startup time goes from painful (like 350ms for `node -e 1` in my quick testing) to in the range you'd expect (~50ms; vs 40ms `python -c 1` or 70ms `ruby -e 1`.) So that would be very nice -- everything we do from a script will get significantly faster!

Meanwhile, from looking at https://github.com/facebook/metro/releases , I learned that that Metro bug is also fixed in a stable release, [Metro v0.56.4](https://github.com/facebook/metro/releases/tag/v0.56.4) (thanks, Metro maintainers!). And Metro v0.56 in turn will come with RN v0.61, #3781 . So that's a bit closer than v0.62, then, happily.

**Comment by gnprice** [comment]
We're now on RN v0.61! So the known Metro issue on Windows that was blocking this is resolved.

The next step is for us to switch over in local development, and see if anything goes wrong. In particular I don't believe any of us have tested Node 12 on macOS yet.

**Comment by gnprice** [comment]
Both @chrisbobbe and I have been using Node 12 for our local development for a couple of months now ([chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/node.20v12/near/933022)), and things seem good. So I'll go make this update.
