### ISSUE TITLE
No error message is shown when deletion fails

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#3788]
If a user tries to delete a message which is too old to be deleted, no error message is shown when the attempt fails.

(See also #2902.)

**Comment by rheo-chiti** [comment]
Can I work on this issue?

**Comment by gnprice** [comment]
(Where #2902 was a similar issue affecting *editing* a message, rather than deleting.)

**Comment by amanjn38** [comment]
I would like to contribute to this issue.

**Comment by agrawal-d** [comment]
I would like to take this up. @ray-kraesig please can I be assigned to this?

**Comment by agrawal-d** [comment]
I have identified where the error is being swallowed. Its in `apiFetch.js:76` Im working to show a meaningful error message instead of a silent ignore.

What is the correct place to discuss the best practices fixes for this. In this issue thread or in the #mobile thread of Zulip community server?

**Comment by agrawal-d** [comment]
Catching the error in `src/api/apiFetch.js:76` might also possibly fix other issues where API failures are silently ignored.

**Comment by agrawal-d** [comment]
I have created a [PR that should fix this](https://github.com/zulip/zulip-mobile/pull/3795). Please have a look at it.

**Comment by awasthishubh** [comment]
@ray-kraesig @gnprice Wouldn't it be better if we can disable edit/delete feature from the client-side as well? (as done by other messaging apps like WhatsApp)

**Comment by agrawal-d** [comment]
@awasthishubh I think this can be confusing to users, as they expect a delete message dialog box to be shown. You referred to WhatsApp, which still shows a `delete for me` option on selecting `delete`. Zulip does not have a 'delete for me' feature AFAIK.

An alternative would be to pre-fetch editing time limit at app startup, and to still show the `delete` option, but not actually send the request to the server, but locally show a dialog instead.

**Comment by agrawal-d** [comment]
Regardless of how we choose to handle the timeout issue, if the deletion fails due to any reason at all, it is currently unhandled. 

The PR that I have made is a catch-all for all possible reasons ( including timeout ).

**Comment by awasthishubh** [comment]
@agrawal-d I was just putting an idea of making it a client-side feature as well. Maybe we can just grey-out the text according to time.
In no way, I meant to oppose your PR. Sorry if you felt like that. I too believe `Catch` is needed there. :)

**Comment by agrawal-d** [comment]
Please do not apologize! If my PR is not a good solution, the by all means I wouldn't want it to get merged. I was just putting forward my opinion on your suggestion.

**Comment by ray-kraesig** [comment]
> Wouldn't it be better if we can disable edit/delete feature from the client-side as well? (as done by other messaging apps like WhatsApp)

For reference, this is #2972 (edit) and #2793 (delete).

**Comment by gnprice** [comment]
Thanks @ray-kraesig and @agrawal-d !

On this point:

> Wouldn't it be better if we can disable edit/delete feature from the client-side as well?

Absolutely so. In general, when there's something the user won't be able to do in certain cases, the way we ideally want to handle it is:
* (a) The client disables that bit of the UI, with an explanation as appropriate.
* (b) If the user does somehow make the request, the server rejects it.
* (c) If the server somehow ends up rejecting a request that we make, the client shows an informative error message.

Case (a) is important because that's the nicest experience for the user. Case (b) is important so policies apply regardless of client. Case (c) is important, even with (a), because the client may not always succeed in predicting whether the server will allow the request: the server may have features this version of the client doesn't have yet, and there's always also the possibility of a race, where something changed just before the user tried the request.

This issue was to do (c), but it would also be good to do (a).
