### ISSUE TITLE
emoji autocomplete only searches at start of each emoji name

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3948]
on web:
![image](https://user-images.githubusercontent.com/18511177/75801288-e2d54680-5da0-11ea-94b0-9bf444f7530d.png)

on mobile:
![image](https://user-images.githubusercontent.com/18511177/75801401-17e19900-5da1-11ea-811f-e97764c6c66d.png)

Issue: 
We filter emoji using `x.indexOf(query) === 0`, which only checks if emoji name starts with `query`. We should use `x. includes(query)`, so that all emojis which contains `query` are included. 

Moved here from:
https://github.com/zulip/zulip-mobile/pull/3847#discussion_r371967822

**Comment by chrisbobbe** [comment]
I think this is covered in #3833, which was formerly called "Emoji reaction search only checks beginning of name," but then we updated it with the idea of sharing the code the webapp uses, since a lot of work has gone into that and it's well-tested. What do you think?

**Comment by chrisbobbe** [comment]
I'll close this as a duplicate (see my previous comment), but please let me know if this is incorrect. 🙂

**Comment by gnprice** [comment]
Thanks @jainkuniya for the report, and @chrisbobbe for spotting that cross-reference!

This is the same issue as the original report at #3833, and it'd be fixed by completing #3833. But I think it's probably helpful to track this symptom, or user-facing issue, separately from that solution.

For one thing, that gives us a more specifically on-point thing to refer to in a thread like the one at https://github.com/zulip/zulip-mobile/pull/3847#discussion_r371967822 where someone notices the issue. :slightly_smiling_face: It also gives us a place to notice that we're hearing repeated reports of it -- as I guess we now have, between #3833 and that thread.

Since #3833 is now about sharing the implementation, probably it's most convenient to make this thread the one for this user-facing issue.

Given that observation that we're repeatedly noticing the issue, I think it'd also make sense to fix the issue directly, even before sharing the implementation per #3833. That's only true if it doesn't involve a lot of code -- but it sounds like it wouldn't.

**Comment by chrisbobbe** [comment]
OK, sounds good! Luckily, there's a PR already in progress for the quick fix; @gnprice or @ray-kraesig, would one of you like to make the necessary changes to https://github.com/zulip/zulip-mobile/pull/3836 and merge it, in one go? I'm happy to look at it myself, but it should be pretty small and self-contained, and I don't want to slow progress on it.

The additional step done in that PR is to bring not only the filtering, but also the sorting, closer to what the web app does. If an emoji name does happen to start with the search term, it should be listed first.

As I said at https://github.com/zulip/zulip-mobile/pull/3836#issuecomment-577890720,

> An extra challenge has become part of this issue, as described here: https://github.com/zulip/zulip-mobile/issues/3833#issuecomment-577837272. This will most likely mean passing a compareFunction argument to `.sort()` in the same area of the code you were looking at. (Docs can be found [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)). The tests should also reflect the new sorting, and they should all pass. Also, please update the commit message to describe the sorting.

**Comment by ray-kraesig** [comment]
> OK, sounds good! Luckily, there's a PR already in progress for the quick fix; @gnprice or @ray-kraesig, would one of you like to make the necessary changes to #3836 and merge it, in one go? I'm happy to look at it myself, but it should be pretty small and self-contained, and I don't want to slow progress on it.

I ended up reworking that PR more than trivially, so I'm putting it up for proper review as #3963.

> But merging this shouldn't block on the sorting part.

Fortunately, that had already been done, and valid test data provided!
