### ISSUE TITLE
Accessibility of "Tooltips" for new users after a long press

### ISSUE THREAD

**Issue by harshbisle** [zulip/zulip-mobile#4004]
There is no message/text pop-up  after long press on  the inbox(the one that opens up after clicking the notification) ,mentions(@), starred(⭐️)etc

**Comment by gnprice** [comment]
This sounds like potentially two issues:
* (a) We should make sure the app is accessible for users who can't see well.
* (b) We could have tooltips on long-press of the icons.

Looking at some other apps, I don't find many that do (b). Mostly if I long-press an icon, it just does the icon's action, the same as a normal press would.

(a) is important. I don't really know the status of it, because I don't know what tools people normally use to use a phone when they aren't able to see the screen well. Certainly a tooltip itself will often not help :wink:; though it might if someone has a certain level of visual impairment and has set their text size very large.

I'd be glad to see an issue where someone finds the upstream advice from Google and/or Apple for Android or iOS respectively, tries out the app the way someone would who's blind (or has other accessibility needs), and identifies things that don't work. Then also very glad to see PRs to fix those things.

**Comment by ray-kraesig** [comment]
I believe *this* bug is just b). The fact that the first word of the title is "Accessibility" seems to be merely an unfortunate happenstance: both here, and in [the discussion in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/.22Tooltips.22), it explicitly addresses *new* users, not any other class; and – as you note – its suggested action is at best unhelpful for users who need a nonvisual interface.

Refiling as `a-onboarding`.

**Comment by ray-kraesig** [comment]
... that said, tooltips on long-press probably wouldn't help new users, either. As noted above, that doesn't seem to be a thing most other apps do; they generally wouldn't be discovered by the users they'd be intended for.

Perhaps, as we so often do, we should take a cue from the webapp, and implement something like the popups it has for first-time users. An issue (or at least a chat thread in #mobile) along those lines would also be welcome! 

But I don't think it's appropriate to transform this suggestion into that one. Closing.

(@harshbisle, if I've misinterpreted you – or if you'd just like to discuss this further for other reasons – please feel free to poke me in chat!)
