### ISSUE TITLE
Apple warning about UIWebView (2020-11 deadline)

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4093]
Apple sends the following warning by email when I upload a new version of the app:

> **ITMS-90809: Deprecated API Usage** - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

I believe we don't actually use `UIWebView` -- we switched to `WKWebView` in 24.0.113, over a year ago. Unless we messed that up somehow. But `react-native-webview` at the version we're using still has code that refers to the old `UIWebView`, which is almost surely enough to explain the warnings.

Looks like I started getting these warnings with the upload of 26.23.146, on 2020-03-09. That may reflect a change in our app then, or it may just reflect Apple starting to issue these warnings.

It looks like react-native-webview dropped UIWebView in v7.0.1:
https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1

So we should upgrade to that version, and then see if that eliminates this warning.

That version in turn comes after the r-n-webview v6 change to use AndroidX. So after we ourselves migrate (#3852), we should be able to try that upgrade.

**Comment by chrisbobbe** [comment]
I'm currently planning to upgrade `react-native-webview` to 7.0.0 in the same commit as the RN v0.60.0 upgrade, because of peer dependency constraints. Then, as a follow-up, I'm planning to take it to v7.0.3 because of a want expressed in 1982f3fa8183502b5388dec0377c518fdeedf. If you want, I can stop by v7.0.1 in a separate commit before v7.0.3, with a note about dropping UIWebView, or I can just give a shoutout to that in the v7.0.3 commit.
