### ISSUE TITLE
lightbox: Tap outside image to show header/footer again

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4098]
@eugenolman reports [in chat](https://chat.zulip.org/#narrow/stream/9-issues/topic/Lightbox.20context.20menu.20mobile/near/873685):
> Once you click on an image you have it full screen resized and outside the picture you have black screen. [...]
> Now if you have a slim picture you have alot of black. And to return to menu ere you have an X to close the image you need to tap on the image. Nothing happen if you tap on the black part. [...]
>
> Double tap on black increase zoom. Single tap nothing.
>
> Normally you should be able to tap on black and get the menu back then click X to return to the thread.

I agree. This would give us the same behavior as other apps I briefly checked:
* FB Messenger on iOS
* (Google) Photos on Android
* built-in Photos app on iOS

As is, once you hide the header and footer I don't see a way to get them back, short of exiting the lightbox and coming back to it.

**Comment by agrawal-d** [comment]
>As is, once you hide the header and footer I don't see a way to get them back, short of exiting the lightbox and coming back to it.

It is possible to toggle the header and footer - tapping on the image does this.

As for the feature to enable toggle on tapping outside the image, it interferes with the image's built-in "double-tap to zoom in/out" feature, i.e, if you add the `onPress` listener to the entire container instead of just the image, and double tap on the image to zoom, it causes the header & footer to quickly show and hide.

IMO it's best to leave it the way it is right now.
