### ISSUE TITLE
Migrate to GitHub Actions (from Travis CI)

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#4174]
GitHub Actions is a new product by GitHub that we can use to automate our CI workflow. I've used it on some of my own projects, and it's pretty good. It runs fast and the dependency downloads are not flaky like in Travis CI. 

We should try out GitHub actions to evaluate it.

Documentation: https://help.github.com/en/actions

**Comment by chrisbobbe** [comment]
I seem to remember some discussion about CI...just not being run anymore, in this repo. Is that what led you to consider GitHub Actions? Do you remember where that discussion was, or am I imagining things?

**Comment by agrawal-d** [comment]
> . Is that one thing that led you to consider GitHub Actions?

Partly yes, and partly because it's integrated into the GitHub UI, so we won't have to switch between services.

>Do you remember where that discussion was, or am I imagining things

:smile: Yes, there was a discussion some time ago, as a comment on a PR: https://github.com/zulip/zulip-mobile/pull/4143#issuecomment-643004206

**Comment by gnprice** [comment]
Turns out:
* Our CI was *running* just fine all along -- but failing to post results to the PRs;
* I was able to [fix that by just](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/travis.20results/near/933188) revoking Travis's access to my account and authorizing it again.

So we're now back to Travis working just as well as it always did.

Faster and less flaky would still be quite attractive, though! So this remains a useful thing to try.

**Comment by gnprice** [comment]
I noticed on #4250 that Travis was back to not posting results on the PRs.

Looking again at [the build history](https://travis-ci.org/github/zulip/zulip-mobile/pull_requests) on Travis's own site, it's still the case that it is running the builds, just apparently failing to post results. But it's really not very useful when it doesn't post results.

I could repeat the "turn it off and on again" fix that seemed to work in July, and maybe I will. But if I have to do that every couple of months when we notice it's broken, that will get old real fast -- really it already has. So we should probably consider Travis to be on its last legs.

**Comment by gnprice** [comment]
I'd noticed again recently that some PRs weren't getting CI results posted from Travis. Today @hackerkid [discovered](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/travis.20ci/near/1077862) that this is true across the Zulip project, and that the reason is that Travis CI has recently cut off free service for most open-source work, including Zulip.

Travis has always been a pretty low-quality product, so I'm not particularly sad about this development. It does mean it's now definitely time to go ahead with this migration.

**Comment by titanous** [comment]
I'll take this one.
