### ISSUE TITLE
Bug with Night mode

### ISSUE THREAD

**Issue by manan2501** [zulip/zulip-mobile#4197]
### Current Behaviour
When we toggle our theme from default to night mode or vise-versa, we are redirected to home page.

### Expected Behaviour
It should stay on the settings page itself. 

### Example
[![bugf29340950876bd6e.gif](https://s7.gifyu.com/images/bugf29340950876bd6e.gif)](https://gifyu.com/image/Wb4W)

**Comment by chrisbobbe** [comment]
Thanks for the report! @gnprice, it sounds like this issue is getting more attention; see https://github.com/zulip/zulip-mobile/issues/3994#issuecomment-657332950 for another recent comment on it. I've got an open PR (https://github.com/zulip/zulip-mobile/pull/4046) that would fix it, and you've merged about half of it; it looks like the rest have gathered some conflicts. I'll sort those out now.

**Comment by chrisbobbe** [comment]
I'm closing this in favor of the original issue, #3994, but I noted that the issue has had more attention at https://github.com/zulip/zulip-mobile/issues/3994#issuecomment-661283736. 🙂
