### ISSUE TITLE
Use new logo!

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4200]
With the release of [Zulip Server 3.0](https://blog.zulip.com/2020/07/16/zulip-3-0-released/), we got a new logo! Let's use it.

Here are some [Apple docs](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/) and [Android docs](https://developer.android.com/google-play/resources/icon-design-specifications) on the app icon.

### Here's a list of places we'll need to update with the new logo.

A couple of these are external to the app itself, in the app stores.

- [ ] iOS home screen etc. (white on color/gradient background, full-bleed; PNG, sizes [here](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/))
- [ ] App Store (see iOS specs)
- [ ] Play Store (same series of PNGs as for iOS but another size; [specs](https://developer.android.com/google-play/resources/icon-design-specifications))
- [ ] Android launcher as WebP (white on color/gradient background, in circle; sizes according to “48dp” example [here](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp)) *(the old-fashioned way — but required even if we do an adaptive icon, because those are several OS versions newer than the oldest we support)*
- [ ] [static/img/logo.png](https://github.com/zulip/zulip-mobile/blob/master/static/img/logo.png) (white on color/gradient background, in circle; PNG; 40x40) *(used only in one uncommon situation, but whatever)*
- [ ] Android notifications icon (White Z on transparent background; in fact all channels but alpha get ignored, per [docs](https://developer.android.com/about/versions/android-5.0-changes#BehaviorNotifications). … Then I can’t actually find documentation for the size, but our current ones are “24dp” i.e. half the sizes in [this example](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp), and are WebP.)
- [ ] [static/img/message-loading.png](https://github.com/zulip/zulip-mobile/blob/master/static/img/message-loading.png), used in the splash screen on launch (white on gray background, in circle; PNG; 512x512)
- ?? [static/img/zulip-logo.png](https://github.com/zulip/zulip-mobile/blob/master/static/img/zulip-logo.png) (25 KB, 512×512, RGB, has alpha channel) *(is this used anywhere?)*
- *optional/later (as we don’t support this now):* Android [adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) for launcher

-----

### Likely won't need these details about SVGs in React Native—all the in-app logos are PNGs and there's not a clear need to change that right now:

For static/img/logo.png and static/img/message-loading.png it seems possible to use SVG files instead of PNGs, if we want, but there are some extra hoops we'd have to jump through because we're not working in the web (well, the WebViews are, but these logos appear outside of them in normal React Native land):

- Looks like [`react-native-svg`](https://www.npmjs.com/package/react-native-svg) would be useful
- In its [doc](https://github.com/react-native-community/react-native-svg#use-with-svg-files), looks like `react-native-svg` wants us to also add [`react-native-svg-transformer`](https://www.npmjs.com/package/react-native-svg-transformer) to use actual SVG files conveniently
- `react-native-svg-transformer` needs us to teach Metro how to treat SVG files; they've got some instructions to tweak our `metro.config.js`
- `react-native-svg` says we might at some point want to use [`babel-plugin-inline-import`](https://www.npmjs.com/package/babel-plugin-inline-import) (this probably doesn't apply to us?)

**Comment by chrisbobbe** [comment]
It may also be a good opportunity to revisit some of these old issues (but I wouldn't say they block anything):

- https://github.com/zulip/zulip-mobile/issues/3571
- https://github.com/zulip/zulip-mobile/issues/2756

**Comment by gnprice** [comment]
Here's a list of places to update that are related to the mobile app, which I prepared in one of our release-planning docs last week. It overlaps with your list:
- [ ] iOS home screen etc. (white on color/gradient background, full-bleed; PNG, sizes [here](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/))
- [ ] App Store (see iOS specs)
- [ ] Play Store (same series of PNGs as for iOS but another size; [specs](https://developer.android.com/google-play/resources/icon-design-specifications))
- [ ] Android launcher as WebP (white on color/gradient background, in circle; sizes according to “48dp” example [here](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp)) *(the old-fashioned way — but required even if we do an adaptive icon, because those are several OS versions newer than the oldest we support)*
- [ ] `logo.png` (white on color/gradient background, in circle; PNG; 40x40) *(used only in one uncommon situation, but whatever)*
- [ ] Android notifications icon (White Z on transparent background; in fact all channels but alpha get ignored, per [docs](https://developer.android.com/about/versions/android-5.0-changes#BehaviorNotifications). … Then I can’t actually find documentation for the size, but our current ones are “24dp” i.e. half the sizes in [this example](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp), and are WebP.)
- [ ] splash screen on launch
- [ ] *optional/later (as we don’t support this now):* Android [adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) for launcher

**Comment by gnprice** [comment]
After some discussion [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/new.20logo/near/951224), this is ripe for someone to take on. See there for
* SVG files to use as the sources for the different graphical variations needed
* an example command to convert from SVG to various sizes of PNG

For WebP, a similar command may work, or see [Android Studio instructions](https://developer.android.com/studio/write/convert-webp).

For all of these but the App Store and Play Store, we'll just want to update the files in the repo, with a PR.

For those two, just post the files here and I can use them to edit our listings.

**Comment by gnprice** [comment]
And done! Followups include:
* make a new release, and follow the usual build+upload sequence
* update icon to be shown in the Play Store listing
* in the App Store release process, try to confirm that the icon for the listing will be updated (as I believe it will be)

and later or optionally:
* static/img/logo.png comes out pixelated and the reason [seems to be straightforward](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/new.20logo/near/954170); fix it, or just remove it (as we use it in one uncommon situation, and it's not clear it improves the design there)
* apply the new brand color, once we've picked it in general
  * to the variable `BRAND_COLOR`; and `static/img/spinning-progress.png`; and experiment to look for other places
* use `setColor()` to apply the new brand color [to Android notifications](https://developer.android.com/about/versions/android-5.0-changes#BehaviorNotifications) and in particular the icon there (this is a feature that's been available forever and we just haven't been using; I learned about it in reading docs for doing this icon update; quick demo [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/new.20logo/near/954313))

**Comment by gnprice** [comment]
> * static/img/logo.png comes out pixelated and the reason [seems to be straightforward](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/new.20logo/near/954170); fix it, or just remove it (as we use it in one uncommon situation, and it's not clear it improves the design there)

Just did this in 5ada9da26. Now that we have the script, this was very quick to fix! So might as well do so, since I'd just diagnosed it and the issue was fresh.
