### ISSUE TITLE
Android/iOS Thumbnails not showing in v3.1 after upgrade from 2.1.7

### ISSUE THREAD

**Issue by maltokyo** [zulip/zulip-mobile#4215]
I have upgraded from 2.1.7 to 3.1 (docker version) and thumbnails of images work as expected only in the web version, but not on Android app. Is there any logs I can provide? Any guidance would be helpful.

**Comment by maltokyo** [comment]
Confirmed this is for iOS also.  Desktop and web versions show all thumbnails.

**Comment by maltokyo** [comment]
I have setup everything according to here: https://github.com/zulip/zulip/blob/3ee69f3da9956aa45580696b8ad7fe20b41c1a43/docs/subsystems/thumbnailing.md

Why would people not want thumbnails?  According to @timabbott this is experimental and not working.  I guess that should be mentioned above.

**Comment by gnprice** [comment]
Thanks @maltokyo for the report. We had further discussion [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Thumbnails.20in.20mobile.20apps.20not.20working/near/971581). (And Tim edited that docs page so that it says it's experimental.)

I agree it would be super valuable to have thumbnails fully working and supported, and it's frustrating that we haven't yet been able to do that. We don't seem to have an issue for this in the server's tracker, but there is #3790.

**Comment by gnprice** [comment]
In the chat thread, you added:
> Thumbnails in the web version do not work either.. They just appear to work in a web version if you have super fast internet. Zulip now basically just loads a tiny sized (x-pixels x y-pixels) version of the HUGE (MBs!) file as a "fake thumbnail". This is hardly best practice..

so it looks like there isn't a mobile-specific issue here, and it's a reflection of the fact that the server doesn't fully support thumbnailing in general. Thanks again for poking us on that.
