### ISSUE TITLE
Remove `react-native-text-input-reset` dependency, if possible

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4239]
I see this deprecation warning when running `./gradlew help --warning-mode=all` from `android` (recommended by [this doc](https://docs.gradle.org/5.6/userguide/upgrading_version_5.html#changes_5.6)):

```
> Configure project :react-native-text-input-reset
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

Its [GitHub page](https://github.com/nikolaiwarner/react-native-text-input-reset/tree/master) says it was only meant to be temporary, so I'm not confident that this deprecation warning will ever be addressed. But from a quick skim of the RN issue it was aimed to be a workaround for, https://github.com/facebook/react-native/pull/12462, it's not immediately clear that that issue has been fixed in any version of React Native.

A complete fix must include:
- this dependency is removed
- we're confident that https://github.com/facebook/react-native/pull/12462 doesn't affect us

**Comment by aryanshridhar** [comment]
Working on it :+1:

**Comment by aryanshridhar** [comment]
Taking this issue :)

**Comment by aryanshridhar** [comment]
Hey , I see no difference while removing <code>TextInputReset</code> from <a href = 'https://github.com/zulip/zulip-mobile/blob/7e36838cc69a9d181839bc1ead72e45274da92e5/src/compose/ComposeBox.js#L102'>here</a> as the behaviour of ComposeBox still remains the same (contents of textinput being properly cleared)

Should I go on with it , and open up an PR removing this package ?

**Comment by chrisbobbe** [comment]
Thanks for looking into this, and it sounds promising that it's working on your device! It would be great if you could read through https://github.com/facebook/react-native/pull/12462 and confirm that we can be reasonably sure that it won't affect other people's devices, too. I'm not very familiar with the details, but there seemed to be some nuances that suggest some people might see the bug, while others don't.

**Comment by aryanshridhar** [comment]
As rightly said by you , looks like the same problem still persists in many android device and hasn't been merged due to lack of <a href = 'https://github.com/facebook/react-native/pull/12462#issuecomment-477295348'>verification</a> of the same .
However this issue can still be solved using native module method by integrating this <a href = 'https://github.com/facebook/react-native/pull/12462#issuecomment-298812731'>code</a> to zulip-mobile . 
Currently looking into it and trying it out .

**Comment by yash-rajpal** [comment]
Is this issue still available? If it is I would like to work upon it. 
I understand the issue and also looked at the native required to clear the text input and restart the keyboard. Should I work on this?

**Comment by gnprice** [comment]
This turned out not to be necessary: the library remains maintained after all, and the maintainer promptly merged last year a PR @chrisbobbe sent to fix this warning:
https://github.com/nikolaiwarner/react-native-text-input-reset/pull/14

We could still cut the library out if we learn that the issue it's meant to work around no longer applies, but that'd take some work to investigate, and there's no longer an obvious motivation to do so.

**Comment by gnprice** [comment]
Well, perhaps I spoke too soon -- @chrisbobbe points out to me that while the library's maintainer did merge that PR, they haven't actually done a release since then: the latest is still (per https://www.npmjs.com/package/react-native-text-input-reset) 1.0.4, from 2019.
