### ISSUE TITLE
Opening notification for inactive account attempts to look up in the active account

### ISSUE THREAD

**Issue by bjorn3** [zulip/zulip-mobile#4371]
I have the rust-lang zulip active most of the time. I got a notification for the bytecodealliance zulip today. When I clicked on it, zulip for android attempted to look the stream and topic up on the rust-lang zulip and gave a message that ot didn't exist.

**Comment by gnprice** [comment]
Thanks @bjorn3 for the report! Sorry for the slow response.

Is it possible that you were logged into the bytecodealliance Zulip org as two different accounts? If you were, then this was a known bug: see #4631.

That bug has since been fixed (in release v27.181, out last month), and we've made other changes to this logic as well, so I'm hoping this is fixed for you. If you see these symptoms again, please reopen or file a new issue, and we can debug.

**Comment by bjorn3** [comment]
> Is it possible that you were logged into the bytecodealliance Zulip org as two different accounts?

I have an account in rust-lang open most of the time. I got a total of four zulip accounts configured in the app, all of which are for a different instance.

I believe it has indeed been fixed since though.

**Comment by gnprice** [comment]
OK. Thanks for the followup! Do let us know if you see an issue like this again.
