### ISSUE TITLE
Android: `RealmScreen` unusable in landscape orientation when input is focused.

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4386]
I discovered this while working on #4315, but then I found out that it was happening with or without the changes in #4315.

Reproduction recipe (works for me on the office Android device I'm using, a Samsung Galaxy S9):

1. Go to the "realm screen", the screen where it says "Enter your Zulip Server URL", in the normal portrait orientation.
2. Make sure the text input is focused (it should be by default, and it's hard to remove focus; read on for one way I've managed to do so).
3. Rotate the device into a landscape orientation.
4. See that the prompt and example input are gone, as in the following screenshot, and the "Enter" button has been renamed "Go". Also, pressing "Go" has no visible effect.

![image](https://user-images.githubusercontent.com/22248748/103914994-93eef080-50d8-11eb-83ae-0693910ea047.png)

Pressing "Go" does seem to have an effect, just not an immediately visible one. After pressing "Go", if I go back to portrait mode, I see the expected result of the action—either an error message like "Cannot connect to server" if I entered an invalid realm, or the auth screen for a valid realm.

The way I was able to see the realm screen without the input being focused is I entered a valid realm, submitted it, then hit "back" from the auth screen. When the input is not focused, things look more as I'd expect them to:

![Screenshot_20210107-081748_Zulip-debug](https://user-images.githubusercontent.com/22248748/103916303-43789280-50da-11eb-9dd0-23d1fbb9beaf.jpg)

**Comment by abhi0504** [comment]
@chrisbobbe can I work on this issue ?

**Comment by abhi0504** [comment]
@chrisbobbe , Actually what is happening that when you change the orientation from portrait to landscape and typed let say for eg "chat.zulip.org" or you typed an invalid URL and presses GO Button ( which is also available in the keypad in the portrait mode ) then it is also working but this time behind the keypad as in landscape mode the keypad covers the whole screen of mobile so we are not able to see the action behind the keypad but it is there .

![WhatsApp Image 2021-01-07 at 11 25 40 PM](https://user-images.githubusercontent.com/56453541/103926979-aea88000-513f-11eb-82c0-40d8b5dcd576.jpeg)

In different devices there are different keypads available In some keypads there is only an icon of "GO" in some device "GO" is represented by icon(as in your case).

Also you can verify this thing by entering chat.zulip.org as URL or any URL or leave it blank then change your orientation from portrait to landscape and press "GO" button and now when you again comes back to portrait mode then see the expected result of the action—either an error message like "Cannot connect to server" if I entered an invalid realm, or the auth screen for a valid realm. 

## **FIX** 
In my opinion this can be easily fixed by just changing the behavior of this "Go" button by "OK" by this when we press the "OK" button then instead of submit of form our keypad will be closed and then we can press "ENTER" button to enter in realm

**Comment by chrisbobbe** [comment]
Probably the thing to try is to not offer that full-screen input UI in the first place. I think that's what the [`disableFullscreenUI`](https://reactnative.dev/docs/textinput#disablefullscreenui-android) is for? I'm going to try that.
