### ISSUE TITLE
The avatar of the user doesn't show on MainTabs of iphone 

### ISSUE THREAD

**Issue by Gautam-Arora24** [zulip/zulip-mobile#4431]
**Unexpected behavior**
The avatar of the user doesn't show up in the MainTabs of the Zulip mobile. This is a serious bug that needs to be fixed.

**Screenshot of the app on iPhone 12**
![Screenshot 2021-01-25 at 12 49 05 AM](https://user-images.githubusercontent.com/53913514/105641390-a2475580-5ea9-11eb-8b15-f3ca870343b4.png)

**Xcode Version** -> 12.3 (12C33)
**Device** -> iPhone 12
**iOS** -> 14.3

**Comment by abhi0504** [comment]
@Gautam-Arora24 I think this issue is only in ios as I have tried it in my android emulator its working fine 
![Android Emulator - Pixel_3_API_29_5554 25-01-2021 13_04_13](https://user-images.githubusercontent.com/56453541/105674944-495dd880-5f0e-11eb-8c57-8cda82c923c1.png)

**Comment by Gautam-Arora24** [comment]
Yes @abhi0504 This issue is only popping up on iOS devices. I have also checked on android simulator and it works fine there

**Comment by chrisbobbe** [comment]
Hello! Thanks for the report.

So far, the bug seems consistent with #4365, which we believe was fixed just last Thursday in bcc135691, from #4420. Could you please pull the latest `master` (if you haven't already) and see if the problem persists there?

If it does, here are some questions that should help us further debug:

- What version of iOS is running in the simulator?
- Can you see any avatars in the app?
  - If so, where do you see them? Do you see them for some users and not others? Do you see them in the message list but not outside it?

**Comment by Gautam-Arora24** [comment]
The bug still persists with the latest code. 
Device -> iPhone 12
iOS Version -> 14.3

**Comment by gnprice** [comment]
Hmm, fascinating. Thanks for the report!

Over on #4365, we found that this didn't appear when using Xcode 11. I currently use Xcode 11 for making releases, which means this doesn't yet affect most users. But... I only have the one Mac, so I can't upgrade to Xcode 12 without making this bug live for the next release, which makes this trickier because I can't reproduce the bug myself.

@Gautam-Arora24 Can you try the further debugging questions Chris mentioned above? That'll help us narrow this down.

**Comment by Gautam-Arora24** [comment]
Thank you @gnprice. One piece of feedback from my side is that I can see the avatars of the user only in the message list and nowhere else.

**Comment by chrisbobbe** [comment]
Linking to discussion on [CZO](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Avatar.20missing.20on.20Iphone/near/1106005); probably best to continue debugging in one place (there). 🙂

**Comment by Gautam-Arora24** [comment]
I think building the app from scratch on iPhone solved my problem.
