### ISSUE TITLE
iOS: font size change only detected at launch

### ISSUE THREAD

**Issue by feorlen** [zulip/zulip-mobile#444]
If I change my dynamic type font size while the app is running, the font stays the same until the next launch. Only then does it reflect the new size. For native apps, you know this happens if you listen for UIContentSizeCategoryDidChangeNotification, not sure how it should work here.

https://developer.apple.com/reference/uikit/uicontentsizecategorydidchangenotification

**Comment by gnprice** [comment]
I happened to try changing the system text size on iOS the other day while the app was running. On the message list screen (where I was), the text in the app bar correctly responded. So something we've done in the past 14 months probably fixed this issue.

I'll open a separate issue for the message text, as that's probably unrelated to whatever made this not work in general when this issue was originally filed. (The message list wasn't even a webview back then.)

Closing this issue. If there are other areas where we still don't respond, an updated specific bug report on that would be very welcome!
