### ISSUE TITLE
Display problem in the "@" icon on the home screen

### ISSUE THREAD

**Issue by blinry** [zulip/zulip-mobile#4521]
On version 27.159 of the Android app (latest version from the Play Store), and on Android 9, the "@" icon in the top bar has a display problem where the path is not filled with color where it's self-intersecting:

![](https://user-images.githubusercontent.com/81277/110769914-fdb28480-8258-11eb-9109-ae1eb1c502d5.png)

Can other people reproduce this? I've been noticing this for a while. I don't know enough about the involved technologies to fix this myself –  it might be an upstream issue with react-native-vector-icons, or just a setting to say that the [fill-rule](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule) of the SVG should be "nonzero" instead of "evenodd"?

**Comment by Gautam-Arora24** [comment]
Seeing this issue on iOS as well. 
My iOS version - 14.3

**Comment by chrisbobbe** [comment]
Thanks for the report, @blinry, and for confirming on iOS, @Gautam-Arora24! Good to have an issue for this in the tracker.

@WesleyAC has debugged this and filed oblador/react-native-vector-icons#1311. Once that fix lands upstream and we can take a new release with it, it should resolve.

**Comment by WesleyAC** [comment]
Honestly, it might be good to just revert RNVI to the previous version until they fix this, since it's been several weeks since I filed that PR, it could be sitting there for quite a while. I don't *think* there are any cutting-edge features we need, although I haven't looked closely. Looks like `6.4.2` was the last version to not have this issue, we're on `^8.0.0`.

**Comment by Gautam-Arora24** [comment]
But moving back to ```6.4.2``` will cut many features for us which may be important.

**Comment by WesleyAC** [comment]
Looking at the commit log for all the upgrades, I think #2209 is the only thing that would revert. And personally, I'd rather have #2209 than this, but maybe there are features that we rely on in upgrades that weren't mentioned in the commit log.

**Comment by Gautam-Arora24** [comment]
Here how it looks on an iPhone Simulator. Certainly, the @ symbol is empty and the path is not filled
![Screenshot 2021-03-16 at 10 02 46 PM](https://user-images.githubusercontent.com/53913514/111345490-593ea100-86a3-11eb-9c1c-49b58644b928.png)

**Comment by chrisbobbe** [comment]
> Looks like `6.4.2` was the last version to not have this issue, we're on `^8.0.0`.

I've just tried out 6.4.2, and I don't observe the issue there, on my iPhone. However, I also tried out 6.5.0, and I don't see the issue there either. @WesleyAC, what led you to 6.4.2? 🙂

**Comment by chrisbobbe** [comment]
> So, after also testing on Android, I'll plan to take us back to 7.0.0, and file an issue in our tracker to track the resolution of oblador/react-native-vector-icons#1311 and upgrade when we can.

Just sent #4538 for this.

**Comment by WesleyAC** [comment]
Ah, I was assuming that [7ddcb4b8](https://github.com/oblador/react-native-vector-icons/commit/7ddcb4b842843b8e10cba6b19b9b4442e03faa44) introduced the bug, since that started using fontcustom and updated `Feather.ttf`, but it looks like it was actually that later commit that you identified. Your revert looks good to me, thanks :)
