### ISSUE TITLE
Reacting with "0️⃣" results in "Invalid emoji name" error

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4546]
If you try to react with the "0️⃣" (`:0:`) emoji on CZO, you get the following error:

```
[Thu Mar 18 2021 17:55:58.353]  LOG      {"httpStatus": 400, "json": {"code": "BAD_REQUEST", "msg": "Invalid emoji name.", "result": "error"}, "params": {"body": "reaction_type=unicode_emoji&emoji_code=0030-20e3&emoji_name=0", "method": "post"}, "route": "messages/1135041/reactions"}
[Thu Mar 18 2021 17:56:00.388]  WARN     Possible Unhandled Promise Rejection (id: 3):
Error: Invalid emoji name.
```

We should fix this, and add an error toast on a 400 response (currently there is no feedback given to the user about why this failed)

**Comment by WesleyAC** [comment]
Ok, filed a PR to show a toast when there's an error.

As for the thing with `:0:` — the app is trying to add `:0:`, but the server only responds to `:zero:`. I think this is because we ship a `src/emoji/codePointMap.js` file that's gotten out of sync with the server version of that file? But I'm not sure how that works overall.

**Comment by WesleyAC** [comment]
@gnprice let me know if you have context on what's going on here, otherwise I'm happy to investigate further.

**Comment by gnprice** [comment]
Indeed, good find! As I mentioned [in the chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/near/1135688), this (well, "Invalid emoji name" in general) turns out to be an error that users are regularly hitting.

We have an old issue #3128 which describes this, so I'll close this one and add an update there, to consolidate threads.
