### ISSUE TITLE
Server URL Input should not be scrollable

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#458]
![ezgif com-video-to-gif 12](https://cloud.githubusercontent.com/assets/18511177/24311101/ae057468-10f8-11e7-8ffd-3ea7748b93fe.gif)

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Good catch! Also worth checking all other input controls for the same issue.

**Comment by synicalsyntax** [comment]
Hello @vishwesh3, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by vishwesh3** [comment]
Same issue with `email` input field in the `Sign in` page.
