### ISSUE TITLE
Android app gets stuck connecting for 3 or 4 minutes

### ISSUE THREAD

**Issue by ChrisDenton** [zulip/zulip-mobile#4648]
When I open the Zulip andoid app and connect to `rust-lang.zulipchat.com` it takes three or four minutes to connect. I literally have to leave the app open and wait for it to connect otherwise it will be stuck. This only affects the initial connection. Thereafter it works fine,

The website works without issue.

**Comment by chrisbobbe** [comment]
Hi, @ChrisDenton, I'm sorry for the delay in responding. Are you still seeing this issue?

A few questions to help debug:
- What version of the mobile app are you on when you experience this issue?
- What do you see during those three minutes; is it the full-screen loading spinner?
- Can you say more about how it only affects the initial connection? Have you run into the issue more than once?

**Comment by ChrisDenton** [comment]
I'm no longer seeing this issue but I could reproduce it consistently at the time.  I just had to close the app and reopen it. It got to the unread messages screen and had "connecting" at the top. And it stayed that way for minutes before the new messages were actually loaded. I'm sorry but I didn't note the version.

As I say, I'm unable to reproduce it now so feel free to close this issue.

**Comment by chrisbobbe** [comment]
> I'm sorry but I didn't note the version.

That's OK! 🙂 From the date on your post here, looks like it would have been [v27.161](https://github.com/zulip/zulip-mobile/releases/tag/v27.161) (released April 2) or earlier.

Thanks for those details, and I'm glad you're not seeing the issue anymore. I'll keep your experience in mind while working on #4165; I've got a pull request (#4193) in progress for part of that.

Again, my apologies for not responding sooner. I regret missing the opportunity to get to the bottom of this and fix it while it was happening.

I'll close this particular issue, since you've said it's not happening anymore, but please don't hesitate to open a new issue with other problems you run into (or if you see this one again), or come say hello in the `#mobile` stream on chat.zulip.org, our [community server](https://zulip.readthedocs.io/en/latest/contributing/chat-zulip-org.html).
