### ISSUE TITLE
Unhandled Zulip API event: type: "attachment"

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4687]
When uploading an image, I see the following error in the log:

```
[Wed Apr 21 2021 23:16:26.796]  ERROR    Unhandled Zulip API event
[Wed Apr 21 2021 23:16:26.844]  ERROR        type: "attachment"
    op: "add"
    attachment: {"id":22548,"name":"Screenshot_20210421-231422.png","path_id":"2/16/aNNbCWo8ptgK6y-FfP6mYEB8/Screenshot_20210421-231422.png","size":148949,"create_time":1619018185000,"messages":[]}
    upload_space_used: 10630145314
    id: 12
```

There's no user-visible impact, as far as I can tell, but we should figure out what's causing this and what the correct fix is.

**Comment by chrisbobbe** [comment]
Looks like that's this event: https://zulip.com/api/get-events#attachment-add

Since we get a new-message event when there's a new (attachment-containing) message, and we get an update-message event when there's an updated (attachment-containing) message, I can't think of a live-updating bug that might come from this.

Maybe if we were keeping and relying on a data structure specifically for attachments, there would be such a bug?

**Comment by timabbott** [comment]
That event is intended for UI on the "Uploaded files" settings page so I'd expect mobile to not want to request it.
