### ISSUE TITLE
Enable fetching more search results

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#4859]
At present, we fetch the 20 most recent search results, and do not provide a way for the user to get more. This can lead to a bad experience when the user is looking for an older message. We should:

1. Fetch additional search results when the user scrolls up from the search results that have already been fetched.
2. Consider fetching more results (100?) in the first place, as 20 is quite low when the query is not very specific.

**Comment by gnprice** [comment]
The implementation of this will require some refactoring and be a bit tricky.

For the message list in all cases other than search, we get the messages from our global Redux store, and the way to fetch more is to go and do a fetch that puts the results into the global Redux store. So that's what the `fetchMore` function in `src/webview/handleOutboundEvents.js` does, dispatching a `fetchOlder` or `fetchNewer` thunk action.

But in the case of search, the list of messages isn't in the global Redux state; instead it's in the local state of the `SearchMessagesScreen` component. We do that because, especially with search-as-you-type causing lots of searches, we don't want to be keeping around indefinitely the results of all the different searches you've done.

As a result, in order to fetch more messages and have them show up in the list, we need to do a fetch that will put the results into that screen's local state.

The first step we'll need for this is to wire things up so that the parent of `MessageList` passes in a pair of callbacks to tell it how to fetch more messages. These can probably just be props called `fetchOlder` and `fetchNewer`, and then in `handleOutboundEvents.js` we'll have
```diff
-    dispatch(fetchOlder(narrow));
+    fetchOlder();
```
and similarly for `fetchNewer`.

That step should be a pure refactor with [no functional change](https://github.com/zulip/zulip-mobile/blob/cf8f1a841dc27f2ba1bf32513e886a299f340822/docs/glossary.md#nfc-or-nfc); in the search case we can pass no-op callbacks for those props.

Then, we'll want to implement those callbacks for search. This will interact with the other state on `SearchMessagesScreen`. Here's some thoughts on that:
* The existing state structure has some trickiness because the query whose results we're showing isn't necessarily the latest one the user entered, if that latest one hasn't yet gotten a response or didn't succeed.
* We should be sure we never end up showing a mixture of results from one query and results from another.
* On scroll, the query we fetch more messages for should probably be the one we're currently showing messages for. That means we should start remembering what that query was, with a state property like `query: string` that we update at the same time as `messages`.
* Then when the fetch-more-messages callback gets a response from its fetch, it needs to check that the query it used is still the current one. If not, it shouldn't store the messages, and can just return.
* I think the fetch-more-messages callback doesn't need to interact with any of the `lastIdSuccess`, `lastIdReceived`, `lastIdSent` state; I think it can just pay attention to what the current query is.
