### ISSUE TITLE
Search only on submit, not as you type

### ISSUE THREAD

**Issue by AkashDhiman** [zulip/zulip-mobile#4964]
Currently search is triggered on text change, however it doesn't work on prefixes and so it doesn't make much sense to have it work this way. Rather a better approach would be to trigger search on submit. This will simplify the work on fetching more on search.

We can perhaps revert back to this once the searching algorithm is changed.

**Comment by gnprice** [comment]
> We can perhaps revert back to this once the searching algorithm is changed.

I think the search backend's behavior is pretty good in this respect -- I think there wouldn't actually be that much to be gained by making it operate on prefixes so that we can do search-as-you-type. (It'd also require a pretty fundamental overhaul of the search engine; you need completely different data structures to do prefix search efficiently vs. whole words, as it currently does. And the search engine is something we get built into Postgres and didn't write ourselves, so even a small change to its internals would be quite a significant investment.) So I don't think that backend change is likely to happen.

Another benefit of this client-side change, besides making the UX align with the backend's design, is that it opens up space in the UI for search suggestions, #4916.
