### ISSUE TITLE
New Bug: Replying to last message in a stream makes new topic "(no topic)"

### ISSUE THREAD

**Issue by maltokyo** [zulip/zulip-mobile#4999]
The previous version on my phone (both ios and android) behaved in this way:

Go into stream, and it shows all topics in the stream. Read them all. Hit reply. It used to take the last topic from the stream, and default that into the reply.

Now, when you do the same thing in the latest mobile app, it DOES NOT default to the last topic upon reply, it rather makes a new topic called "(no topic)", which I (and my users) find really frustrating, resulting in us having to edit the message, and go fishing for the last topic that we thought we are responding to.

Is it possible to get this topic defaulting back? A topic is better than "no topic"

The web view behaves correctly. For example, when I am in the [#mobile stream](https://chat.zulip.org/#narrow/stream/48-mobile) of chat.zulip.org and hit reply at the bottom, it correctly takes the topic of the last message as my topic.

The discussion is ongoing here: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.3A.20Replying.20to.20last.20message.20in.20a.20stream

**Comment by gnprice** [comment]
Thanks @maltokyo for the report!

This behavior was introduced in v27.169, and fixed in v27.170: we now focus the topic input first, so that you pick a topic before composing the message, just like in the web app.

Details on the changes are in @chrisbobbe's message here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.3A.20Replying.20to.20last.20message.20in.20a.20stream/near/1255035

I've just started the rollout of v27.170 to all users (it was in beta since late last week), so you and your colleagues should get it shortly.
