### ISSUE TITLE
Move compose box buttons into a row below the compose box

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5080]
At present, compose box buttons are accessed via a "plus" symbol to the left of the compose box. Clicking on "plus" expands the buttons on the same line as the compose box. This works OK with the buttons we currently have, but is likely to no longer look good as we start adding more buttons (#3427, #5079).

We should try moving the row of buttons below the compose box. We may need to play with the UI to make sure the interactions feel natural, but we can try the following approach:

1) Putting the cursor into the compose box automatically opens a row of buttons below the compose box. Moving the cursor away from the compose box closes the buttons row.
2) Clicking on "plus" when the cursor is not in the compose box also automatically opens a row of buttons below the compose box.

This issue may be a blocker for #3427 and #5079. It's possible we can implement one of those without this issue, but not both.

[Discussion thread on CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/user.20feedback/near/1270607)

**Comment by chetas411** [comment]
So I have two approaches, either I pull out the row of buttons part from the composeMenu component and make it a separate component ans use two version of the menu separately or the other way is I add more states in composeBox component and add some logic so that theere remains only single component i.e. composeMenu and I add some logic via props that renders 2 versions on basis of conditions of props. Which one to move forward with?

**Comment by alya** [comment]
Agreed, the "plus" button should disappear when the buttons are expanded.

**Comment by chetas411** [comment]
https://user-images.githubusercontent.com/65273718/140638602-70840fe0-7699-4dcb-863d-b5ce5a84cf89.mp4

**Comment by chetas411** [comment]
>  Google.Pixel.4.emulator.zulip.testing.mp4

do we want something like thsi @alya @chrisbobbe ?

**Comment by alya** [comment]
For the most part, that looks good to me!

I think we need to change the "collapse" (`<`) button, since it no longer has icons to the right of it in the new design. Perhaps just changing it to a `^` would work?

**Comment by chetas411** [comment]
> For the most part, that looks good to me!
> 
> I think we need to change the "collapse" (`<`) button, since it no longer has icons to the right of it in the new design. Perhaps just changing it to a `^` would work?

I have inlcuded the change suggested by you @alya. Please review the PR.

**Comment by chetas411** [comment]
@chrisbobbe can you review the latest PR ?

**Comment by chrisbobbe** [comment]
> 1) Putting the cursor into the compose box automatically opens a row of buttons below the compose box. Moving the cursor away from the compose box closes the buttons row.
> 2) Clicking on "plus" when the cursor is not in the compose box also automatically opens a row of buttons below the compose box.

What use cases does (2) answer that (1) doesn't? After looking at those videos (thanks @chetas411!) I'm thinking we may not need a button at all, and we can just do (1).

- I think it's simpler to have just one way to toggle than two. And (1) is maybe more appropriate than (2), since the row gives tools for composing a message, and composing a message is something you're only doing when the message input is focused.
- If we remove the button, the input elements can get wider to fill the space where the button was. Wider input elements means a better compose experience. You can see more of your text on the screen at a time.

@alya, thoughts?

**Comment by alya** [comment]
If you look at other apps, they do have a `+` button that can be used to attach files/pictures/etc. I think the idea is that the user's mental model might be not, "I want to compose a message", but "I want to send a picture," and in that case putting the cursor into the compose box is not a natural starting point.

**Comment by chetas411** [comment]
@alya @chrisbobbe so is this change fine or any further changes required for this issue ?

**Comment by chrisbobbe** [comment]
> If you look at other apps

@alya which apps are you thinking of?

I've just looked at Slack on iOS and Android, and it looks like on both platforms they use an approach like I described in https://github.com/zulip/zulip-mobile/issues/5080#issuecomment-972076840. They have a row of buttons under the message input, and you show or hide the row just by moving the focus in and out of the message input; there isn't a button for doing that. The row of buttons itself has a plus button, but that doesn't hide/unhide the row; it brings up a sheet that offers options that wouldn't fit in the row.

Here's a video of what I'm seeing: https://user-images.githubusercontent.com/22248748/142944344-89129d6a-aede-47a1-a94c-c7317913f18d.mp4

1. Message input is unfocused, row is hidden
2. I focus the input, row appears
3. I tap the `+` button in the row, it brings up a sheet with additional options
4. I close that sheet
5. I unfocus the input by scrolling a bit in the message list, row hides

> I think the idea is that the user's mental model might be not, "I want to compose a message", but "I want to send a picture," and in that case putting the cursor into the compose box is not a natural starting point.

Hmm, maybe. I wonder if encouraging this mental model is a side effect of a bug, though: #4540. Currently, we have some buttons that act like send-image buttons, but they're really supposed to be attach-image buttons. Currently, once you select or capture a photo, the app takes a shortcut where it makes a new message with just the markdown for the photo and sends it right away, before you have a chance to edit it. That's annoying, and maybe scary, too, if you tap/send the wrong image by mistake and you don't know how to [delete uploaded files](https://zulip.com/help/manage-your-uploaded-files) or you don't do it fast enough. People who use the web app, or the edit-message feature in the mobile apps (or a future view-message-source feature on mobile), will be used to dealing with images as markdown, and I predict most of them will be relieved to have #4540 fixed.

And with it fixed, so that the buttons are proper "attach" buttons that don't send anything (they just act on the message-input text by adding a bit of markdown), I think putting the cursor into the compose box might be a natural starting point for using the buttons.

**Comment by alya** [comment]
Hmm, what I had in mind is that Slack and Discord (on Android) *always* show the "+" button, even when no other formatting buttons are visible.

Perhaps we should discuss on CZO?
![Screenshot_20211122-150249_Slack](https://user-images.githubusercontent.com/2090066/142948136-8dbe7e4d-dced-41dd-bd18-4ee73e1e847e.jpg)
![Screenshot_20211122-150327_Discord](https://user-images.githubusercontent.com/2090066/142948143-9fe931b0-9e66-437e-b9d5-81a035cf3858.jpg)

**Comment by chrisbobbe** [comment]
> Perhaps we should discuss on CZO?

Sure: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M5080.20Move.20compose.20box.20buttons.20into.20a.20row.20below.20the.20compose/near/1285321

**Comment by alya** [comment]
Ok, based on the discussion in the CZO thread linked above, let's limit this issue to just the first part:

> Putting the cursor into the compose box automatically opens a row of buttons below the compose box. Moving the cursor away from the compose box closes the buttons row.

**Comment by chetas411** [comment]
> Ok, based on the discussion in the CZO thread linked above, let's limit this issue to just the first part, without changing the functionality for `+`:
> 
> > Putting the cursor into the compose box automatically opens a row of buttons below the compose box. Moving the cursor away from the compose box closes the buttons row.
> 
> The `+` should disappear when the cursor is in the compose box.

So should I make functionality for `+` button same as before or is this fine as well because anyhow  #5141 will gonna change it again ?

**Comment by alya** [comment]
For this PR, we should make the functionality for the `+` button as before when it is shown. We want to make this PR mergeable separately from #5141, and that will be the way to do that.

Thanks!

**Comment by chetas411** [comment]
@alya I have made the changes proposed by you,  can you review ?

https://user-images.githubusercontent.com/65273718/143764414-27ca420c-ff93-41c1-acc2-cb514cb424e1.mp4
