### ISSUE TITLE
Keyboard issue on the "New PM" screen

### ISSUE THREAD

**Issue by plankt3r** [zulip/zulip-mobile#5185]
Pressing the "New PM" button leads to a screen listing all the users. Once there, you can pick a user and send them a message. For some reason, the keyboard pops up immediately when you land on that page, covering part of the screen. Logically, it should only appear once you have selected a user and activated the compose box, as is implemented on the "New group PM" screen.

See in CZO: [#**mobile>keyboard issues** ](https://chat.zulip.org/#narrow/stream/48-mobile/topic/keyboard.20issues/near/1303350) 

<img src="https://user-images.githubusercontent.com/69382070/148041913-e664a0b7-96c7-4057-a16d-ed3c9fb437cc.jpg" width="200">

**Comment by thisisnitish** [comment]
@chrisbobbe!, Could you please assign this issue to me. I want to work on it.

**Comment by chrisbobbe** [comment]
Sure! First, would you mind describing your plan for how to solve the issue? Thanks!

**Comment by thisisnitish** [comment]
Sure @chrisbobbe!,

* First, if you move to the users screen, where you see users list. That screen contains a search input.
* That input is already focused. The reason for this is, this screen is using `Screen` component as a wrapper and it has one prop name `autoFocus` and it is `true` as of now. But if we change it to `false`, then this bug can be fixed.
* The reason is, as soon as the screen loads, that input should not be focused so, the keyboard will also not appear.
* Now, once you make `autoFocus` is false or just remove that prop. You will see, that input box will not already focused as the screen loads, so that keyboard will also not appear. It will only appear, when you tap on the search input.

I hope you got the idea.
Thanks 😊

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I'll try to finish this asap 🙂

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I've raised the PR. Please review it. Thanks 🙂
