### ISSUE TITLE
Not Showing any alert if stream name already exist.

### ISSUE THREAD

**Issue by sumj25** [zulip/zulip-mobile#5199]
If I create a stream with the existing name then it shows no alert. Here's a web app behavior-

![Screenshot from 2022-01-21 00-52-35](https://user-images.githubusercontent.com/59159432/150412597-23c9d97e-4bc2-4bfd-9e5e-8dee8b2f4864.png)
-
We can do something sort of like this. see[CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Not.20showing.20any.20alert.20if.20stream.20name.20already.20exist)

**Comment by vaidehi44** [comment]
Hey @sumj25, can I work on this?

**Comment by sumj25** [comment]
Hi @vaidehi44 , yes you can work on this issue.

**Comment by vaidehi44** [comment]
Okay. Thanks.

**Comment by thisisnitish** [comment]
Hey @alya, I would like to work on this issue. Thanks 😊

**Comment by thisisnitish** [comment]
Hey @alya The plan is like this,

* We have `CreateStreamScreen`..right??. In that, file we have one function called `handleComplete`.
* In `handleComplete` we are calling `createStream` from api inorder to create a stream.
Now, the solution is:
* Before using `createStream` api I will be checking whether the stream by this `name` is already present or not?
* In order to do this, we will be using `getStreamsByName` selector and will iterate over the keys to check is stream name is already present or not. If yes, then show the alert msg other proceed further.

**Below is Preview of my idea:**

https://user-images.githubusercontent.com/48220369/162491893-baf05475-405d-49ec-b305-7a323bb7fb22.mp4

**Comment by Fingel** [comment]
Hi @thisisnitish 
This is a good plan. There might be a better way though. Currently when you try to create a stream with a name that already exists, the server probably responds with an error. But the mobile app does not handle it correctly. Maybe what we should do is handle the error properly, and display it to the user. This way there are more cases we can cover. For example, there might be a blacklist of stream names that are reserved or cannot be created - so checking the server response would work for that case as well.

**Comment by thisisnitish** [comment]
Hi @Fingel 
You are right, the first thing that came to my mind is the same thing you said. So looked into the code where we are using the api and found that, we aren't handling any responses there. So, I looked into the Zulip API docs specifically for creating a stream [here](https://zulip.com/api/create-stream). When you will go to this URL it will suggest you to go on subscribe stream page where you will create a stream.

And, I checked on subscribe stream page, the response that URL returns, but there was no such response which is of our desired result. 
So, I thought my proposed plan might be the better idea.
Thanks 😊

**Comment by Fingel** [comment]
I see. It's actually a subscribe request that happens when you create a new stream. So when you try to create a new stream with an existing name, the response lets us know that the user is already subscribed:
​​```json
{
  "result": "success",
  "msg": "",
  "subscribed": {},
  "already_subscribed": {
    "user9@zulipdev.com": [
      "devel"
    ]
  }
}
```

We could do something with that. Where it gets kinda wacky is if you are unsubscribed from a stream, but then try to create a new stream with the same name. You won't get an error, but you'll be subscribed to the existing stream:

```json
{
  "result": "success",
  "msg": "",
  "subscribed": {
    "user9@zulipdev.com": [
      "devel"
    ]
  },
  "already_subscribed": {}
}
```
Which is indistinguishable from the response you get when you do create an entirely new stream:
```json
{
  "result": "success",
  "msg": "",
  "subscribed": {
    "user9@zulipdev.com": [
      "new_stream"
    ]
  },
  "already_subscribed": {}
}
```

Not super intuitive, but we should definitely be doing something here to better handle these responses.

**Comment by thisisnitish** [comment]
I've checked the responses we are getting from `createStream` api I found something.

* When there is already exist a stream then we get response something like:
<img width="591" alt="Screenshot 2022-04-08 at 11 51 07 PM" src="https://user-images.githubusercontent.com/48220369/162499985-84dd9d3c-1a9c-4b55-a789-955be09ad0fe.png">

That means we have already subscribed to the stream.

* But, if we stream. doesn't exists, then we get the response like this:
<img width="592" alt="Screenshot 2022-04-08 at 11 53 06 PM" src="https://user-images.githubusercontent.com/48220369/162500097-8fceffa4-5edd-4144-a4dc-9a3648f6f93f.png">

I think we can probably check if the object `already_subscribed` is empty or not. If it is empty then we should show the alert otherwise proceed further.

**Comment by thisisnitish** [comment]
Now, I'm using the response that we get from `createStream` api and checked if the user has already subscribed to the stream then show the alert otherwise proceed further.

**Below is the preview:**

https://user-images.githubusercontent.com/48220369/162519999-0572b816-da11-485b-abd3-6cea8869f45c.mp4

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!, I've added my updated plan here. Please have a look at that. I feel this is the correct way. Thanks 😊

**Comment by chrisbobbe** [comment]
Thanks, @thisisnitish! Let's continue the discussion on CZO, [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M5199/near/1362991).

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!, I've raised the PR. Please have a look at that #5331.

Also, I've tried to cover all the cases:
**Case 1:**
When we try to create a stream with an existing name and we are subscribed to the stream.
https://user-images.githubusercontent.com/48220369/162564979-350948d7-88d4-40ea-b101-52a778860307.mp4

**Case 2:**
When we try to create a stream with an existing name and we aren't subscribed to the stream.
https://user-images.githubusercontent.com/48220369/162565009-4ebfa0ad-452f-4a9d-8148-9d2e102b690c.mp4

**Case 3:**
When we try to create a stream with new name.
https://user-images.githubusercontent.com/48220369/162565043-36d55d06-9065-4cff-887f-7f9c5f0bd572.mp4

Thanks 😊
