### ISSUE TITLE
Make it possible to resolve/unresolve a topic

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5202]
At present, it's not possible to resolve/unresolve a topic from the mobile app. For parity with the webapp (https://github.com/zulip/zulip/issues/18751), we should make it possible to resolve/unresolve a topic from the long-press topic menu.

CC @gnprice for any comments on the implementation plan.

**Comment by gnprice** [comment]
I think the main work that will be needed for this is actually to fix a couple of longstanding gaps in how the mobile app handles when messages have their topic (or stream) edited:
* #2688, which is an outright bug
* When you're looking right at a conversation and it gets moved, we should change your current narrow to follow along. We don't seem to have an existing issue for this; I'll go file one.

While those gaps are present, if we do have some UI for resolving/unresolving a topic the experience is going to feel pretty broken: before #2688 is fixed, you'll still be looking at the old version of the topic and the messages won't have gone anywhere (because even though they have on the server, the bug #2688 means we don't reflect that.) And then with that but before the other thing is fixed, you'll still be looking at the old version of the topic and will see the messages disappear from there.

These are also important on their own for the experience of just reading while other people are resolving/unresolving topics.

Then once those are fixed, I think it will be fairly straightforward to add an option in the UI to resolve/unresolve a topic. See src/action-sheets/index.js for where that UI goes; and for how the logic should work, see web's `message_edit.toggle_resolve_topic`.
