### ISSUE TITLE
Build fails under Java 15

### ISSUE THREAD

**Issue by Mihir3** [zulip/zulip-mobile#5288]
When I tried to build the Zulip app on Android Emulator (Pixel 4 Google Play) via Android Studio on macOS Monterey (v 12.0.1) in Java 15 (OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)) and Gradle 6.9  with command :

`(base) mihirpamnani@Mihirs-MacBook-Air zulip-mobile % tools/run-android`

I ran into the following issue : 

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-photo-view:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
````

And as I mentioned in a comment on #5229 : 

Looking up online, I found this comment on an old Github thread discussing the above issue :
https://github.com/alwx/react-native-photo-view/issues/189#issuecomment-911496526

which led to a suggestion to install postinstall Jetifier to provide support in :
https://github.com/facebook/react-native/issues/25483#issuecomment-508446776

And after installing Jetifier in the project as mentioned in the above comment, I ran the command `tools/run-android` again and it resolved the compilation issue and built the app successfully.

Later, @gnprice pointed out that it is unnecessary to install Jetifier as there already exists a postinstall script in package.json doing the same work as Jetifier : 
https://github.com/zulip/zulip-mobile/blob/11cbbd15b97fcd42964a8b8fc362401f1a708381/package.json#L6

Hence, now it is unclear why the existing postinstall didn't work or execute in resolving the compilation issue.

**Comment by gnprice** [comment]
Thanks for the report!

It looks like Java 15 is no longer supported upstream:
https://adoptium.net/support/
https://adoptopenjdk.net/support.html#roadmap

So I think we are not going to try to dig into this and resolve it; instead, our recommendation is to switch to a supported version of Java.

Java 11 is a good choice, because it's an LTS release and will be supported for the next two years. Java 17 is the next LTS after it, and will be a good choice once we resolve #5229.
