### ISSUE TITLE
Topic autocomplete missing part of touch target on iOS

### ISSUE THREAD

**Issue by namse** [zulip/zulip-mobile#5486]
Hi. Very recently when I tab the topic, it just ignores my input. 

https://user-images.githubusercontent.com/3580430/189909332-9ae3b1b7-92c6-46ae-918c-0b90feade433.MOV

I'm not sure why it happened.

**Comment by namse** [comment]
I found that it only happened when I click left side of topics. I guess maybe resolved mark area makes some trouble. 
 ![image](https://user-images.githubusercontent.com/3580430/189910608-ed85915b-fcde-459f-b657-05071b28531c.jpeg)

**Comment by gnprice** [comment]
Thanks @namse for the report!

I reproduce the issue. Specifically:
* I see this on iOS (an iPhone 7 running iOS 15.6.1), but not on Android (a Pixel 4 running Android 12.)
* The symptom is: when I try to select a topic from that autocomplete popup by tapping somewhere near its left edge -- in about the region indicated by the red box in your comment -- it doesn't work. Instead, it behaves as if I'd tapped outside the popup entirely, to dismiss the whole compose box.
* On the other hand, if I tap anywhere else in the popup, it works fine -- the topic I tapped on gets selected.

I think the cause is not likely to be related to the resolved-topic checkmark. The symptom seems to be the same on topics that don't have that, and even when none of the topics in the list have it.

**Comment by gnprice** [comment]
OK, and with some further testing:
* I reproduce the issue on v27.191, the latest.
* I *don't* reproduce the issue on v27.190, the previous version.

We sent v27.191 to all users on 2022-09-08, a few days before this issue was filed. So that fits very neatly with the mention of it happening "very recently".

@chrisbobbe would you take a look at debugging this? I think the next step is to bisect to find where the regression happened (or if you have a guess as to what caused the issue, then to check that guess directly.)

**Comment by chrisbobbe** [comment]
It appears that the react-native-gesture-handler upgrade in that commit was a factor, by changing React Navigation's behavior so that it closes the keyboard for the swipe-right-to-go-back gesture at the moment you press the screen, instead of when you actually start swiping.

I expect a fix in [@react-navigation/stack 6.1.0](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%406.1.0), from commit https://github.com/react-navigation/react-navigation/commit/5a19877080bd406c5657a096f3c8cd5573316718. I did a quick manual cherry-pick of that commit (it's a one-line change) in node_modules at `main` and the symptom resolved.

Greg, do we think we could take that @React-navigation/stack 6.1.0 upgrade soon, or should we look at other options, like examining the reason for the gesture-handler upgrade for a possible revert, etc.?

**Comment by gnprice** [comment]
We just had [another report](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Reply-Topic.20Selection.20Quirk/near/1476724) of this issue.
