### ISSUE TITLE
Sent images include file extension in link text

### ISSUE THREAD

**Issue by shreyanjoshi** [zulip/zulip-mobile#5526]
It shows the file format of the images for no reason

**Comment by hackpk** [comment]
can i work on this ??

**Comment by hackpk** [comment]
@chrisbobbe i think @shreyanjoshi is talking about this 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/22720175/212850579-b645920f-b0e5-4984-9df1-30eb2e24da8f.png">
i have checked on android

**Comment by chrisbobbe** [comment]
I think it can be helpful to show the filename extension. Could you say more about why you think it's better to hide it than show it?

I noticed that the web app shows it. And in the following example I appreciate seeing ".gif" because it's a clue that the picture might move. I might act on that clue by clicking the preview to see the clip from start to finish. (In this case, it shows a recording of some mobile-app UI that I made when developing a feature.)

https://chat.zulip.org/#narrow/stream/7-test-here/topic/.E2.9C.94.20Chris/near/1491604

<img width="243" alt="image" src="https://user-images.githubusercontent.com/22248748/213016616-f47065a8-c07d-41e7-814c-fc0e8cd5b538.png">

I'd prefer to confirm that this is something the web app wants to do, before implementing it on mobile. Could you please ask a web-app maintainer in the `#frontend` stream of the [Zulip development community](https://zulip.com/development-community/)? Thanks!

**Comment by gnprice** [comment]
Closing for the reasons in @chrisbobbe's comment above.
