### ISSUE TITLE
Zulip Mobile Push notifications not working on iOS App

### ISSUE THREAD

**Issue by thefaizan** [zulip/zulip-mobile#5686]
I have setup and configured the zulip mobile apps successfully. I have also enabled the the central push notification service for production mode as per zulip's documentation. The push notifications work perfectly fine on android app but not on iOS app.

**Comment by alya** [comment]
@thefaizan  could you please drop by the [#mobile](https://chat.zulip.org/#narrow/stream/48-mobile) stream in the [Zulip development community](https://zulip.com/development-community/) so that we can debug this more interactively? I will close out this issue, as I don't think trying to help you here will work well. Thanks!
