### ISSUE TITLE
upgrade react native to 0.71

### ISSUE THREAD

**Issue by 2547409617** [zulip/zulip-mobile#5736]
I can not build with my box for react native version.

**Comment by gnprice** [comment]
Upgrading React Native is an investment we're unlikely to make in this legacy app. It's legacy because we're [upgrading to Flutter](https://chat.zulip.org/#narrow/stream/2-general/topic/Flutter/near/1582367) instead.

For cross-reference, here's the issue for what would be our next RN upgrade:
* #5428 

---

I don't understand what's meant by "with my box for react native version", but the app builds perfectly well if you [follow the instructions](https://github.com/zulip/zulip-mobile/blob/7b033bd508bb26eafb86a5f233aeb83b98af3de7/docs/howto/build-run.md). The `yarn install` step gets the appropriate versions of RN and all the other dependencies.

If you're having trouble, feel free to post an issue with details or ask in `#mobile` on chat.zulip.org, and we might be able to help. (Though given that we're now focused on the new Flutter app, we won't be able to spend a lot of time on it.)
