### ISSUE TITLE
Cannot connect to server from Bouygues mobile carrier

### ISSUE THREAD

**Issue by videlec** [zulip/zulip-mobile#5739]
A user of https://ultimatebegles.zulipchat.com has connection problems with the app.

- phone: Google pixel 6a
- OS: android v13
- zulip app version: v27.207

More precisely , when opening the app he sees the following hanging screen

<img src="https://github.com/zulip/zulip-mobile/assets/5619446/0c01241d-17a2-42a5-ad5f-5087c5f85b12" width=40% height=40%>

Might be similar to 
- #3618
- [Huawei P20 mobile app not connecting (on chat.zulip.org)](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Huawei.20P20.20mobile.20app.20not.20connecting)

**Comment by gnprice** [comment]
Thanks @videlec for this report! Sorry for the delayed reply.

From [the chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bouygues.20mobile.20network.20blocks.20zulipchat.2Ecom/near/1672138), the issue turned out to be that the mobile carrier Bouygues had for unknown reasons blocked access to zulipchat.com. Another Zulip user contacted Bouygues to ask them to fix that, and then things started working again.
