### ISSUE TITLE
move the topic box under the message box

### ISSUE THREAD

**Issue by abdeldjalil-fellah** [zulip/zulip-mobile#5755]
usually messages are sent to a default topic (no topic) so it would be more convenient to put the topic box under the message box,
by mistake I write the message in the topic box many times.

**Comment by gnprice** [comment]
Thanks for the feedback.

There are definitely things we can do to better avoid this sort of mixup. I think we will do some of those in our upcoming new app:
* https://github.com/zulip/zulip-flutter/issues/493
* https://github.com/zulip/zulip-flutter/issues/494

I don't think the specific solution of swapping the layout in this way will be something we do, though. It's the inverse of what Zulip web does and of how the messages appear after they're sent (where the topic always goes above the content), and I'm not particularly convinced it would make this issue better instead of worse.
