### ISSUE TITLE
FR: Support move message on Mobile

### ISSUE THREAD

**Issue by samtuke** [zulip/zulip-mobile#5760]
Outcome: Zulip users of Android app can move messages between topics and streams. E.g. using a "Move" option from the message context menu. 

Context: I do this on desktop app often, but see no option for it on Android app. I am an admin/moderator and often need to move other users' messages as well as my own. 

Using Android 27.211 and Server 7.3

**Comment by chrisbobbe** [comment]
Thanks for the feature request! This is tracked in #5165, so I'll go ahead and close this one as a duplicate. Please let me know if that seems wrong.

I think the most likely outcome is that we'll implement this in the [new Flutter app](https://github.com/zulip/zulip-flutter) rather than in the currently published app built in React Native. As part of the transition to that new app, we'll copy issues from this tracker into [that project's tracker](https://github.com/zulip/zulip-flutter), and that will include #5165.

**Comment by samtuke** [comment]
Appreciate the clear info, thanks @chrisbobbe
