### ISSUE TITLE
Show which topics are followed

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5770]
In the web app, we indicate followed topics with a dedicated icon (see [here](https://chat.zulip.org/#narrow/stream/101-design/topic/followed.20topic.20left.20sidebar/near/1647200)).

We should also indicate followed topics with an icon in the mobile app, in the Inbox view (probably the most useful placement), as well as the app bar in topic views and topic header bars.

**Comment by gnprice** [comment]
The mobile app is already tracking the data needed for this: `getTopicVisibilityPolicy` is the selector to get it from the state. So what's needed in order to do this is:
* Get the "followed topic" icon into our tree. (And the "unmuted" / "default visibility" / "muted" icons, if we want to show any of those?)
* Add it in the several places in the UI mentioned in the description above.
  * This may involve making some visual-design choices about precisely how to show it: how big, where, with what padding, etc.
