### ISSUE TITLE
Process 'command 'bash'' finished with non-zero exit value 127  

### ISSUE THREAD

**Issue by keke195** [zulip/zulip-mobile#5829]
I download v27.225 zip, yarn install and In Windows Git Bash Running a command like react-native run-android fails with an error like:

```
> Task :app:buildStaticWebviewAssets FAILED
32 actionable tasks: 3 executed, 29 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildStaticWebviewAssets'.
> Process 'command 'bash'' finished with non-zero exit value 127

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildStaticWebviewAssets'.
> Process 'command 'bash'' finished with non-zero exit value 127

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (D:\ASProject\zulip-mobile-27.225\node_modules\execa\index.js:174:9)
    at D:\ASProject\zulip-mobile-27.225\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\ASProject\zulip-mobile-27.225\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\ASProject\zulip-mobile-27.225\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
```

![1709523179309](https://github.com/zulip/zulip-mobile/assets/19198738/557de90d-2fb8-4662-b54f-8917bb30f181)

the Git Bash path has already  to be added to to PATH in the System environment，JDK version is 11,i have no idea ,please help me

**Comment by gnprice** [comment]
Have you installed rsync? See our notes for Windows setup:
https://github.com/zulip/zulip-mobile/blob/main/docs/howto/build-run.md#per-platform-notes

That's one issue that's tripped up several people when trying to build the app on Windows, and task `:app:buildStaticWebviewAssets` is the step it would fail at.

If you're having trouble setting that part up, this thread has the latest advice we know:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Execution.20failed.20for.20task.20'.3Aapp.3AbuildStaticWebviewAssets'.2E/near/1487513

Because this app is now in maintenance mode, though, as we build the new Zulip mobile app in Flutter, I'm afraid we won't be able to spend time helping debug.

(If this were a codebase we still intended to spend much time developing, we'd probably replace the `rsync` logic with something else — rsync works great, but setting it up has been a recurring pain for people on Windows, and we're not actually using it for that much.)

**Comment by keke195** [comment]
> Have you installed rsync? See our notes for Windows setup: https://github.com/zulip/zulip-mobile/blob/main/docs/howto/build-run.md#per-platform-notes
> 
> That's one issue that's tripped up several people when trying to build the app on Windows, and task `:app:buildStaticWebviewAssets` is the step it would fail at.
> 
> If you're having trouble setting that part up, this thread has the latest advice we know: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Execution.20failed.20for.20task.20'.3Aapp.3AbuildStaticWebviewAssets'.2E/near/1487513
> 
> Because this app is now in maintenance mode, though, as we build the new Zulip mobile app in Flutter, I'm afraid we won't be able to spend time helping debug.
> 
> (If this were a codebase we still intended to spend much time developing, we'd probably replace the `rsync` logic with something else — rsync works great, but setting it up has been a recurring pain for people on Windows, and we're not actually using it for that much.)

thanks，I fixed the problem  after  install rsync !

**Comment by gnprice** [comment]
Great, and thanks for confirming that solved it for you.

I've also just added an entry for this in the troubleshooting section of our instructions (93aeee9c6e376225071ff62705a453fb3de07a19), so hopefully that'll help the next person who runs into this to find the solution more quickly.
