### ISSUE TITLE
Support new settings for restricting direct messages

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5870]
We will need to support restricted permissions for sending direct messages as described in https://github.com/zulip/zulip/issues/24467. At a minimum, the mobile app should give a reasonable error when a user tries to send a message that they are not allowed to send.

(TBD whether this is a goal for 9.0.)

**Comment by gnprice** [comment]
> At a minimum, the mobile app should give a reasonable error when a user tries to send a message that they are not allowed to send.

Doing the best possible version of this UX approach (like, an error modal that appears synchronously after they hit the send button) might require more refactoring than we want to do for the legacy app, because currently our message sending happens from an "outbox" system that works at arm's length from the compose box.

For a solution for this issue, we'll want to keep simple the changes we make. So it'll be enough if we have the error message appear asynchronously, for example as a toast, when the outbox system eventually hits it.

**Comment by chrisbobbe** [comment]
> topic-based permissions for sending messages as described in https://github.com/zulip/zulip/issues/24467

That issue is about DMs; I don't find anything on the page about topics. Is this the right issue link?

**Comment by gnprice** [comment]
That server issue looks like it's making active progress, and it also matches this issue's title. So I think that is the one that's intended, and the mention of "topic-based permissions" in the description is a thinko for some other issue that presumably isn't an immediate priority. @alya, is that the right guess?

**Comment by alya** [comment]
Oh, sorry, that must be a copy-paste issue. Topic-based permissions are https://github.com/zulip/zulip/issues/19434.

**Comment by alya** [comment]
Updated the issue description.
