### ISSUE TITLE
The app keep getting crash during downloading any image on lightbox.

### ISSUE THREAD

**Issue by ArpanMondalGITHUB** [zulip/zulip-mobile#5903]
https://github.com/user-attachments/assets/2791efa3-fa05-4795-b1b4-8309e920adad

**Comment by ArpanMondalGITHUB** [comment]
it can be only phone's problem please check in your devices..i am using an android device..

**Comment by gnprice** [comment]
@ArpanMondalGITHUB adds [in a chat thread](https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/targetSdkVersion.2034.20.28Android.2014.29/near/1975399) that the download itself is successful. That's a helpful fact that mitigates the issue somewhat.

Still, because this is a crash (and because the user might reasonably assume the download failed and so not even discover that it succeeded), this is one of the few sorts of issues that we'll fix within this legacy app.
