### ISSUE TITLE
Add topics to the stream sidebar

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#74]

**Comment by timabbott** [comment]
I've heard this a few times from folks asking for feedback on the alpha.  Probably this should work like the  Android app's approach (of showing them indented and below the currently open stream in the streams sidebar), with maybe a caret type click target to the right of the stream name to open the list without narrowing?

There's an endpoint on the server that returns topic history that we can use to get historical topics beyond whatever messages be pull into cache as part of narrowing
`GET users/me/(?P<stream_id>\d+)/topics`

**Comment by TomaszKolek** [comment]
@zulipbot claim

**Comment by TomaszKolek** [comment]
@borisyankov @neerajwahi 
Please comment my potential approach:
1. Create function to get topics for particular stream
2. execute this function in getting initial info from server
3. create handler for new topic in the stream event from server
4. create state change event and reducer
5. Display on demand 

Sounds it reasonable?

**Comment by borisyankov** [comment]
1. Yes.
2. Execute on narrowing to a Stream
3. Yes. I am not sure if such an event exist though
4. Maybe. Not sure if the details are correct though (should discuss more)
5. Yep.

I think you can do each point in a separate commit/PR.

**Comment by TomaszKolek** [comment]
Ad 3
If it doesn't we should download topics every time on narrowing?
@timabbott Could you try to help us here?

Ad 4
I'm not familiar enough with React Native so maybe I'm talking nonsense.
Every time we download new topics for a stream we should change the state?

**Comment by timabbott** [comment]
There's no such thing as a "new topic" event -- topic is more of a field on a message than an object (there's no database table or anything for them).

The webapp just displays those topics that are present in the messages it has in cache from narrowing/scrolling, and one might want to do that to start.  However, there's this endpoint in `zproject/urls.py` that will fetch all historical topics for a stream:
```
    url(r'^users/me/(?P<stream_id>\d+)/topics$', rest_dispatch,
        {'GET': 'zerver.views.streams.get_topics_backend'}),
```
The intent is for that to be what gets called when you click the "more topics" button in the webapp (since that endpoint is slower than just fetching the last 100 messages on a stream, which is probably what we want for the initial load of a narrow); the same approach probably makes sense on mobile.

**Comment by dhruvdutt** [comment]
@zulipbot claim

**Comment by dhruvdutt** [comment]
@timabbott Do we have any specific endpoint for fetching the list of topics in a particular stream?
I can't find anything [here in docs](https://chat.zulip.org/api/get-all-streams).

**Comment by kunall17** [comment]
Yup @dhruvdutt we have the endpoint, look at the Tim's comment above! 

Anyways a PR of mine is already lying around https://github.com/zulip/zulip-mobile/pull/1398 but we decided to not to show in this fashion!

**Comment by dhruvdutt** [comment]
@kunall17 Ah! Thanks for the heads-up.

Have we still not decided how to show it?

**Comment by borisyankov** [comment]
@dhruvdutt I'll close this issue, as it gives the impression we have decided on a solution.
Mostly we will think of a better UI, the coding part is relatively straightforward.
I expect we tackle this next month.
